### ISSUE TITLE
Uncaught exception detected: <class 'aiohttp.errors.ClientDisconnectedError'>

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-server#1052]
``` 
2017-05-30 11:23:46 ERROR route.py:229 Uncaught exception detected: <class 'aiohttp.errors.ClientDisconnectedError'>
Traceback (most recent call last):
  File "/Users/noplay/code/gns3/gns3-server/gns3server/web/route.py", line 185, in control_schema
    request = yield from parse_request(request, input_schema, raw)
  File "/Users/noplay/code/gns3/gns3-server/gns3server/web/route.py", line 45, in parse_request
    body = yield from request.read()
  File "/Users/noplay/.virtualenvs/gns3-server/lib/python3.6/site-packages/aiohttp/web_reqrep.py", line 382, in read
    chunk = yield from self._payload.readany()
  File "/Users/noplay/.virtualenvs/gns3-server/lib/python3.6/site-packages/aiohttp/streams.py", line 498, in wrapper
    result = yield from func(self, *args, **kw)
  File "/Users/noplay/.virtualenvs/gns3-server/lib/python3.6/site-packages/aiohttp/streams.py", line 575, in readany
    return (yield from super().readany())
  File "/Users/noplay/.virtualenvs/gns3-server/lib/python3.6/site-packages/aiohttp/streams.py", line 288, in readany
    yield from self._wait('readany')
  File "/Users/noplay/.virtualenvs/gns3-server/lib/python3.6/site-packages/aiohttp/streams.py", line 208, in _wait
    yield from waiter
aiohttp.errors.ClientDisconnectedError
```

**Comment by noplay** [comment]
Wrong aiohttp version
