### ISSUE TITLE
AttributeError: can't set attribute

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-server#1084]
https://sentry.io/gns3/gns3-server/issues/299440335/

```
AttributeError: can't set attribute
  File "gns3server/web/route.py", line 195, in control_schema
    yield from func(request, response)
  File "gns3server/handlers/api/controller/node_handler.py", line 54, in create
    node = yield from project.add_node(compute, request.json.pop("name"), request.json.pop("node_id", None), **request.json)
  File "gns3server/controller/project.py", line 339, in add_node
    node = Node(self, compute, name, node_id=node_id, node_type=node_type, **kwargs)
  File "gns3server/controller/node.py", line 97, in __init__
    raise e
  File "gns3server/controller/node.py", line 94, in __init__
    setattr(self, prop, kwargs[prop])

AttributeError: can't set attribute
```

**Comment by noplay** [comment]
Not able to reproduce. It's on a single user computer

**Comment by Cavorticus** [comment]
From Installed Appliances, added Cisco c7200 router to workspace. 
Edited configuration by adding Adapters to slots 1 through 6. PA-A1, PA-FE-TX, etc...
When saving changes, pop-up occurred with listed error. 
**Log snip:**
_Traceback (most recent call last):
  File "./gns3-server\gns3server\web\route.py", line 195, in control_schema
  File "./gns3-server\gns3server\handlers\api\controller\appliance_handler.py", line 73, in create_node_from_appliance
  File "./gns3-server\gns3server\controller\project.py", line 483, in add_node_from_appliance
  File "./gns3-server\gns3server\controller\project.py", line 520, in add_node
  File "./gns3-server\gns3server\controller\node.py", line 350, in create
  File "./gns3-server\gns3server\controller\node.py", line 416, in parse_node_response
  File "./gns3-server\gns3server\controller\node.py", line 616, in _list_ports
  File "./gns3-server\gns3server\controller\ports\port_factory.py", line 194, in __new__
AttributeError: can't set attribute_
