### ISSUE TITLE
Uploading IOU images is not working

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-server#1141]
```
Traceback (most recent call last):
  File "/Users/noplay/code/gns3/gns3-server/gns3server/web/route.py", line 195, in control_schema
    yield from func(request, response)
  File "/Users/noplay/code/gns3/gns3-server/gns3server/handlers/api/controller/appliance_handler.py", line 73, in create_node_from_appliance
    compute_id=request.json.get("compute_id"))
  File "/Users/noplay/code/gns3/gns3-server/gns3server/controller/project.py", line 424, in add_node_from_appliance
    node = yield from self.add_node(compute, name, node_id, node_type=node_type, **template)
  File "/Users/noplay/code/gns3/gns3-server/gns3server/controller/project.py", line 459, in add_node
    yield from node.create()
  File "/Users/noplay/code/gns3/gns3-server/gns3server/controller/node.py", line 332, in create
    res = yield from self._upload_missing_image(self._node_type, e.response["image"])
  File "/Users/noplay/code/gns3/gns3-server/gns3server/controller/node.py", line 542, in _upload_missing_image
    yield from self._compute.post("/{}/images/{}".format(self._node_type, os.path.basename(img)), data=f, timeout=None)
  File "/Users/noplay/code/gns3/gns3-server/gns3server/controller/compute.py", line 568, in post
    response = yield from self.http_query("POST", path, data, **kwargs)
  File "/Users/noplay/code/gns3/gns3-server/gns3server/controller/compute.py", line 365, in http_query
    response = yield from self._run_http_query(method, path, data=data, **kwargs)
  File "/Users/noplay/code/gns3/gns3-server/gns3server/controller/compute.py", line 508, in _run_http_query
    response = yield from self._session().request(method, url, headers=headers, data=data, auth=self._auth, chunked=chunked, timeout=timeout)
  File "/Users/noplay/.virtualenvs/gns3-server/lib/python3.6/site-packages/aiohttp/helpers.py", line 91, in __iter__
    ret = yield from self._coro
  File "/Users/noplay/.virtualenvs/gns3-server/lib/python3.6/site-packages/aiohttp/client.py", line 226, in _request
    session=self)
  File "/Users/noplay/.virtualenvs/gns3-server/lib/python3.6/site-packages/aiohttp/client_reqrep.py", line 104, in __init__
    self.update_body_from_data(data)
  File "/Users/noplay/.virtualenvs/gns3-server/lib/python3.6/site-packages/aiohttp/client_reqrep.py", line 264, in update_body_from_data
    body = FormData(body)()
  File "/Users/noplay/.virtualenvs/gns3-server/lib/python3.6/site-packages/aiohttp/formdata.py", line 28, in __init__
    self.add_fields(*fields)
  File "/Users/noplay/.virtualenvs/gns3-server/lib/python3.6/site-packages/aiohttp/formdata.py", line 90, in add_fields
    .format(rec))
TypeError: Only io.IOBase, multidict and (name, file) pairs allowed, use .add_field() for passing more complex parameters, got <generator object Compute._run_http_query.<locals>.send_data at 0x10846aeb8>

```

**Comment by noplay** [comment]
Seem to be a regression due to the switch to recent aiohttp version
