### ISSUE TITLE
Exception while creating Cloud node on Windows

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-server#1174]
```
2017-08-29 03:33:38 ERROR base_events.py:1259 Task exception was never retrieved
future: <Task finished coro=<AsyncioTelnetServer.run() done, defined at ./gns3-server\gns3server\utils\asyncio\telnet_server.py:188> exception=AssertionError() created at C:\Python36-x64\lib\asyncio\streams.py:240>
source_traceback: Object created at (most recent call last):
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "C:\Python36-x64\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "C:\Python36-x64\lib\site-packages\cx_Freeze\initscripts\Console.py", line 24, in <module>
  File "gns3-server/gns3server/main.py", line 87, in <module>
  File "gns3-server/gns3server/main.py", line 83, in main
  File "./gns3-server\gns3server\run.py", line 250, in run
  File "./gns3-server\gns3server\web\web_server.py", line 279, in run
  File "C:\Python36-x64\lib\asyncio\base_events.py", line 421, in run_forever
  File "C:\Python36-x64\lib\asyncio\base_events.py", line 1417, in _run_once
  File "C:\Python36-x64\lib\asyncio\events.py", line 127, in _run
  File "C:\Python36-x64\lib\asyncio\streams.py", line 240, in connection_made
Traceback (most recent call last):
  File "./gns3-server\gns3server\utils\asyncio\telnet_server.py", line 196, in run
  File "C:\Python36-x64\lib\asyncio\coroutines.py", line 210, in coro
  File "./gns3-server\gns3server\utils\asyncio\embed_shell.py", line 199, in connected
  File "C:\Python36-x64\lib\site-packages\prompt_toolkit\interface.py", line 81, in __init__
  File "C:\Python36-x64\lib\site-packages\prompt_toolkit\input.py", line 67, in __init__
AssertionError
```

**Comment by ziajka** [comment]
I think it's gonna be mine :)

**Comment by grossmj** [comment]
This is with latest 2.1 build :)

**Comment by ziajka** [comment]
ok!

**Comment by ziajka** [comment]
@grossmj I tried to reproduce that wit the last three nightly builds however it seems to work.

I'm doing it in a way:
1. install GNS3
2. add Cloud node to the project (drag).

**Comment by grossmj** [comment]
Sorry, actually I noticed I was running the server directly from the code, not the compiled version. Everything worked after reinstalling the dependencies using pip. I think it is safe to close this issue.
