### ISSUE TITLE
version: 1.5.2 Could not connect to 127.0.0.1 on port 3080: [Errno 111] Connection refused

### ISSUE THREAD

**Issue by RJLWTF** [GNS3/gns3-server#1182]
Hello, my new GNS3 simulator cannot work,How can I solve this problem? 
journal:
client log:
`GNS3 GUI version 1.5.2
Copyright (c) 2007-2017 GNS3 Technologies Inc.
2017-09-25 09:30:41 INFO logger.py:106 Log level: INFO
2017-09-25 09:30:41 INFO servers.py:103 New local server connection http://127.0.0.1:3080 registered
2017-09-25 09:30:41 ERROR __init__.py:144 vmware command not found
2017-09-25 09:30:41 INFO __init__.py:181 VPCS module reset
2017-09-25 09:30:41 INFO __init__.py:322 Dynamips module reset
2017-09-25 09:30:41 INFO __init__.py:262 IOU module reset
2017-09-25 09:30:41 INFO __init__.py:256 QEMU module reset
2017-09-25 09:30:41 INFO __init__.py:302 VirtualBox module reset
2017-09-25 09:30:41 INFO __init__.py:369 VMware module reset
2017-09-25 09:30:41 INFO __init__.py:193 Docker module reset
2017-09-25 09:30:41 INFO __init__.py:70 Built-in module reset
2017-09-25 09:30:41 INFO topology.py:408 Topology reset
2017-09-25 09:30:41 INFO servers.py:537 Starting local server process with "/usr/bin/gns3server" --host=127.0.0.1 --port=3080 --local --controller --log="/home/raojl/.config/GNS3/gns3_server.log" --pid="/home/raojl/.config/GNS3/gns3_server.pid"
2017-09-25 09:30:41 INFO servers.py:550 Local server process has started (PID=4299)
/usr/lib/python3.5/site-packages/raven/conf/remote.py:67: UserWarning: Transport selection via DSN is deprecated. You should explicitly pass the transport class to Client() instead.
  warnings.warn('Transport selection via DSN is deprecated. You should explicitly pass the transport class to Client() instead.')
2017-09-25 09:31:11 CRITICAL progress_dialog.py:159 WaitForConnectionWorker thread stopping with an error: Could not connect to 127.0.0.1 on port 3080: [Errno 111] Connection refused
2017-09-25 09:31:11 CRITICAL __init__.py:95 Could not connect to 127.0.0.1 on port 3080: [Errno 111] Connection refused`
==============================================================================
server log:
`2017-09-25 09:28:14 INFO run.py:214 GNS3 server version 1.5.2
2017-09-25 09:28:14 INFO run.py:216 Copyright (c) 2007-2017 GNS3 Technologies Inc.
2017-09-25 09:28:14 INFO run.py:219 Config file /home/raojl/.config/GNS3/gns3_server.conf loaded
2017-09-25 09:28:14 INFO run.py:224 Controller mode is enabled.
2017-09-25 09:28:14 WARNING run.py:227 Local mode is enabled. Beware, clients will have full control on your filesystem
2017-09-25 09:28:14 INFO run.py:235 Running with Python 3.5.4 and has PID 4224
2017-09-25 09:28:14 INFO run.py:78 Current locale is en_US.UTF-8
2017-09-25 09:28:14 INFO server.py:241 Starting server on 127.0.0.1:3080
2017-09-25 09:28:14 CRITICAL run.py:260 Critical error while running the server: __init__() got multiple values for argument 'handler'
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/gns3server/run.py", line 254, in run
    server.run()
  File "/usr/lib/python3.5/site-packages/gns3server/server.py", line 242, in run
    self._handler = app.make_handler(handler=RequestHandler)
  File "/usr/lib64/python3.5/site-packages/aiohttp/web.py", line 251, in make_handler
    loop=self.loop, **kwargs)
TypeError: __init__() got multiple values for argument 'handler'
2017-09-25 09:28:15 ERROR crash_report.py:106 Can't send crash report to Sentry: ('API key is disabled', 401)
`

**Comment by grossmj** [comment]
Please try with a recent version of GNS3: version. 2.0.3 (stable) or version 2.1 RC1 (unstable)

**Comment by RJLWTF** [comment]
Sorry, I just installed gns3-server===2.0.4dev1- fc87871, but it can't run, but I have installed aiohttp module.
![importerror](https://user-images.githubusercontent.com/19492031/32045251-67b5c902-ba05-11e7-84e8-bdfc7bab7799.png)

**Comment by grossmj** [comment]
Make sure you run the setup script with `python3 setup.py install`

**Comment by RJLWTF** [comment]
I installed it this way, and tried other versions, too. I don't know what's going on, and then I import this module in Python shell, like the following error.
Is this a problem with the aiohttp module?
![i](https://user-images.githubusercontent.com/19492031/32099616-909c0df0-bad6-11e7-8969-1c1844a62774.png)
