### ISSUE TITLE
Error while getting appliance list: Traceback (most recent call last):

### ISSUE THREAD

**Issue by netdiscussion** [GNS3/gns3-server#1258]
Dear,
I did new installation by using "GNS3-2.1.0a1-all-in-one".
when i open GNS3, i'm facing below issue.

 **Error while getting appliance list: Traceback (most recent call last):
  File "./gns3-server\gns3server\web\route.py", line 195, in control_schema
  File "C:\Python36-x64\lib\asyncio\coroutines.py", line 210, in coro
  File "./gns3-server\gns3server\handlers\api\controller\appliance_handler.py", line 51, in list
  File "./gns3-server\gns3server\web\response.py", line 104, in json
  File "./gns3-server\gns3server\controller\appliance.py", line 79, in __json__
KeyError: 'name'**
 
Waiting for positive response.

Regards,

**Comment by cioby23** [comment]
You are using an old alpha version of GNS3. Try to use the latest version available here https://github.com/GNS3/gns3-gui/releases/download/v2.1.2/GNS3-2.1.2-all-in-one.exe

**Comment by netdiscussion** [comment]
I tried 2.1.2 initially & received messages regarding "Python34.dll", I installed python 3.4 & 3.6 but problem was same. so i downloaded older verified version because newer version is not verified.

**Comment by grossmj** [comment]
@netdiscussion please can you post the error messages? Thanks!

**Comment by netdiscussion** [comment]
@grossmj 
**Please find below error messages.
Error while getting appliance list: Traceback (most recent call last):
File "./gns3-server\gns3server\web\route.py", line 195, in control_schema
File "C:\Python36-x64\lib\asyncio\coroutines.py", line 210, in coro
File "./gns3-server\gns3server\handlers\api\controller\appliance_handler.py", line 51, in list
File "./gns3-server\gns3server\web\response.py", line 104, in json
File "./gns3-server\gns3server\controller\appliance.py", line 79, in json
KeyError: 'name'**
