### ISSUE TITLE
Could not start iouyap: [Errno 8] Exec format error

### ISSUE THREAD

**Issue by lvalero** [GNS3/gns3-server#126]
Hello,

difficult to spot the source of the problem, when upgrading to v1.3.0, i opened a project made with previous version (made of vbox + IOU) and i got that message trying to start IOU devices :

Server error from 127.0.0.1:8000: IOU5: Could not start iouyap: [Errno 8] Exec format error

on terminal more output :
2015-03-31 11:08:11 ERROR route.py:145 VM error detected: <class 'gns3server.modules.iou.iou_error.IOUError'>
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/gns3_server-1.3.0-py3.4.egg/gns3server/modules/iou/iou_vm.py", line 510, in _start_iouyap
    cwd=self.working_dir)
  File "/usr/lib/python3.4/asyncio/subprocess.py", line 193, in create_subprocess_exec
    stderr=stderr, **kwds)
  File "/usr/lib/python3.4/asyncio/base_events.py", line 652, in subprocess_exec
    bufsize, **kwargs)
  File "/usr/lib/python3.4/asyncio/unix_events.py", line 157, in _make_subprocess_transport
    extra=extra, **kwargs)
  File "/usr/lib/python3.4/asyncio/base_subprocess.py", line 29, in __init__
    stderr=stderr, bufsize=bufsize, **kwargs)
  File "/usr/lib/python3.4/asyncio/unix_events.py", line 491, in _start
    universal_newlines=False, bufsize=bufsize, **kwargs)
  File "/usr/lib/python3.4/subprocess.py", line 848, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.4/subprocess.py", line 1446, in _execute_child
    raise child_exception_type(errno_num, err_msg)
OSError: [Errno 8] Exec format error
 
 
During handling of the above exception, another exception occurred:
 
 
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/gns3_server-1.3.0-py3.4.egg/gns3server/web/route.py", line 139, in control_schema
    yield from func(request, response)
  File "/usr/local/lib/python3.4/dist-packages/gns3_server-1.3.0-py3.4.egg/gns3server/handlers/api/iou_handler.py", line 161, in start
    yield from vm.start()
  File "/usr/local/lib/python3.4/dist-packages/gns3_server-1.3.0-py3.4.egg/gns3server/modules/iou/iou_vm.py", line 480, in start
    yield from self._start_iouyap()
  File "/usr/local/lib/python3.4/dist-packages/gns3_server-1.3.0-py3.4.egg/gns3server/modules/iou/iou_vm.py", line 516, in _start_iouyap
    raise IOUError("Could not start iouyap: {}\n{}".format(e, iouyap_stdout))
gns3server.modules.iou.iou_error.IOUError: Could not start iouyap: [Errno 8] Exec format error
 
 
2015-03-31 11:08:11 INFO http_client.py:335 Response error: Error downloading http://127.0.0.1:8000/v1/projects/957273ff-18ad-4f6e-8c06-2d6ee998dc0e/iou/vms/0940e6bc-ff38-4817-8315-cbb915851f1a/start - server replied: Conflict
2015-03-31 11:08:11 INFO server.py:169 127.0.0.1 - - Tue, 31 Mar 2015 15:08:11 GMT "POST /v1/projects/957273ff-18ad-4f6e-8c06-2d6ee998dc0e/iou/vms/0940e6bc-ff38-4817-8315-cbb915851f1a/start HTTP/1.1" 409 320 "-" "GNS3 QT Client v1.3.0"
2015-03-31 11:08:11 ERROR vm.py:96 error while starting IOU1: Could not start iouyap: [Errno 8] Exec format error

I switch back to v1.2.3 and restore project files which were kind of damaged (loss of snapshots).

Regards

**Comment by grossmj** [comment]
Looks like we are trying to use a 32-bit version of iouyap on a 64-bit only system (this is usually what Exec format error means). Can you check?

Thanks,

**Comment by lvalero** [comment]
Hello Jeremy,

Actualy i was using iouyap with gns3 v1.2.3 on a 64bits computer, i just
upgrade gns3 on the same computer.

Regards.

On Tue, Mar 31, 2015 at 10:14 PM, Jeremy Grossmann <notifications@github.com

**Comment by noplay** [comment]
If you start iouyap from command line it's works?

**Comment by lvalero** [comment]
Allo Julien,

tu veux dire comme ça :
root@gns3lab:/usr/local/bin# ./iouyap -V
iouyap version 0.95.0

ou avec d'autres options ?

Merci

On Thu, Apr 2, 2015 at 5:11 AM, Julien Duponchelle <notifications@github.com

**Comment by noplay** [comment]
Oui

**Comment by noplay** [comment]
Do you have only one version of iouyap in your path?

You can force the iouyap path in 
 ~/.config/GNS3/gns3_server.conf

By adding a section:
```
[IOU]
iouyap_path = /usr/local/bin/iouyap
iourc_path = /tmp/iourc.txt
```

**Comment by noplay** [comment]
Thanks for the debug help

**Comment by lvalero** [comment]
Yes i have only one version, so to sum up :

- i faced the message i sent you trying to start iou devices, i noticed
that when i tried to start them a second time they went on, but the lab
project was not working (iou routers where linked on a "dump" switch, and
there was no connectivity), i also noticed that my snapshots disappeared
from the project, and my predefined iou devices and dynamips devices were
not present, and so my predefined virtualbox vm.

Regards,
Lionel.



On Thu, Apr 2, 2015 at 9:59 AM, Julien Duponchelle <notifications@github.com

**Comment by lvalero** [comment]
when i upgraded to 1.3.0 i am pretty sure i had to put iouyap and licence
path back, as they disappeared.

**Comment by noplay** [comment]
Did you try with the 1.3.2 ? Sorry for the delay...

**Comment by lvalero** [comment]
Yes everything is OK thanks

Regards
Le 2015-05-04 03:33, "Julien Duponchelle" <notifications@github.com> a
écrit :

**Comment by noplay** [comment]
Thanks for the feedback
