### ISSUE TITLE
New version 2.1.2 crash on MAC OSX

### ISSUE THREAD

**Issue by MrMic** [GNS3/gns3-server#1260]
Here is the message:
 Local server process has stopped
Killed ghost process dynamips
/Applications/GNS3.app/Contents/MacOS/lib/python3.6/raven/conf/remote.py:88: UserWarning: Transport selection via DSN is deprecated. You should explicitly pass the transport class to Client() instead.

Mac OSX : 10.13.2 High Sierra
The previous version works fine  (2.1.1) .... :(

**Comment by grossmj** [comment]
Assuming you use the GNS3 VM, the current workaround is to manually start it before you start GNS3 itself.

**Comment by MrMic** [comment]
No ! I use local server

**Comment by MrMic** [comment]
But i got a VM too with VMWare fusion.

**Comment by grossmj** [comment]
The local server has crashed, please post the content of `~/.config/GNS3/gns3_server.log` right after the crash happens.

**Comment by MrMic** [comment]
Here it is:
------ 8< --------------------------- >8 ---

2018-01-11 10:27:44 INFO run.py:213 GNS3 server version 2.1.2
2018-01-11 10:27:44 INFO run.py:215 Copyright (c) 2007-2018 GNS3 Technologies Inc.
2018-01-11 10:27:44 INFO run.py:218 Config file /Users/mic/.config/GNS3/gns3_server.conf loaded
2018-01-11 10:27:44 WARNING run.py:224 Local mode is enabled. Beware, clients will have full control on your filesystem
2018-01-11 10:27:44 INFO run.py:232 Running with Python 3.6.4 and has PID 17135
2018-01-11 10:27:44 INFO web_server.py:275 Starting server on 127.0.0.1:3080
2018-01-11 10:27:44 INFO __init__.py:65 Load controller configuration file /Users/mic/.config/GNS3/gns3_controller.conf
2018-01-11 10:27:44 INFO __init__.py:143 Start controller
2018-01-11 10:27:44 INFO compute.py:79 Create compute local
2018-01-11 10:27:44 INFO __init__.py:276 Start the GNS3 VM
2018-01-11 10:27:44 INFO compute.py:79 Create compute vm
2018-01-11 10:27:44 INFO helpers.py:529 127.0.0.1 - - [11/Jan/2018:09:27:44 +0000] "GET /v2/version HTTP/1.1" 200 225 "-" "GNS3 QT Client v2.1.2"
2018-01-11 10:27:44 INFO helpers.py:529 127.0.0.1 - - [11/Jan/2018:09:27:44 +0000] "GET /v2/appliances HTTP/1.1" 200 6308 "-" "GNS3 QT Client v2.1.2"
2018-01-11 10:27:44 INFO helpers.py:529 127.0.0.1 - - [11/Jan/2018:09:27:44 +0000] "GET /v2/appliances/templates HTTP/1.1" 200 471060 "-" "GNS3 QT Client v2.1.2"
2018-01-11 10:27:44 INFO helpers.py:529 127.0.0.1 - - [11/Jan/2018:09:27:44 +0000] "GET /v2/version HTTP/1.1" 200 225 "-" "GNS3 QT Client v2.1.2"
2018-01-11 10:27:44 INFO helpers.py:529 127.0.0.1 - - [11/Jan/2018:09:27:44 +0000] "GET /v2/projects HTTP/1.1" 200 8917 "-" "GNS3 QT Client v2.1.2"
2018-01-11 10:27:44 INFO helpers.py:529 127.0.0.1 - - [11/Jan/2018:09:27:44 +0000] "GET /v2/computes HTTP/1.1" 200 1007 "-" "GNS3 QT Client v2.1.2"
2018-01-11 10:27:44 INFO __init__.py:574 Searching for VMware VMs in inventory file "/Users/mic/Library/Application Support/VMware Fusion/vmInventory"
2018-01-11 10:27:44 INFO __init__.py:390 Executing vmrun with command: '/Applications/VMware Fusion.app/Contents/Library/vmrun' -T fusion checkToolsState '/Users/mic/Documents/Virtual Machines.localized/GNS3 VM 2.vmwarevm/GNS3 VM 2.vmx'
2018-01-11 10:27:44 INFO helpers.py:529 127.0.0.1 - - [11/Jan/2018:09:27:44 +0000] "GET /v2/projects HTTP/1.1" 200 8917 "-" "GNS3 QT Client v2.1.2"
2018-01-11 10:27:44 INFO helpers.py:529 127.0.0.1 - - [11/Jan/2018:09:27:44 +0000] "GET /v2/symbols/:/symbols/qemu_guest.svg/raw HTTP/1.1" 200 45561 "-" "GNS3 QT Client v2.1.2"
2018-01-11 10:27:44 INFO helpers.py:529 127.0.0.1 - - [11/Jan/2018:09:27:44 +0000] "GET /v2/symbols/:/symbols/multilayer_switch.svg/raw HTTP/1.1" 200 21516 "-" "GNS3 QT Client v2.1.2"
2018-01-11 10:27:44 INFO helpers.py:529 127.0.0.1 - - [11/Jan/2018:09:27:44 +0000] "GET /v2/symbols/:/symbols/router.svg/raw HTTP/1.1" 200 11036 "-" "GNS3 QT Client v2.1.2"
2018-01-11 10:27:44 INFO helpers.py:529 127.0.0.1 - - [11/Jan/2018:09:27:44 +0000] "GET /v2/symbols/:/symbols/vmware_guest.svg/raw HTTP/1.1" 200 20015 "-" "GNS3 QT Client v2.1.2"
2018-01-11 10:27:44 INFO helpers.py:529 127.0.0.1 - - [11/Jan/2018:09:27:44 +0000] "GET /v2/symbols/:/symbols/vbox_guest.svg/raw HTTP/1.1" 200 207094 "-" "GNS3 QT Client v2.1.2"
2018-01-11 10:27:44 INFO helpers.py:529 127.0.0.1 - - [11/Jan/2018:09:27:44 +0000] "GET /v2/symbols/:/symbols/vpcs_guest.svg/raw HTTP/1.1" 200 19494 "-" "GNS3 QT Client v2.1.2"
2018-01-11 10:27:44 INFO helpers.py:529 127.0.0.1 - - [11/Jan/2018:09:27:44 +0000] "GET /v2/symbols/:/symbols/cloud.svg/raw HTTP/1.1" 200 27981 "-" "GNS3 QT Client v2.1.2"
2018-01-11 10:27:44 INFO helpers.py:529 127.0.0.1 - - [11/Jan/2018:09:27:44 +0000] "GET /v2/symbols/:/symbols/ethernet_switch.svg/raw HTTP/1.1" 200 9272 "-" "GNS3 QT Client v2.1.2"
2018-01-11 10:27:44 INFO helpers.py:529 127.0.0.1 - - [11/Jan/2018:09:27:44 +0000] "GET /v2/symbols/:/symbols/hub.svg/raw HTTP/1.1" 200 7635 "-" "GNS3 QT Client v2.1.2"
2018-01-11 10:27:44 INFO helpers.py:529 127.0.0.1 - - [11/Jan/2018:09:27:44 +0000] "GET /v2/symbols/:/symbols/frame_relay_switch.svg/raw HTTP/1.1" 200 10026 "-" "GNS3 QT Client v2.1.2"
2018-01-11 10:27:44 INFO helpers.py:529 127.0.0.1 - - [11/Jan/2018:09:27:44 +0000] "GET /v2/symbols/:/symbols/atm_switch.svg/raw HTTP/1.1" 200 9958 "-" "GNS3 QT Client v2.1.2"
2018-01-11 10:27:44 INFO helpers.py:529 127.0.0.1 - - [11/Jan/2018:09:27:44 +0000] "GET /v2/symbols/fortinet.svg/raw HTTP/1.1" 200 18842 "-" "GNS3 QT Client v2.1.2"
2018-01-11 10:27:44 INFO helpers.py:529 127.0.0.1 - - [11/Jan/2018:09:27:44 +0000] "GET /v2/symbols/mgmt_station.svg/raw HTTP/1.1" 200 18842 "-" "GNS3 QT Client v2.1.2"
2018-01-11 10:27:44 INFO helpers.py:529 127.0.0.1 - - [11/Jan/2018:09:27:44 +0000] "GET /v2/symbols/:/symbols/firewall.svg/raw HTTP/1.1" 200 9625 "-" "GNS3 QT Client v2.1.2"
2018-01-11 10:27:44 INFO helpers.py:529 127.0.0.1 - - [11/Jan/2018:09:27:44 +0000] "GET /v2/symbols/:/symbols/guest.svg/raw HTTP/1.1" 200 18842 "-" "GNS3 QT Client v2.1.2"
2018-01-11 10:27:44 INFO helpers.py:529 127.0.0.1 - - [11/Jan/2018:09:27:44 +0000] "GET /v2/symbols/linux_guest.svg/raw HTTP/1.1" 200 18842 "-" "GNS3 QT Client v2.1.2"
2018-01-11 10:27:44 INFO helpers.py:529 127.0.0.1 - - [11/Jan/2018:09:27:44 +0000] "GET /v2/symbols/ostinato-3d-icon.svg/raw HTTP/1.1" 200 18842 "-" "GNS3 QT Client v2.1.2"
2018-01-11 10:27:44 INFO helpers.py:529 127.0.0.1 - - [11/Jan/2018:09:27:44 +0000] "GET /v2/symbols/loadbalancer.svg/raw HTTP/1.1" 200 18842 "-" "GNS3 QT Client v2.1.2"
2018-01-11 10:27:44 INFO helpers.py:529 127.0.0.1 - - [11/Jan/2018:09:27:44 +0000] "GET /v2/symbols/microsoft.svg/raw HTTP/1.1" 200 18842 "-" "GNS3 QT Client v2.1.2"
2018-01-11 10:27:44 INFO helpers.py:529 127.0.0.1 - - [11/Jan/2018:09:27:44 +0000] "GET /v2/symbols/vRIN.svg/raw HTTP/1.1" 200 18842 "-" "GNS3 QT Client v2.1.2"
2018-01-11 10:27:44 INFO helpers.py:529 127.0.0.1 - - [11/Jan/2018:09:27:44 +0000] "GET /v2/symbols/:/symbols/ids.svg/raw HTTP/1.1" 200 13372 "-" "GNS3 QT Client v2.1.2"
2018-01-11 10:27:44 INFO helpers.py:529 127.0.0.1 - - [11/Jan/2018:09:27:44 +0000] "GET /v2/symbols/juniper-vqfx.svg/raw HTTP/1.1" 200 18842 "-" "GNS3 QT Client v2.1.2"
2018-01-11 10:27:44 INFO helpers.py:529 127.0.0.1 - - [11/Jan/2018:09:27:44 +0000] "GET /v2/symbols/juniper-vmx.svg/raw HTTP/1.1" 200 18842 "-" "GNS3 QT Client v2.1.2"
2018-01-11 10:27:44 INFO helpers.py:529 127.0.0.1 - - [11/Jan/2018:09:27:44 +0000] "GET /v2/symbols/:/symbols/asa.svg/raw HTTP/1.1" 200 18811 "-" "GNS3 QT Client v2.1.2"
2018-01-11 10:27:44 INFO helpers.py:529 127.0.0.1 - - [11/Jan/2018:09:27:44 +0000] "GET /v2/symbols/pan-vm-fw.svg/raw HTTP/1.1" 200 18842 "-" "GNS3 QT Client v2.1.2"
2018-01-11 10:27:44 INFO helpers.py:529 127.0.0.1 - - [11/Jan/2018:09:27:44 +0000] "GET /v2/symbols/cisco-fmcv.svg/raw HTTP/1.1" 200 18842 "-" "GNS3 QT Client v2.1.2"
2018-01-11 10:27:44 INFO helpers.py:529 127.0.0.1 - - [11/Jan/2018:09:27:44 +0000] "GET /v2/symbols/:/symbols/wlan_controller.svg/raw HTTP/1.1" 200 261469 "-" "GNS3 QT Client v2.1.2"
2018-01-11 10:27:44 INFO helpers.py:529 127.0.0.1 - - [11/Jan/2018:09:27:44 +0000] "GET /v2/symbols/mgmt_station_docker.svg/raw HTTP/1.1" 200 18842 "-" "GNS3 QT Client v2.1.2"
2018-01-11 10:27:44 INFO helpers.py:529 127.0.0.1 - - [11/Jan/2018:09:27:44 +0000] "GET /v2/symbols/cisco-ise.svg/raw HTTP/1.1" 200 18842 "-" "GNS3 QT Client v2.1.2"
2018-01-11 10:27:44 INFO helpers.py:529 127.0.0.1 - - [11/Jan/2018:09:27:44 +0000] "GET /v2/symbols/:/symbols/router_firewall.svg/raw HTTP/1.1" 200 50060 "-" "GNS3 QT Client v2.1.2"
2018-01-11 10:27:44 INFO helpers.py:529 127.0.0.1 - - [11/Jan/2018:09:27:44 +0000] "GET /v2/symbols/firefox.svg/raw HTTP/1.1" 200 18842 "-" "GNS3 QT Client v2.1.2"
2018-01-11 10:27:44 INFO helpers.py:529 127.0.0.1 - - [11/Jan/2018:09:27:44 +0000] "GET /v2/symbols/securityonion-logo.png/raw HTTP/1.1" 200 18842 "-" "GNS3 QT Client v2.1.2"
2018-01-11 10:27:45 INFO __init__.py:390 Executing vmrun with command: '/Applications/VMware Fusion.app/Contents/Library/vmrun' -T fusion list
2018-01-11 10:27:45 INFO vmware_gns3_vm.py:150 Update GNS3 VM settings
2018-01-11 10:27:45 INFO vmware_gns3_vm.py:84 GNS3 VM vCPU count set to 1 and RAM amount set to 2048
2018-01-11 10:27:45 INFO __init__.py:390 Executing vmrun with command: '/Applications/VMware Fusion.app/Contents/Library/vmrun' -T fusion start '/Users/mic/Documents/Virtual Machines.localized/GNS3 VM 2.vmwarevm/GNS3 VM 2.vmx'
2018-01-11 10:27:46 INFO helpers.py:529 127.0.0.1 - - [11/Jan/2018:09:27:46 +0000] "GET /v2/compute/capabilities HTTP/1.1" 200 499 "-" "Python/3.6 aiohttp/2.3.7"
2018-01-11 10:27:50 INFO helpers.py:529 127.0.0.1 - - [11/Jan/2018:09:27:50 +0000] "GET /v2/computes HTTP/1.1" 200 1371 "-" "GNS3 QT Client v2.1.2"
2018-01-11 10:27:52 INFO vmware_gns3_vm.py:160 GNS3 VM has been started
2018-01-11 10:27:52 INFO vmware_gns3_vm.py:165 Waiting for GNS3 VM IP
2018-01-11 10:27:52 INFO project.py:80 Project 574e12bd-019c-49e5-a2c8-9c0d5810d424 with path '/Users/mic/GNS3/projects/ASA' created
2018-01-11 10:27:52 INFO helpers.py:529 127.0.0.1 - - [11/Jan/2018:09:27:52 +0000] "POST /v2/compute/projects HTTP/1.1" 201 273 "-" "Python/3.6 aiohttp/2.3.7"
2018-01-11 10:27:52 INFO qemu_vm.py:178 QEMU VM "ASA-1" [02168210-95bc-4a9e-a4d7-221b1c6c06a7] has set the QEMU path to /Applications/GNS3.app/Contents/Resources/qemu/bin/qemu-system-x86_64
2018-01-11 10:27:52 INFO qemu_vm.py:542 QEMU VM "ASA-1" [02168210-95bc-4a9e-a4d7-221b1c6c06a7]: MAC address changed to 00:d4:24:06:a7:00
2018-01-11 10:27:52 INFO qemu_vm.py:490 QEMU VM "ASA-1" [02168210-95bc-4a9e-a4d7-221b1c6c06a7]: number of Ethernet adapters changed to 1
2018-01-11 10:27:52 INFO qemu_vm.py:123 QEMU VM "ASA-1" [02168210-95bc-4a9e-a4d7-221b1c6c06a7] has been created
2018-01-11 10:27:52 INFO base_node.py:260 Qemu: ASA-1 [02168210-95bc-4a9e-a4d7-221b1c6c06a7] created
2018-01-11 10:27:52 INFO qemu_vm.py:490 QEMU VM "ASA-1" [02168210-95bc-4a9e-a4d7-221b1c6c06a7]: number of Ethernet adapters changed to 4
2018-01-11 10:27:52 INFO qemu_vm.py:219 QEMU VM "ASA-1" [02168210-95bc-4a9e-a4d7-221b1c6c06a7] has set the QEMU hda_disk_image path to /Users/mic/GNS3/images/QEMU/FLASH
2018-01-11 10:27:52 INFO qemu_vm.py:738 QEMU VM "ASA-1" [02168210-95bc-4a9e-a4d7-221b1c6c06a7] has set the QEMU initrd path to /Users/mic/GNS3/images/QEMU/asa842-initrd.gz
2018-01-11 10:27:52 INFO qemu_vm.py:787 QEMU VM "ASA-1" [02168210-95bc-4a9e-a4d7-221b1c6c06a7] has set the QEMU kernel command line to -append ide_generic.probe_mask=0x01 ide_core.chs=0.0:980,16,32 auto nousb console=ttyS0,9600 bigphysarea=65536
2018-01-11 10:27:52 INFO qemu_vm.py:764 QEMU VM "ASA-1" [02168210-95bc-4a9e-a4d7-221b1c6c06a7] has set the QEMU kernel image path to /Users/mic/GNS3/images/QEMU/asa842-vmlinuz
2018-01-11 10:27:52 INFO qemu_vm.py:563 QEMU VM "ASA-1" [02168210-95bc-4a9e-a4d7-221b1c6c06a7] has enabled legacy networking
2018-01-11 10:27:52 INFO qemu_vm.py:703 QEMU VM "ASA-1" [02168210-95bc-4a9e-a4d7-221b1c6c06a7] has set the QEMU options to -m 1024 -icount auto -hdachs 980,16,32
2018-01-11 10:27:52 INFO qemu_vm.py:638 QEMU VM "ASA-1" [02168210-95bc-4a9e-a4d7-221b1c6c06a7] has set the process priority to normal
2018-01-11 10:27:52 INFO qemu_vm.py:659 QEMU VM "ASA-1" [02168210-95bc-4a9e-a4d7-221b1c6c06a7] has set the RAM to 1024
2018-01-11 10:27:52 INFO helpers.py:529 127.0.0.1 - - [11/Jan/2018:09:27:52 +0000] "POST /v2/compute/projects/574e12bd-019c-49e5-a2c8-9c0d5810d424/qemu/nodes HTTP/1.1" 201 1872 "-" "Python/3.6 aiohttp/2.3.7"
2018-01-11 10:27:52 INFO __init__.py:307 Creating new hypervisor 127.0.0.1:54067 with working directory /Users/mic/GNS3/projects/ASA/project-files/dynamips
2018-01-11 10:27:52 INFO hypervisor.py:128 Starting Dynamips: ['/Applications/GNS3.app/Contents/Resources/dynamips', '-N1', '-l', 'dynamips_i1_log.txt', '-H', '127.0.0.1:54067']
2018-01-11 10:27:52 INFO hypervisor.py:130 Dynamips process logging to /Users/mic/GNS3/projects/ASA/project-files/dynamips/dynamips_i1_stdout.txt
2018-01-11 10:27:53 INFO hypervisor.py:137 Dynamips process started PID=17478
2018-01-11 10:27:53 INFO __init__.py:309 Hypervisor 127.0.0.1:54067 has successfully started
2018-01-11 10:27:53 INFO dynamips_hypervisor.py:93 Connected to Dynamips hypervisor after 0.0120 seconds
2018-01-11 10:27:53 INFO ethernet_switch.py:165 Ethernet switch "Ethernetswitch-1" [49e02218-d1f7-4138-ac16-ff68f2b55a50] has been created
2018-01-11 10:27:53 INFO helpers.py:529 127.0.0.1 - - [11/Jan/2018:09:27:53 +0000] "POST /v2/compute/projects/574e12bd-019c-49e5-a2c8-9c0d5810d424/ethernet_switch/nodes HTTP/1.1" 201 1571 "-" "Python/3.6 aiohttp/2.3.7"
2018-01-11 10:27:53 INFO helpers.py:529 127.0.0.1 - - [11/Jan/2018:09:27:53 +0000] "POST /v2/compute/projects/574e12bd-019c-49e5-a2c8-9c0d5810d424/ports/udp HTTP/1.1" 201 242 "-" "Python/3.6 aiohttp/2.3.7"
2018-01-11 10:27:53 INFO helpers.py:529 127.0.0.1 - - [11/Jan/2018:09:27:53 +0000] "POST /v2/compute/projects/574e12bd-019c-49e5-a2c8-9c0d5810d424/ports/udp HTTP/1.1" 201 242 "-" "Python/3.6 aiohttp/2.3.7"
2018-01-11 10:27:53 INFO qemu_vm.py:1155 QEMU VM "ASA-1" [02168210-95bc-4a9e-a4d7-221b1c6c06a7]: NIO UDP added to adapter 0
2018-01-11 10:27:53 INFO helpers.py:529 127.0.0.1 - - [11/Jan/2018:09:27:53 +0000] "POST /v2/compute/projects/574e12bd-019c-49e5-a2c8-9c0d5810d424/qemu/nodes/02168210-95bc-4a9e-a4d7-221b1c6c06a7/adapters/0/ports/0/nio HTTP/1.1" 201 377 "-" "Python/3.6 aiohttp/2.3.7"
2018-01-11 10:27:53 INFO ethernet_switch.py:254 Ethernet switch "Ethernetswitch-1" [49e02218-d1f7-4138-ac16-ff68f2b55a50]: NIO udp-8eafa0b6-de2b-409d-8063-377cfe85883e bound to port 0
2018-01-11 10:27:53 INFO ethernet_switch.py:327 Ethernet switch "Ethernetswitch-1" [49e02218-d1f7-4138-ac16-ff68f2b55a50]: port 0 set as an access port in VLAN 1
2018-01-11 10:27:53 INFO helpers.py:529 127.0.0.1 - - [11/Jan/2018:09:27:53 +0000] "POST /v2/compute/projects/574e12bd-019c-49e5-a2c8-9c0d5810d424/ethernet_switch/nodes/49e02218-d1f7-4138-ac16-ff68f2b55a50/adapters/0/ports/0/nio HTTP/1.1" 201 388 "-" "Python/3.6 aiohttp/2.3.7"
2018-01-11 10:27:53 INFO helpers.py:529 127.0.0.1 - - [11/Jan/2018:09:27:53 +0000] "POST /v2/projects/load HTTP/1.1" 201 621 "-" "GNS3 QT Client v2.1.2"
2018-01-11 10:27:53 INFO helpers.py:529 127.0.0.1 - - [11/Jan/2018:09:27:53 +0000] "GET /v2/projects/574e12bd-019c-49e5-a2c8-9c0d5810d424/nodes HTTP/1.1" 200 9157 "-" "GNS3 QT Client v2.1.2"
2018-01-11 10:27:53 INFO helpers.py:529 127.0.0.1 - - [11/Jan/2018:09:27:53 +0000] "GET /v2/projects/574e12bd-019c-49e5-a2c8-9c0d5810d424/links HTTP/1.1" 200 1470 "-" "GNS3 QT Client v2.1.2"
2018-01-11 10:27:53 INFO helpers.py:529 127.0.0.1 - - [11/Jan/2018:09:27:53 +0000] "GET /v2/projects/574e12bd-019c-49e5-a2c8-9c0d5810d424/drawings HTTP/1.1" 200 204 "-" "GNS3 QT Client v2.1.2"
2018-01-11 10:27:56 WARNING compute.py:414 Can't connect to compute vm
2018-01-11 10:27:56 INFO helpers.py:529 127.0.0.1 - - [11/Jan/2018:09:27:56 +0000] "GET /v2/computes HTTP/1.1" 200 1371 "-" "GNS3 QT Client v2.1.2"
2018-01-11 10:28:05 INFO vmware_gns3_vm.py:179 GNS3 VM IP address set to 192.168.6.129
2018-01-11 10:28:05 CRITICAL run.py:256 Critical error while running the server: Conflict
Traceback (most recent call last):
  File "./gns3-server/gns3server/run.py", line 250, in run
  File "./gns3-server/gns3server/web/web_server.py", line 278, in run
  File "./gns3-server/gns3server/web/web_server.py", line 80, in _run_application
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/base_events.py", line 467, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.6/site-packages/aiohttp/web.py", line 264, in startup
  File "/usr/local/lib/python3.6/site-packages/aiohttp/signals.py", line 51, in send
  File "/usr/local/lib/python3.6/site-packages/aiohttp/signals.py", line 17, in _send
  File "./gns3-server/gns3server/web/web_server.py", line 202, in _on_startup
  File "./gns3-server/gns3server/controller/__init__.py", line 180, in start
  File "./gns3-server/gns3server/controller/gns3vm/__init__.py", line 244, in auto_start_vm
  File "./gns3-server/gns3server/utils/asyncio/__init__.py", line 158, in new_function
  File "./gns3-server/gns3server/controller/gns3vm/__init__.py", line 300, in start
  File "./gns3-server/gns3server/controller/gns3vm/__init__.py", line 308, in _check_network
  File "./gns3-server/gns3server/controller/compute.py", line 146, in interfaces
  File "./gns3-server/gns3server/controller/compute.py", line 587, in get
  File "./gns3-server/gns3server/controller/compute.py", line 384, in http_query
  File "./gns3-server/gns3server/utils/asyncio/__init__.py", line 158, in new_function
  File "./gns3-server/gns3server/controller/compute.py", line 435, in connect
aiohttp.web_exceptions.HTTPConflict: Conflict
2018-01-11 10:28:06 INFO crash_report.py:114 Crash report sent with event ID: 7aa7ab05bc2744b189712a68c4a63133

-------- 8< --------------------------- >8 ----

**Comment by grossmj** [comment]
This confirms the issue I was suspecting and we recently fixed it: https://github.com/GNS3/gns3-gui/issues/2385.

The local server crashes even if you don't use the GNS3 VM in your project. Starting the VM manually first will prevent the local server to crash. Alternatively, you can remove the GNS3 VM use from the preferences.

The fix will be included when we release version 2.1.3

**Comment by MrMic** [comment]
No!
I started the VM manually and then started GNS3, and "the local server still stopped" !

**Comment by grossmj** [comment]
Can you try the nightly build? https://sourceforge.net/projects/gns-3/files/Nightly%20Builds/2018-01-12/2.1/GNS3-2.1.3dev1.dmg/download

**Comment by MrMic** [comment]
Hi,

Seems to work now !
I will investigate further in then  next coming days.
Thank you for all.
 Rgds,

**Comment by grossmj** [comment]
Perfect, please re-open this issue or create a new one if encounter a different problem. Thanks!
