### ISSUE TITLE
Project deletion fails on GNS3VM

### ISSUE THREAD

**Issue by ehlers** [GNS3/gns3-server#1261]
GNS3 2.1.3dev 1 commit 97cfb89

Deleting a project (File -> Delete project) fails on the GNS3VM since commit 97cfb89, before it works fine. I assume it fails, because no vboxmanage is installed in the GNS3VM. During this test, the project contained only one dynamips router in the GNS3VM.

Log in GNS3VM:
```
2018-01-11 16:20:22 INFO base_node.py:312 Dynamips: 'R1' [8d6ccb6d-a301-41cb-99fc-9a638e8e9ca3]: is closing
2018-01-11 16:20:22 INFO hypervisor.py:150 Stopping Dynamips process PID=1374
2018-01-11 16:20:22 INFO project.py:342 Project 0eed99b8-48f6-4b31-ab57-9ce4367d0ce6 with path '/opt/gns3/projects/0eed99b8-48f6-4b31-ab57-9ce4367d0ce6' deleted
2018-01-11 16:20:22 INFO __init__.py:64 A path to VBoxManage has not been configured, trying to find it...
2018-01-11 16:20:22 ERROR route.py:229 Uncaught exception detected: <class 'TypeError'>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/gns3_server-2.1.3dev1_97cfb892-py3.5.egg/gns3server/web/route.py", line 195, in control_schema
    yield from func(request, response)
  File "/usr/local/lib/python3.5/dist-packages/gns3_server-2.1.3dev1_97cfb892-py3.5.egg/gns3server/handlers/api/compute/project_handler.py", line 137, in delete
    yield from project.delete()
  File "/usr/local/lib/python3.5/dist-packages/gns3_server-2.1.3dev1_97cfb892-py3.5.egg/gns3server/compute/project.py", line 370, in delete
    yield from module.instance().project_closed(self)
  File "/usr/local/lib/python3.5/dist-packages/gns3_server-2.1.3dev1_97cfb892-py3.5.egg/gns3server/compute/virtualbox/__init__.py", line 164, in project_closed
    hdd_files_to_close = yield from self._find_inaccessible_hdd_files()
  File "/usr/local/lib/python3.5/dist-packages/gns3_server-2.1.3dev1_97cfb892-py3.5.egg/gns3server/compute/virtualbox/__init__.py", line 137, in _find_inaccessible_hdd_files
    properties = yield from self.execute("list", ["hdds"])
  File "/usr/local/lib/python3.5/dist-packages/gns3_server-2.1.3dev1_97cfb892-py3.5.egg/gns3server/compute/virtualbox/__init__.py", line 105, in execute
    vboxmanage_path = self.find_vboxmanage()
  File "/usr/local/lib/python3.5/dist-packages/gns3_server-2.1.3dev1_97cfb892-py3.5.egg/gns3server/compute/virtualbox/__init__.py", line 81, in find_vboxmanage
    if not os.path.exists(vboxmanage_path):
  File "/usr/lib/python3.5/genericpath.py", line 19, in exists
    os.stat(path)
TypeError: stat: can't specify None for path argument
2018-01-11 16:20:22 INFO helpers.py:508 192.168.1.10 - - [11/Jan/2018:15:20:22 +0000] "DELETE /v2/compute/projects/0eed99b8-48f6-4b31-ab57-9ce4367d0ce6 HTTP/1.1" 500 1910 "-" "Python/3.6 aiohttp/2.2.5"
2018-01-11 16:20:27 ERROR route.py:210 Node error detected: DynamipsError
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/gns3_server-2.1.3dev1_97cfb892-py3.5.egg/gns3server/web/route.py", line 195, in control_schema
    yield from func(request, response)
  File "/usr/local/lib/python3.5/dist-packages/gns3_server-2.1.3dev1_97cfb892-py3.5.egg/gns3server/handlers/api/compute/dynamips_vm_handler.py", line 185, in stop
    yield from vm.stop()
  File "/usr/local/lib/python3.5/dist-packages/gns3_server-2.1.3dev1_97cfb892-py3.5.egg/gns3server/compute/dynamips/nodes/router.py", line 323, in stop
    status = yield from self.get_status()
  File "/usr/local/lib/python3.5/dist-packages/gns3_server-2.1.3dev1_97cfb892-py3.5.egg/gns3server/compute/dynamips/nodes/router.py", line 248, in get_status
    status = yield from self._hypervisor.send('vm get_status "{name}"'.format(name=self._name))
  File "/usr/local/lib/python3.5/dist-packages/gns3_server-2.1.3dev1_97cfb892-py3.5.egg/gns3server/compute/dynamips/dynamips_hypervisor.py", line 249, in send
    raise DynamipsError("Not connected")
gns3server.compute.dynamips.dynamips_error.DynamipsError: Not connected
2018-01-11 16:20:27 INFO helpers.py:508 192.168.1.10 - - [11/Jan/2018:15:20:27 +0000] "POST /v2/compute/projects/0eed99b8-48f6-4b31-ab57-9ce4367d0ce6/dynamips/nodes/8d6ccb6d-a301-41cb-99fc-9a638e8e9ca3/stop HTTP/1.1" 409 329 "-" "Python/3.6 aiohttp/2.2.5"
2018-01-11 16:20:27 INFO project.py:346 Project 0eed99b8-48f6-4b31-ab57-9ce4367d0ce6 with path '/opt/gns3/projects/0eed99b8-48f6-4b31-ab57-9ce4367d0ce6' closed
2018-01-11 16:20:27 INFO helpers.py:508 192.168.1.10 - - [11/Jan/2018:15:20:27 +0000] "POST /v2/compute/projects/0eed99b8-48f6-4b31-ab57-9ce4367d0ce6/close HTTP/1.1" 204 227 "-" "Python/3.6 aiohttp/2.2.5"
```

**Comment by grossmj** [comment]
Thanks for catching this. I will fix this asap.
