### ISSUE TITLE
AppVeyor crashes with pypiwin32-222

### ISSUE THREAD

**Issue by ziajka** [GNS3/gns3-server#1276]
```
Successfully installed pypiwin32-222 pywin32-222
%PYTHON%\python.exe -m pytest -v
Traceback (most recent call last):
  File "C:\Python36-x64\lib\site-packages\_pytest\config.py", line 342, in _getconftestmodules
    return self._path2confmods[path]
KeyError: local('C:\\projects\\gns3-server\\tests')
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Python36-x64\lib\site-packages\_pytest\config.py", line 373, in _importconftest
    return self._conftestpath2mod[conftestpath]
KeyError: local('C:\\projects\\gns3-server\\tests\\conftest.py')
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Python36-x64\lib\site-packages\_pytest\config.py", line 379, in _importconftest
    mod = conftestpath.pyimport()
  File "C:\Python36-x64\lib\site-packages\py\_path\local.py", line 668, in pyimport
    __import__(modname)
  File "C:\Python36-x64\lib\site-packages\_pytest\assertion\rewrite.py", line 212, in load_module
    py.builtin.exec_(co, mod.__dict__)
  File "C:\projects\gns3-server\tests\conftest.py", line 37, in <module>
    from gns3server.web.route import Route
  File "C:\projects\gns3-server\gns3server\web\route.py", line 30, in <module>
    from ..compute.error import NodeError, ImageMissingError
  File "C:\projects\gns3-server\gns3server\compute\__init__.py", line 23, in <module>
    from .virtualbox import VirtualBox
  File "C:\projects\gns3-server\gns3server\compute\virtualbox\__init__.py", line 32, in <module>
    from .virtualbox_vm import VirtualBoxVM
  File "C:\projects\gns3-server\gns3server\compute\virtualbox\virtualbox_vm.py", line 35, in <module>
    from gns3server.utils.asyncio.serial import asyncio_open_serial
  File "C:\projects\gns3-server\gns3server\utils\asyncio\serial.py", line 28, in <module>
    import win32file
ImportError: DLL load failed: The specified module could not be found.
ERROR: could not load C:\projects\gns3-server\tests\conftest.py
[WinError 2] The system cannot find the file specified

```

There is no issue with pywin32-220: https://ci.appveyor.com/project/gns3-build/gns3-server/build/655-2.2

**Comment by ziajka** [comment]
Ref. https://github.com/mhammond/pywin32/issues/1151

**Comment by ziajka** [comment]
We lock this dependency and wait till solved by maintainer of pywin32. Note: pypiwin32 is obsolete and should be switched to pywin32 when fixed.

**Comment by ziajka** [comment]
Locked down dependencies, wait for new version of pypiwin32
