### ISSUE TITLE
OS X: unable to create UDP NIO

### ISSUE THREAD

**Issue by ehlers** [GNS3/gns3-server#133]
GNS3 version 1.3.0 on Darwin (64-bit) 10.9.5.

On Mac OS X the following sequence reproducible creates the "unable to create UDP NIO" error. I tried the exact same sequence on linux, no problems.

start GNS3
place first ethernet switch
place second ethernet switch
create link port 1 first switch to port 1 second switch
delete second switch
place ethernet hub
create link port 1 hub to port 1 first switch
--> error is shown

This happens no matter what dynamips devices I use (internal or IOS). It doesn't happen, when I try this with 2 qemu devices. And this doesn't happen on linux. Maybe it depends from dynamips version. On OS X it's version 0.2.12-amd64/Darwin unstable, on my linux it's version 0.2.14-amd64/Linux stable.

**Comment by ehlers** [comment]
And here are the logs, GitHub really should add a way to attach files.

```
Apr  2 09:07:51 imac.lan GNS3[3156] <Notice>: GNS3 GUI version 1.3.0
Apr  2 09:07:51 imac.lan GNS3[3156] <Notice>: Copyright (c) 2007-2015 GNS3 Technologies Inc.
Apr  2 09:07:51 imac.lan GNS3[3156] <Notice>: 2015-04-02 09:07:51 INFO main.py:218 Log level: INFO
Apr  2 09:07:51 imac.lan GNS3[3156] <Notice>: 2015-04-02 09:07:51 INFO servers.pyo:311 New remote server connection http://192.168.1.90:8000 registered
Apr  2 09:07:51 imac.lan GNS3[3156] <Notice>: 2015-04-02 09:07:51 INFO servers.pyo:69 New local server connection http://192.168.1.10:8000 registered
Apr  2 09:07:51 imac.lan GNS3[3156] <Notice>: QPixmap::scaled: Pixmap is a null pixmap
Apr  2 09:07:52 imac.lan GNS3[3156] <Notice>: 2015-04-02 09:07:52 INFO servers.pyo:225 Starting local server process with "/Applications/Lokal/GNS3.app/Contents/Resources/server/Contents/MacOS/gns3server" --host 192.168.1.10 --port 8000 --local
Apr  2 09:07:52 imac.lan GNS3[3156] <Notice>: 2015-04-02 09:07:52 INFO servers.pyo:238 Local server process has started (PID=3159)
Apr  2 09:07:52 imac.lan GNS3[3156] <Notice>: QPixmap::scaled: Pixmap is a null pixmap
Apr  2 09:07:52 imac.lan GNS3[3156] <Notice>: 2015-04-02 09:07:52 INFO main.py:145 GNS3 server version 1.3.0
Apr  2 09:07:52 imac.lan GNS3[3156] <Notice>: 2015-04-02 09:07:52 INFO main.py:147 Copyright (c) 2007-2015 GNS3 Technologies Inc.
Apr  2 09:07:52 imac.lan GNS3[3156] <Notice>: 2015-04-02 09:07:52 INFO main.py:150 Config file /Users/behlers/.config/gns3.net/gns3_server.conf loaded
Apr  2 09:07:52 imac.lan GNS3[3156] <Notice>: 2015-04-02 09:07:52 WARNING main.py:155 Local mode is enabled. Beware, clients will have full control on your filesystem
Apr  2 09:07:52 imac.lan GNS3[3156] <Notice>: 2015-04-02 09:07:52 INFO main.py:163 Running with Python 3.4.3 and has PID 3159
Apr  2 09:07:52 imac.lan GNS3[3156] <Notice>: 2015-04-02 09:07:52 INFO server.pyc:214 Starting server on 192.168.1.10:8000
Apr  2 09:07:52 imac.lan GNS3[3156] <Notice>: 2015-04-02 09:07:52.507 GNS3[3156:507] modalSession has been exited prematurely - check for a reentrant call to endModalSession:
Apr  2 09:07:52 imac.lan GNS3[3156] <Notice>: 2015-04-02 09:07:52 INFO __init__.pyo:206 VPCS module reset
Apr  2 09:07:52 imac.lan GNS3[3156] <Notice>: 2015-04-02 09:07:52 INFO __init__.pyo:421 Dynamips module reset
Apr  2 09:07:52 imac.lan GNS3[3156] <Notice>: 2015-04-02 09:07:52 INFO __init__.pyo:301 IOU module reset
Apr  2 09:07:52 imac.lan GNS3[3156] <Notice>: 2015-04-02 09:07:52 INFO __init__.pyo:306 VirtualBox module reset
Apr  2 09:07:52 imac.lan GNS3[3156] <Notice>: 2015-04-02 09:07:52 INFO __init__.pyo:291 QEMU module reset
Apr  2 09:07:52 imac.lan GNS3[3156] <Notice>: 2015-04-02 09:07:52 INFO __init__.pyo:69 Built-in module reset
Apr  2 09:07:52 imac.lan GNS3[3156] <Notice>: 2015-04-02 09:07:52 INFO topology.pyo:371 Topology reset
Apr  2 09:07:59 imac.lan GNS3[3156] <Notice>: QPixmap::scaled: Pixmap is a null pixmap
Apr  2 09:08:05 imac.lan GNS3[3156] <Notice>: 2015-04-02 09:08:05 INFO __init__.pyo:330 creating node <class 'gns3.modules.dynamips.nodes.ethernet_switch.EthernetSwitch'>
Apr  2 09:08:05 imac.lan GNS3[3156] <Notice>: 2015-04-02 09:08:05 INFO __init__.pyo:343 configuring node Ethernet switch
Apr  2 09:08:05 imac.lan GNS3[3156] <Notice>: 2015-04-02 09:08:05 INFO http_client.pyo:242 Connection to 192.168.1.10:8000
Apr  2 09:08:06 imac.lan GNS3[3156] <Notice>: 2015-04-02 09:08:06 INFO server.pyc:169 127.0.0.1 - - Thu, 02 Apr 2015 07:08:06 GMT "GET /v1/version HTTP/1.1" 200 230 "-" "GNS3 QT Client v1.3.0"
Apr  2 09:08:06 imac.lan GNS3[3156] <Notice>: 2015-04-02 09:08:06 INFO project.pyc:76 Project 77dbc099-2ed8-4d5a-9c3e-e91f71bce740 with path '/Users/behlers/GNS3/projects/77dbc099-2ed8-4d5a-9c3e-e91f71bce740' created
Apr  2 09:08:06 imac.lan GNS3[3156] <Notice>: 2015-04-02 09:08:06 INFO server.pyc:169 127.0.0.1 - - Thu, 02 Apr 2015 07:08:06 GMT "POST /v1/projects HTTP/1.1" 201 427 "-" "GNS3 QT Client v1.3.0"
Apr  2 09:08:06 imac.lan GNS3[3156] <Notice>: 2015-04-02 09:08:06 INFO project.pyo:266 Server project path is /Users/behlers/GNS3/projects/77dbc099-2ed8-4d5a-9c3e-e91f71bce740
Apr  2 09:08:06 imac.lan GNS3[3156] <Notice>: 2015-04-02 09:08:06 INFO __init__.pyc:341 Creating new hypervisor 192.168.1.10:50161 with working directory /Users/behlers/GNS3/projects/77dbc099-2ed8-4d5a-9c3e-e91f71bce740/project-files/dynamips
Apr  2 09:08:06 imac.lan GNS3[3156] <Notice>: 2015-04-02 09:08:06 INFO hypervisor.pyc:111 Starting Dynamips: ['/Applications/Lokal/GNS3.app/Contents/Resources/dynamips', '-N1', '-l', 'dynamips_i1_log.txt', '-H', '192.168.1.10:50161']
Apr  2 09:08:06 imac.lan GNS3[3156] <Notice>: 2015-04-02 09:08:06 INFO hypervisor.pyc:115 Dynamips process logging to /var/folders/w5/khqk_lyn3_xd7qqz84cfxcnm0000gn/T/tmp62nwkp04
Apr  2 09:08:06 imac.lan GNS3[3156] <Notice>: 2015-04-02 09:08:06 INFO hypervisor.pyc:120 Dynamips process started PID=3160
Apr  2 09:08:06 imac.lan GNS3[3156] <Notice>: 2015-04-02 09:08:06 INFO __init__.pyc:343 Hypervisor 192.168.1.10:50161 has successfully started
Apr  2 09:08:06 imac.lan GNS3[3156] <Notice>: 2015-04-02 09:08:06 INFO dynamips_hypervisor.pyc:94 Connected to Dynamips hypervisor after 0.4968 seconds
Apr  2 09:08:06 imac.lan GNS3[3156] <Notice>: 2015-04-02 09:08:06 INFO ethernet_switch.pyc:75 Ethernet switch "SW1" [719ce93e-0931-49c8-9b8e-91104aea6e03] has been created
Apr  2 09:08:06 imac.lan GNS3[3156] <Notice>: 2015-04-02 09:08:06 INFO server.pyc:169 127.0.0.1 - - Thu, 02 Apr 2015 07:08:06 GMT "POST /v1/projects/77dbc099-2ed8-4d5a-9c3e-e91f71bce740/dynamips/devices HTTP/1.1" 201 375 "-" "GNS3 QT Client v1.3.0"
Apr  2 09:08:06 imac.lan GNS3[3156] <Notice>: 2015-04-02 09:08:06 INFO device.pyo:62 SW1 has been created
Apr  2 09:08:09 imac.lan GNS3[3156] <Notice>: 2015-04-02 09:08:09 INFO __init__.pyo:330 creating node <class 'gns3.modules.dynamips.nodes.ethernet_switch.EthernetSwitch'>
Apr  2 09:08:09 imac.lan GNS3[3156] <Notice>: 2015-04-02 09:08:09 INFO __init__.pyo:343 configuring node Ethernet switch
Apr  2 09:08:09 imac.lan GNS3[3156] <Notice>: 2015-04-02 09:08:09 INFO __init__.pyc:341 Creating new hypervisor 192.168.1.10:50205 with working directory /Users/behlers/GNS3/projects/77dbc099-2ed8-4d5a-9c3e-e91f71bce740/project-files/dynamips
Apr  2 09:08:09 imac.lan GNS3[3156] <Notice>: 2015-04-02 09:08:09 INFO hypervisor.pyc:111 Starting Dynamips: ['/Applications/Lokal/GNS3.app/Contents/Resources/dynamips', '-N1', '-l', 'dynamips_i2_log.txt', '-H', '192.168.1.10:50205']
Apr  2 09:08:09 imac.lan GNS3[3156] <Notice>: 2015-04-02 09:08:09 INFO hypervisor.pyc:115 Dynamips process logging to /var/folders/w5/khqk_lyn3_xd7qqz84cfxcnm0000gn/T/tmp_93u3xer
Apr  2 09:08:09 imac.lan GNS3[3156] <Notice>: 2015-04-02 09:08:09 INFO hypervisor.pyc:120 Dynamips process started PID=3165
Apr  2 09:08:09 imac.lan GNS3[3156] <Notice>: 2015-04-02 09:08:09 INFO __init__.pyc:343 Hypervisor 192.168.1.10:50205 has successfully started
Apr  2 09:08:09 imac.lan GNS3[3156] <Notice>: 2015-04-02 09:08:09 INFO dynamips_hypervisor.pyc:94 Connected to Dynamips hypervisor after 0.0119 seconds
Apr  2 09:08:09 imac.lan GNS3[3156] <Notice>: 2015-04-02 09:08:09 INFO ethernet_switch.pyc:75 Ethernet switch "SW2" [a5745c23-4d18-4ac4-a680-063438b95b8a] has been created
Apr  2 09:08:09 imac.lan GNS3[3156] <Notice>: 2015-04-02 09:08:09 INFO server.pyc:169 127.0.0.1 - - Thu, 02 Apr 2015 07:08:09 GMT "POST /v1/projects/77dbc099-2ed8-4d5a-9c3e-e91f71bce740/dynamips/devices HTTP/1.1" 201 375 "-" "GNS3 QT Client v1.3.0"
Apr  2 09:08:09 imac.lan GNS3[3156] <Notice>: 2015-04-02 09:08:09 INFO device.pyo:62 SW2 has been created
Apr  2 09:08:17 imac.lan GNS3[3156] <Notice>: 2015-04-02 09:08:17 INFO link.pyo:56 adding link from SW2 1 to SW1 1
Apr  2 09:08:17 imac.lan GNS3[3156] <Notice>: 2015-04-02 09:08:17 INFO server.pyc:169 127.0.0.1 - - Thu, 02 Apr 2015 07:08:17 GMT "POST /v1/projects/77dbc099-2ed8-4d5a-9c3e-e91f71bce740/ports/udp HTTP/1.1" 201 239 "-" "GNS3 QT Client v1.3.0"
Apr  2 09:08:17 imac.lan GNS3[3156] <Notice>: 2015-04-02 09:08:17 INFO server.pyc:169 127.0.0.1 - - Thu, 02 Apr 2015 07:08:17 GMT "POST /v1/projects/77dbc099-2ed8-4d5a-9c3e-e91f71bce740/ports/udp HTTP/1.1" 201 239 "-" "GNS3 QT Client v1.3.0"
Apr  2 09:08:17 imac.lan GNS3[3156] <Notice>: 2015-04-02 09:08:17 INFO nio_udp.pyc:72 NIO UDP nio_udp0 created with lport=10000, rhost=192.168.1.10, rport=10001
Apr  2 09:08:17 imac.lan GNS3[3156] <Notice>: 2015-04-02 09:08:17 INFO nio_udp.pyc:72 NIO UDP nio_udp1 created with lport=10001, rhost=192.168.1.10, rport=10000
Apr  2 09:08:17 imac.lan GNS3[3156] <Notice>: 2015-04-02 09:08:17 INFO ethernet_switch.pyc:149 Ethernet switch "SW2" [a5745c23-4d18-4ac4-a680-063438b95b8a]: NIO nio_udp0 bound to port 1
Apr  2 09:08:17 imac.lan GNS3[3156] <Notice>: 2015-04-02 09:08:17 INFO ethernet_switch.pyc:149 Ethernet switch "SW1" [719ce93e-0931-49c8-9b8e-91104aea6e03]: NIO nio_udp1 bound to port 1
Apr  2 09:08:17 imac.lan GNS3[3156] <Notice>: 2015-04-02 09:08:17 INFO ethernet_switch.pyc:217 Ethernet switch "SW2" [a5745c23-4d18-4ac4-a680-063438b95b8a]: port 1 set as an access port in VLAN 1
Apr  2 09:08:17 imac.lan GNS3[3156] <Notice>: 2015-04-02 09:08:17 INFO server.pyc:169 127.0.0.1 - - Thu, 02 Apr 2015 07:08:17 GMT "POST /v1/projects/77dbc099-2ed8-4d5a-9c3e-e91f71bce740/dynamips/devices/a5745c23-4d18-4ac4-a680-063438b95b8a/ports/1/nio HTTP/1.1" 201 355 "-" "GNS3 QT Client v1.3.0"
Apr  2 09:08:17 imac.lan GNS3[3156] <Notice>: 2015-04-02 09:08:17 INFO ethernet_switch.pyc:217 Ethernet switch "SW1" [719ce93e-0931-49c8-9b8e-91104aea6e03]: port 1 set as an access port in VLAN 1
Apr  2 09:08:17 imac.lan GNS3[3156] <Notice>: 2015-04-02 09:08:17 INFO server.pyc:169 127.0.0.1 - - Thu, 02 Apr 2015 07:08:17 GMT "POST /v1/projects/77dbc099-2ed8-4d5a-9c3e-e91f71bce740/dynamips/devices/719ce93e-0931-49c8-9b8e-91104aea6e03/ports/1/nio HTTP/1.1" 201 355 "-" "GNS3 QT Client v1.3.0"
Apr  2 09:08:17 imac.lan GNS3[3156] <Notice>: QPixmap::scaled: Pixmap is a null pixmap
Apr  2 09:08:24 imac.lan GNS3[3156] <Notice>: QPixmap::scaled: Pixmap is a null pixmap
Apr  2 09:08:26 imac.lan GNS3[3156] <Notice>: QPixmap::scaled: Pixmap is a null pixmap
Apr  2 09:08:28 imac.lan GNS3[3156] <Notice>: 2015-04-02 09:08:28.194 GNS3[3156:507] modalSession has been exited prematurely - check for a reentrant call to endModalSession:
Apr  2 09:08:28 imac.lan GNS3[3156] <Notice>: 2015-04-02 09:08:28 INFO link.pyo:137 deleting link from SW2 1 to SW1 1
Apr  2 09:08:28 imac.lan GNS3[3156] <Notice>: 2015-04-02 09:08:28 INFO ethernet_switch.pyc:173 Ethernet switch "SW1" [719ce93e-0931-49c8-9b8e-91104aea6e03]: NIO nio_udp1 removed from port 1
Apr  2 09:08:28 imac.lan GNS3[3156] <Notice>: 2015-04-02 09:08:28 INFO server.pyc:169 127.0.0.1 - - Thu, 02 Apr 2015 07:08:28 GMT "DELETE /v1/projects/77dbc099-2ed8-4d5a-9c3e-e91f71bce740/dynamips/devices/719ce93e-0931-49c8-9b8e-91104aea6e03/ports/1/nio HTTP/1.1" 204 231 "-" "GNS3 QT Client v1.3.0"
Apr  2 09:08:28 imac.lan GNS3[3156] <Notice>: 2015-04-02 09:08:28 INFO ethernet_switch.pyc:173 Ethernet switch "SW2" [a5745c23-4d18-4ac4-a680-063438b95b8a]: NIO nio_udp0 removed from port 1
Apr  2 09:08:28 imac.lan GNS3[3156] <Notice>: 2015-04-02 09:08:28 INFO server.pyc:169 127.0.0.1 - - Thu, 02 Apr 2015 07:08:28 GMT "DELETE /v1/projects/77dbc099-2ed8-4d5a-9c3e-e91f71bce740/dynamips/devices/a5745c23-4d18-4ac4-a680-063438b95b8a/ports/1/nio HTTP/1.1" 204 231 "-" "GNS3 QT Client v1.3.0"
Apr  2 09:08:28 imac.lan GNS3[3156] <Notice>: 2015-04-02 09:08:28 INFO ethernet_switch.pyc:124 Ethernet switch "SW2" [a5745c23-4d18-4ac4-a680-063438b95b8a] has been deleted
Apr  2 09:08:28 imac.lan GNS3[3156] <Notice>: 2015-04-02 09:08:28 INFO hypervisor.pyc:133 Stopping Dynamips process PID=3165
Apr  2 09:08:28 imac.lan GNS3[3156] <Notice>: 2015-04-02 09:08:28 INFO server.pyc:169 127.0.0.1 - - Thu, 02 Apr 2015 07:08:28 GMT "DELETE /v1/projects/77dbc099-2ed8-4d5a-9c3e-e91f71bce740/dynamips/devices/a5745c23-4d18-4ac4-a680-063438b95b8a HTTP/1.1" 204 203 "-" "GNS3 QT Client v1.3.0"
Apr  2 09:08:28 imac.lan GNS3[3156] <Notice>: 2015-04-02 09:08:28 INFO device.pyo:93 SW2 has been deleted
Apr  2 09:08:33 imac.lan GNS3[3156] <Notice>: QPixmap::scaled: Pixmap is a null pixmap
Apr  2 09:08:36 imac.lan GNS3[3156] <Notice>: 2015-04-02 09:08:36 INFO __init__.pyo:330 creating node <class 'gns3.modules.dynamips.nodes.ethernet_hub.EthernetHub'>
Apr  2 09:08:36 imac.lan GNS3[3156] <Notice>: 2015-04-02 09:08:36 INFO __init__.pyo:343 configuring node Ethernet hub
Apr  2 09:08:36 imac.lan GNS3[3156] <Notice>: 2015-04-02 09:08:36 INFO __init__.pyc:341 Creating new hypervisor 192.168.1.10:50209 with working directory /Users/behlers/GNS3/projects/77dbc099-2ed8-4d5a-9c3e-e91f71bce740/project-files/dynamips
Apr  2 09:08:36 imac.lan GNS3[3156] <Notice>: 2015-04-02 09:08:36 INFO hypervisor.pyc:111 Starting Dynamips: ['/Applications/Lokal/GNS3.app/Contents/Resources/dynamips', '-N1', '-l', 'dynamips_i3_log.txt', '-H', '192.168.1.10:50209']
Apr  2 09:08:36 imac.lan GNS3[3156] <Notice>: 2015-04-02 09:08:36 INFO hypervisor.pyc:115 Dynamips process logging to /var/folders/w5/khqk_lyn3_xd7qqz84cfxcnm0000gn/T/tmp16s6o0cv
Apr  2 09:08:36 imac.lan GNS3[3156] <Notice>: 2015-04-02 09:08:36 INFO hypervisor.pyc:120 Dynamips process started PID=3166
Apr  2 09:08:36 imac.lan GNS3[3156] <Notice>: 2015-04-02 09:08:36 INFO __init__.pyc:343 Hypervisor 192.168.1.10:50209 has successfully started
Apr  2 09:08:36 imac.lan GNS3[3156] <Notice>: 2015-04-02 09:08:36 INFO dynamips_hypervisor.pyc:94 Connected to Dynamips hypervisor after 0.0124 seconds
Apr  2 09:08:36 imac.lan GNS3[3156] <Notice>: 2015-04-02 09:08:36 INFO ethernet_hub.pyc:59 Ethernet hub "HUB1" [6cda13b3-516c-4a06-950a-734239400b3e] has been created
Apr  2 09:08:36 imac.lan GNS3[3156] <Notice>: 2015-04-02 09:08:36 INFO server.pyc:169 127.0.0.1 - - Thu, 02 Apr 2015 07:08:36 GMT "POST /v1/projects/77dbc099-2ed8-4d5a-9c3e-e91f71bce740/dynamips/devices HTTP/1.1" 201 359 "-" "GNS3 QT Client v1.3.0"
Apr  2 09:08:36 imac.lan GNS3[3156] <Notice>: 2015-04-02 09:08:36 INFO device.pyo:62 HUB1 has been created
Apr  2 09:08:39 imac.lan GNS3[3156] <Notice>: QPixmap::scaled: Pixmap is a null pixmap
Apr  2 09:08:45 imac.lan GNS3[3156] <Notice>: 2015-04-02 09:08:45 INFO link.pyo:56 adding link from HUB1 1 to SW1 1
Apr  2 09:08:45 imac.lan GNS3[3156] <Notice>: 2015-04-02 09:08:45 INFO server.pyc:169 127.0.0.1 - - Thu, 02 Apr 2015 07:08:45 GMT "POST /v1/projects/77dbc099-2ed8-4d5a-9c3e-e91f71bce740/ports/udp HTTP/1.1" 201 239 "-" "GNS3 QT Client v1.3.0"
Apr  2 09:08:45 imac.lan GNS3[3156] <Notice>: 2015-04-02 09:08:45 INFO server.pyc:169 127.0.0.1 - - Thu, 02 Apr 2015 07:08:45 GMT "POST /v1/projects/77dbc099-2ed8-4d5a-9c3e-e91f71bce740/ports/udp HTTP/1.1" 201 239 "-" "GNS3 QT Client v1.3.0"
Apr  2 09:08:45 imac.lan GNS3[3156] <Notice>: 2015-04-02 09:08:45 ERROR route.pyc:145 VM error detected: <class 'gns3server.modules.dynamips.dynamips_error.DynamipsError'>
Apr  2 09:08:45 imac.lan GNS3[3156] <Notice>: Traceback (most recent call last):
Apr  2 09:08:45 imac.lan GNS3[3156] <Notice>:   File "gns3server/web/route.pyc", line 139, in control_schema
Apr  2 09:08:45 imac.lan GNS3[3156] <Notice>:   File "gns3server/handlers/api/dynamips_device_handler.pyc", line 147, in create_nio
Apr  2 09:08:45 imac.lan GNS3[3156] <Notice>:   File "gns3server/modules/dynamips/__init__.pyc", line 414, in create_nio
Apr  2 09:08:45 imac.lan GNS3[3156] <Notice>:   File "gns3server/modules/dynamips/nios/nio_udp.pyc", line 67, in create
Apr  2 09:08:45 imac.lan GNS3[3156] <Notice>:   File "gns3server/modules/dynamips/dynamips_hypervisor.pyc", line 307, in send
Apr  2 09:08:45 imac.lan GNS3[3156] <Notice>: gns3server.modules.dynamips.dynamips_error.DynamipsError: unable to create UDP NIO
Apr  2 09:08:45 imac.lan GNS3[3156] <Notice>: 2015-04-02 09:08:45 INFO server.pyc:169 127.0.0.1 - - Thu, 02 Apr 2015 07:08:45 GMT "POST /v1/projects/77dbc099-2ed8-4d5a-9c3e-e91f71bce740/dynamips/devices/719ce93e-0931-49c8-9b8e-91104aea6e03/ports/1/nio HTTP/1.1" 409 326 "-" "GNS3 QT Client v1.3.0"
Apr  2 09:08:45 imac.lan GNS3[3156] <Notice>: 2015-04-02 09:08:45 INFO nio_udp.pyc:72 NIO UDP nio_udp3 created with lport=10000, rhost=192.168.1.10, rport=10001
Apr  2 09:08:45 imac.lan GNS3[3156] <Notice>: 2015-04-02 09:08:45 INFO http_client.pyo:335 Response error: Error downloading http://192.168.1.10:8000/v1/projects/77dbc099-2ed8-4d5a-9c3e-e91f71bce740/dynamips/devices/719ce93e-0931-49c8-9b8e-91104aea6e03/ports/1/nio - server replied: Conflict
Apr  2 09:08:45 imac.lan GNS3[3156] <Notice>: 2015-04-02 09:08:45 ERROR device.pyo:106 error while adding an UDP NIO for SW1: unable to create UDP NIO
Apr  2 09:08:45 imac.lan GNS3[3156] <Notice>: 2015-04-02 09:08:45 INFO ethernet_hub.pyc:106 Ethernet hub "HUB1" [6cda13b3-516c-4a06-950a-734239400b3e]: NIO nio_udp3 bound to port 1
Apr  2 09:08:45 imac.lan GNS3[3156] <Notice>: 2015-04-02 09:08:45 INFO server.pyc:169 127.0.0.1 - - Thu, 02 Apr 2015 07:08:45 GMT "POST /v1/projects/77dbc099-2ed8-4d5a-9c3e-e91f71bce740/dynamips/devices/6cda13b3-516c-4a06-950a-734239400b3e/ports/1/nio HTTP/1.1" 201 355 "-" "GNS3 QT Client v1.3.0"
Apr  2 09:08:45 imac.lan GNS3[3156] <Notice>: 2015-04-02 09:08:45 INFO ethernet_hub.pyc:130 Ethernet switch "HUB1" [6cda13b3-516c-4a06-950a-734239400b3e]: NIO nio_udp3 removed from port 1
Apr  2 09:08:45 imac.lan GNS3[3156] <Notice>: 2015-04-02 09:08:45 INFO server.pyc:169 127.0.0.1 - - Thu, 02 Apr 2015 07:08:45 GMT "DELETE /v1/projects/77dbc099-2ed8-4d5a-9c3e-e91f71bce740/dynamips/devices/6cda13b3-516c-4a06-950a-734239400b3e/ports/1/nio HTTP/1.1" 204 231 "-" "GNS3 QT Client v1.3.0"
Apr  2 09:08:46 imac.lan GNS3[3156] <Notice>: QPixmap::scaled: Pixmap is a null pixmap
```

**Comment by noplay** [comment]
Thanks for the scenario. I confirm I can reproduce it:

```
2015-04-02 10:12:32 ERROR route.py:145 VM error detected: <class 'gns3server.modules.dynamips.dynamips_error.DynamipsError'>
Traceback (most recent call last):
  File "/Users/noplay/code/gns3/gns3-server/gns3server/web/route.py", line 139, in control_schema
    yield from func(request, response)
  File "/Users/noplay/code/gns3/gns3-server/gns3server/handlers/api/dynamips_device_handler.py", line 147, in create_nio
    nio = yield from dynamips_manager.create_nio(device, request.json["nio"])
  File "/Users/noplay/code/gns3/gns3-server/gns3server/modules/dynamips/__init__.py", line 414, in create_nio
    yield from nio.create()
  File "/Users/noplay/code/gns3/gns3-server/gns3server/modules/dynamips/nios/nio_udp.py", line 67, in create
    rport=self._rport))
  File "/Users/noplay/code/gns3/gns3-server/gns3server/modules/dynamips/dynamips_hypervisor.py", line 307, in send
    raise DynamipsError(data[-1][4:])
gns3server.modules.dynamips.dynamips_error.DynamipsError: unable to create UDP NIO
```

**Comment by noplay** [comment]
I think the port problem is the port is not free by this version of dynamips

**Comment by noplay** [comment]
After many test we can't reuse a previously used port.

**Comment by noplay** [comment]
I have workaround the issue .... You can take a look on the commit @grossmj  perhaps we need a more recent version of dynamips on OSX

**Comment by ehlers** [comment]
Thanks a lot for your effort !!!

I tested different dynamips version on OS X, no success in all cases (with plain GNS3 1.3.0).
I tested dynamips V0.2.14 stable and unstable, trunk (0.2.15-dev) stable and unstable. I even installed gcc and compiled with it instead of clang. Always this UDP NIO error.
