### ISSUE TITLE
timeout error when exporting a project

### ISSUE THREAD

**Issue by anthony-barn** [GNS3/gns3-server#1338]
Hi, i'm using gns3 since 3 weeks for studies. I'm trying to export my first project since 1 week but it's doesn't work.

**Here's the error code returned by gns3 :** 
ExportProjectWorker thread stopping with an error: Timeout error when connecting to http://192.168.234.128:3080/v2/compute/projects/8a79156c-127b-4c0f-b22f-49ef737ea3fc/files
Timeout error when connecting to http://192.168.234.128:3080/v2/compute/projects/8a79156c-127b-4c0f-b22f-49ef737ea3fc/files

I'm using GNS3 2.1.6 + GNS3 VM on VmWare on windows 10 64bits. 
I tried to disable firewall/antivirus, reinstall windows, gns and vmware. None helped me. 

**Here's my gns3_server.log (in appdata/roaming/gns3)** 
2018-05-27 17:37:25 INFO export_project.py:241 Downloading image 'pfSense-CE-2.3.5-RELEASE-2g-amd64-nanobsd.img' from compute server 'vm'
2018-05-27 17:38:12 INFO export_project.py:266 Saved images\qemu\pfSense-CE-2.3.5-RELEASE-2g-amd64-nanobsd.img
2018-05-27 17:38:12 INFO export_project.py:241 Downloading image 'Debian 9x-hda.qcow2' from compute server 'vm'
2018-05-27 17:38:12 INFO export_project.py:266 Saved images\qemu\Debian 9x-hda.qcow2
2018-05-27 17:38:12 INFO export_project.py:241 Downloading image 'debian-9.4.0-amd64-xfce-CD-1.iso' from compute server 'vm'
2018-05-27 17:38:28 INFO export_project.py:266 Saved images\qemu\debian-9.4.0-amd64-xfce-CD-1.iso
2018-05-27 17:38:28 INFO export_project.py:241 Downloading image 'core-linux-6.4-internet-0.1.img' from compute server 'vm'
2018-05-27 17:38:28 INFO export_project.py:266 Saved images\qemu\core-linux-6.4-internet-0.1.img
2018-05-27 17:38:28 INFO export_project.py:241 Downloading image 'Linux mint-hda.qcow2' from compute server 'vm'
2018-05-27 17:38:28 INFO export_project.py:266 Saved images\qemu\Linux mint-hda.qcow2
2018-05-27 17:40:29 ERROR route.py:205 Controller error detected: <class 'gns3server.controller.compute.ComputeError'>
Traceback (most recent call last):
  File "./gns3-server\gns3server\controller\compute.py", line 529, in _run_http_query
  File "C:\Python36-x64\lib\site-packages\aiohttp\helpers.py", line 104, in __iter__
  File "C:\Python36-x64\lib\site-packages\aiohttp\client.py", line 277, in _request
  File "C:\Python36-x64\lib\site-packages\aiohttp\client_reqrep.py", line 637, in start
  File "C:\Python36-x64\lib\site-packages\aiohttp\helpers.py", line 732, in __exit__
concurrent.futures._base.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./gns3-server\gns3server\web\route.py", line 181, in control_schema
  File "./gns3-server\gns3server\handlers\api\controller\project_handler.py", line 290, in export_project
  File "./gns3-server\gns3server\controller\export_project.py", line 86, in export_project
  File "./gns3-server\gns3server\controller\compute.py", line 644, in list_files
  File "./gns3-server\gns3server\controller\compute.py", line 387, in http_query
  File "./gns3-server\gns3server\controller\compute.py", line 531, in _run_http_query
gns3server.controller.compute.ComputeError: Timeout error when connecting to http://192.168.234.128:3080/v2/compute/projects/8a79156c-127b-4c0f-b22f-49ef737ea3fc/files

**Comment by grossmj** [comment]
This should be fixed when we release 2.1.7. Please re-open if you still encounter an issue.

**Comment by adikabintang** [comment]
Hi, I am running GNS3 version 2.2.6 on Windows 10 and the gns3-server is installed on a remote Ubuntu 18.04 (gns3-server is also version 2.2.6). I have the same problem as this issue: timeout when exporting as a portable project. I noticed that the timeout happens when the GNS3 on my windows accessing `/v2/compute/projects/{project_id}/files`. I tried to curl it and yes it hangs forever without any response. If I understand it correctly, this line https://github.com/GNS3/gns3-server/blob/2.2/gns3server/controller/compute.py#L617 does not return (I also noticed the `timeout=None`). Do you have any idea how to solve this problem?

**Comment by pearso1987** [comment]
> This should be fixed when we release 2.1.7. Please re-open if you still encounter an issue.

I am experiencing the same issue with latest version 2.2.31 any ideas?
