### ISSUE TITLE
[v2.1.5] : While diplicating a project => ZIP does not support timestamps before 1980

### ISSUE THREAD

**Issue by AJNOURI** [GNS3/gns3-server#1360]
From the community forum:
https://gns3.com/qa/weird-error-when-duplicating-pro

---------------
Hi guys,
 
we have a GNS3 in version 2.1.5 as VM running on a ESXi6.5...and my colleague encountered a weird error i never saw before:
He wants to duplicate his project (the original one works and is running, he can do things in there without any problems!), but everytime he does that the GNS3 GUI is throwing the following error messages...
 
Error while getting compute list: Operation timeout
Timeout after 30 seconds for request http://gns3@10.10.10.10:3080/v2/computes
Error while getting compute list: Operation timeout
Timeout after 30 seconds for request http://gns3@10.10.10.10:3080/v2/computes
Error while getting compute list: Operation timeout
Error while duplicating project: Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/gns3_server-2.1.5-py3.4.egg/gns3server/web/route.py", line 195, in control_schema
    yield from func(request, response)
  File "/usr/local/lib/python3.4/dist-packages/gns3_server-2.1.5-py3.4.egg/gns3server/handlers/api/controller/project_handler.py", line 376, in duplicate
    new_project = yield from project.duplicate(name=request.json.get("name"), location=location)
  File "/usr/local/lib/python3.4/dist-packages/gns3_server-2.1.5-py3.4.egg/gns3server/controller/project.py", line 882, in duplicate
    for data in zipstream:
  File "/usr/local/lib/python3.4/dist-packages/zipstream/__init__.py", line 182, in __iter__
    for data in self.__write(**kwargs):
  File "/usr/local/lib/python3.4/dist-packages/zipstream/__init__.py", line 255, in __write
    zinfo = ZipInfo(arcname, date_time)
  File "/usr/local/lib/python3.4/dist-packages/zipstream/__init__.py", line 105, in __init__
    zipfile.ZipInfo.__init__(self, *args, **kwargs)
  File "/usr/lib/python3.4/zipfile.py", line 334, in __init__
    raise ValueError('ZIP does not support timestamps before 1980')
ValueError: ZIP does not support timestamps before 1980
 
 
Hmmmm...wtf is happening here?
Any ideas how to solve it? It´s a lab with some F5 qemus in there, and it would be a messy job to do all again from the scratch, since he wants to try out certain ways from a starting point configuration.
 
Many thanks for the input,
Andreas

----------------

GNS3 in version 2.1.5 as VM running on a ESXi6.5

**Comment by grossmj** [comment]
I believe the problem comes from the OP's system. This is the only user who reported this issue.

**Comment by grossmj** [comment]
Now we make sure project files date is >= 1980 when needed.
