### ISSUE TITLE
ImportError: cannot import name 'generator_to_async_generator'

### ISSUE THREAD

**Issue by jean-christophe-manciot** [GNS3/gns3-server#1392]
Debian buster
gns3-gui v2.1.9
gns3-server v2.1.9
python3-pyqt5 5.11.2+dfsg-1+b1
python3-pyqt5.qtsvg 5.11.2+dfsg-1+b1
python3-pyqt5.qtwebsockets 5.11.2+dfsg-1+b1
python3-sip 4.19.12+dfsg-1
python3-async-generator 1.10-1

```
gns3 --debug
...
2018-08-24 10:01:07 DEBUG local_server:468 Starting local server process with "/usr/local/bin/gns3server" --local --debug --log="/root/.config/GNS3/gns3_server.log" --pid="/root/.config/GNS3/gns3_server.pid"
2018-08-24 10:01:07 DEBUG local_server:481 Local server process has started (PID=26331)
2018-08-24 10:01:07 DEBUG utils.progress_dialog:71 Set worker inside a thread <class 'gns3.utils.wait_for_connection_worker.WaitForConnectionWorker'>
2018-08-24 10:01:07 DEBUG utils.progress_dialog:112 WaitForConnectionWorker thread started
2018-08-24 10:01:10 ERROR local_server:487 Local server process has stopped
2018-08-24 10:01:10 ERROR local_server:489 Traceback (most recent call last):
  File "/usr/local/bin/gns3server", line 11, in <module>
    load_entry_point('gns3-server==2.1.9', 'console_scripts', 'gns3server')()
  File "/usr/local/lib/python3.6/dist-packages/gns3_server-2.1.9-py3.6.egg/gns3server/main.py", line 82, in main
    from gns3server.run import run
  File "/usr/local/lib/python3.6/dist-packages/gns3_server-2.1.9-py3.6.egg/gns3server/run.py", line 32, in <module>
    from gns3server.web.web_server import WebServer
  File "/usr/local/lib/python3.6/dist-packages/gns3_server-2.1.9-py3.6.egg/gns3server/web/web_server.py", line 32, in <module>
    from .route import Route
  File "/usr/local/lib/python3.6/dist-packages/gns3_server-2.1.9-py3.6.egg/gns3server/web/route.py", line 30, in <module>
    from ..compute.error import NodeError, ImageMissingError
  File "/usr/local/lib/python3.6/dist-packages/gns3_server-2.1.9-py3.6.egg/gns3server/compute/__init__.py", line 24, in <module>
    from .dynamips import Dynamips
  File "/usr/local/lib/python3.6/dist-packages/gns3_server-2.1.9-py3.6.egg/gns3server/compute/dynamips/__init__.py", line 45, in <module>
    from .dynamips_factory import DynamipsFactory
  File "/usr/local/lib/python3.6/dist-packages/gns3_server-2.1.9-py3.6.egg/gns3server/compute/dynamips/dynamips_factory.py", line 28, in <module>
    from .nodes.ethernet_switch import EthernetSwitch
  File "/usr/local/lib/python3.6/dist-packages/gns3_server-2.1.9-py3.6.egg/gns3server/compute/dynamips/nodes/ethernet_switch.py", line 25, in <module>
    from gns3server.utils.asyncio.embed_shell import EmbedShell, create_telnet_shell
  File "/usr/local/lib/python3.6/dist-packages/gns3_server-2.1.9-py3.6.egg/gns3server/utils/asyncio/embed_shell.py", line 24, in <module>
    from prompt_toolkit import prompt
  File "/usr/local/lib/python3.6/dist-packages/prompt_toolkit/__init__.py", line 16, in <module>
    from .interface import CommandLineInterface
  File "/usr/local/lib/python3.6/dist-packages/prompt_toolkit/interface.py", line 19, in <module>
    from .application import Application, AbortAction
  File "/usr/local/lib/python3.6/dist-packages/prompt_toolkit/application/__init__.py", line 2, in <module>
    from .application import Application
  File "/usr/local/lib/python3.6/dist-packages/prompt_toolkit/application/application.py", line 3, in <module>
    from prompt_toolkit.buffer import Buffer
  File "/usr/local/lib/python3.6/dist-packages/prompt_toolkit/buffer.py", line 9, in <module>
    from .completion import Completer, Completion, CompleteEvent
  File "/usr/local/lib/python3.6/dist-packages/prompt_toolkit/completion/__init__.py", line 2, in <module>
    from .base import Completion, Completer, ThreadedCompleter, DummyCompleter, DynamicCompleter, CompleteEvent, merge_completers, get_common_complete_suffix
  File "/usr/local/lib/python3.6/dist-packages/prompt_toolkit/completion/base.py", line 4, in <module>
    from prompt_toolkit.eventloop import generator_to_async_generator, AsyncGeneratorItem
ImportError: cannot import name 'generator_to_async_generator'
```
I cannot find any python3 module called ```generator_to_async_generator```. The closest one is ```async-generator```, but it does not seem to help.
Any suggestion?

**Comment by jean-christophe-manciot** [comment]
I always build gns3 gui & server from sources.
I have just rebuilt gns3 server from sources after having **reinstalled** all aforementioned dependencies and the **issue is gone**.
No clue about what happened.
Also:
```
# pip3 show pip
Name: pip
Version: 18.0
Summary: The PyPA recommended tool for installing Python packages.
Home-page: https://pip.pypa.io/
Author: The pip developers
Author-email: pypa-dev@groups.google.com
License: MIT
Location: /usr/local/lib/python3.6/dist-packages
Requires: 

# pip3 show prompt-toolkit
Name: prompt-toolkit
Version: 1.0.15
Summary: Library for building powerful interactive command lines in Python
Home-page: https://github.com/jonathanslenders/python-prompt-toolkit
Author: Jonathan Slenders
Author-email: UNKNOWN
License: UNKNOWN
Location: /usr/local/lib/python3.6/dist-packages
Requires: wcwidth, six
```
I'll try with Ubuntu cosmic and let you know.

**Comment by jean-christophe-manciot** [comment]
Ubuntu 18.10
gns3-gui v2.1.9
gns3-server v2.1.9
python3-pyqt5 5.11.2+dfsg-1ubuntu2
python3-pyqt5.qtsvg 5.11.2+dfsg-1ubuntu2
python3-pyqt5.qtwebsockets 5.11.2+dfsg-1ubuntu2
python3-sip 4.19.12+dfsg-1
python3-async-generator 1.10-1

Rebuilt both gns3 packages with all those dependencies reinstalled and the issue has not popped up.

**Comment by grossmj** [comment]
Thanks for testing :+1:
