### ISSUE TITLE
Exception when node with console auto start and no console port allocated

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-server#1493]
Looks like the root of the problem is when VPCS node is already running when opening a project. Maybe the node is not stopped properly when closing a project.

```
Traceback (most recent call last):
  File "/home/grossmj/PycharmProjects/gns3-gui/gns3/qt/__init__.py", line 247, in partial
    return func(*args, **kwargs)
  File "/home/grossmj/PycharmProjects/gns3-gui/gns3/http_client.py", line 716, in _processResponse
    callback(params, server=server, context=context, raw_body=raw_body)
  File "/home/grossmj/PycharmProjects/gns3-gui/gns3/qt/__init__.py", line 247, in partial
    return func(*args, **kwargs)
  File "/home/grossmj/PycharmProjects/gns3-gui/gns3/project.py", line 552, in _listNodesCallback
    topo.createNode(node)
  File "/home/grossmj/PycharmProjects/gns3-gui/gns3/topology.py", line 543, in createNode
    node.createNodeCallback(node_data)
  File "/home/grossmj/PycharmProjects/gns3-gui/gns3/node.py", line 319, in createNodeCallback
    result = self._parseControllerResponse(result)
  File "/home/grossmj/PycharmProjects/gns3-gui/gns3/node.py", line 513, in _parseControllerResponse
    self.setStatus(Node.started)
  File "/home/grossmj/PycharmProjects/gns3-gui/gns3/node.py", line 660, in setStatus
    self.openConsole()
  File "/home/grossmj/PycharmProjects/gns3-gui/gns3/node.py", line 685, in openConsole
    console_port = self.console()
  File "/home/grossmj/PycharmProjects/gns3-gui/gns3/node.py", line 176, in console
    return self.settings()["console"]
KeyError: 'console'
```

**Comment by grossmj** [comment]
Fixed
