### ISSUE TITLE
Exception when loading and quickly closing a project

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-server#1501]
```
AttributeError: 'dict' object has no attribute 'compute'
Traceback (most recent call last):
  File "/home/grossmj/PycharmProjects/gns3-server/gns3server/web/route.py", line 196, in control_schema
    await func(request, response)
  File "/home/grossmj/PycharmProjects/gns3-server/gns3server/handlers/api/controller/node_handler.py", line 106, in update
    await node.update(**request.json)
  File "/home/grossmj/PycharmProjects/gns3-server/gns3server/controller/node.py", line 409, in update
    self.project.dump()
  File "/home/grossmj/PycharmProjects/gns3-server/gns3server/controller/project.py", line 993, in dump
    topo = project_to_topology(self)
  File "/home/grossmj/PycharmProjects/gns3-server/gns3server/controller/topology.py", line 104, in project_to_topology
    computes.add(node.compute)
AttributeError: 'dict' object has no attribute 'compute'
```

**Comment by grossmj** [comment]
Seems to be related to the project auto close feature when a websocket client notification is disconnected.

**Comment by grossmj** [comment]
Should be good now.
