### ISSUE TITLE
Unable to set Idle-pc value - GNS3-GUI 2.2 with GNS3 VM 2.2

### ISSUE THREAD

**Issue by SNV100** [GNS3/gns3-server#1515]
Unablel to set Idle PC value  GN3-GUI 2.2.0a1 with GNS3 VM2.2.0a1 - Ubuntu 18.04

Error 

Traceback (most recent call last):
  File "/usr/share/gns3/gns3-gui/lib/python3.6/site-packages/gns3/dialogs/idlepc_dialog.py", line 92, in done
    self._applySlot()
  File "/usr/share/gns3/gns3-gui/lib/python3.6/site-packages/gns3/dialogs/idlepc_dialog.py", line 82, in _applySlot
    self._router.module().updateImageIdlepc(ios_image, idlepc)
  File "/usr/share/gns3/gns3-gui/lib/python3.6/site-packages/gns3/modules/dynamips/__init__.py", line 169, in updateImageIdlepc
    for ios_router in self._ios_routers.values():
AttributeError: 'Dynamips' object has no attribute '_ios_router

**Comment by grossmj** [comment]
Thanks for catching this. Fixed in https://github.com/GNS3/gns3-gui/commit/c85112978defbb685239e335cab03bf8da97947a
