### ISSUE TITLE
Cannot run gns3-server-2.2.0a1 after successful installation 

### ISSUE THREAD

**Issue by n3oxmind** [GNS3/gns3-server#1523]
Running gns3-server-2.20a1 from terminal throws these errors below:

`Traceback (most recent call last):
  File "/usr/local/bin/gns3server", line 11, in <module>
    load_entry_point('gns3-server==2.2.0a1', 'console_scripts', 'gns3server')()
  File "/usr/local/lib/python3.7/site-packages/gns3_server-2.2.0a1-py3.7.egg/gns3server/main.py", line 82, in main
    from gns3server.run import run
  File "/usr/local/lib/python3.7/site-packages/gns3_server-2.2.0a1-py3.7.egg/gns3server/run.py", line 32, in <module>
    from gns3server.web.web_server import WebServer
  File "/usr/local/lib/python3.7/site-packages/gns3_server-2.2.0a1-py3.7.egg/gns3server/web/web_server.py", line 26, in <module>
    import aiohttp
  File "/usr/lib64/python3.7/site-packages/aiohttp/__init__.py", line 6, in <module>
    from .client import *  # noqa
  File "/usr/lib64/python3.7/site-packages/aiohttp/client.py", line 12, in <module>
    from typing import Any, Generator, Optional, Tuple
  File "/usr/local/lib/python3.7/site-packages/typing.py", line 1356, in <module>
    class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):
  File "/usr/local/lib/python3.7/site-packages/typing.py", line 1004, in __new__
    self._abc_registry = extra._abc_registry
AttributeError: type object 'Callable' has no attribute '_abc_registry'`

**Comment by grossmj** [comment]
I recommend you uninstall the `typing` module and reinstall all the dependencies (pip3 install -r requirements.txt) or try to run GNS3 in a virtual environment (see https://github.com/GNS3/gns3-server/issues/1525).

**Comment by n3oxmind** [comment]
Thanks for that, the issue was that  for some reason I have to run the gns3server as superuser `sudo gns3server`. how did that happen I dont know I'll figure it out once I dig into it. If you have any idea let me know.

P.S. I installed gns3server witch pip3 command.

**Comment by n3oxmind** [comment]
Okay, its was a root privilege issue. just for future reference all I did was removing python3.7 `$HOME/.local/lib/python3.7` and reinstalling gns3-server with pip3.

I'm gonna close this issue.

Thanks,
