### ISSUE TITLE
projects all of sudden will not launch - Win 10 (10.0.17763 N/A Build 17763)

### ISSUE THREAD

**Issue by melshman** [GNS3/gns3-server#1614]
Hoping someone can help get my projects up and running again.   Any help is really appreciated.  Thanks in advance!  I think there was also a windows update that got installed just the other day that my have coincided with the beginning of the issues.  (Windows 10 Build info below).  

I have been working successfully with same GNS3 setup for over a month.  Using the GNS3 VM on VMware Player.  Version below.   Never had a problem until couple days ago and I can't seem to fix the issue.  All of a sudden I can't open most projects.  Getting this error:

**Internal server error http://127.0.0.1:3080/v2/compute/projects/313a3e29-7ad6-407d-b006-ac4713e978bf/nat/nodes**

In fact there is only one project that I can open and it works perfectly.  It uses the GNS3 VM and I can start it, add devices, etc. No issues.   Unfortuneately the projects that I need to work, don't.   I thought that was interesting information that might lead to a solution. I included info below on launching this project as well as a project that does not launch.  

**NOTE:  I CAN create new projects just fine, so something is making it so that projects created previously are not opening properly any more**.

I see some potential issues in the server.log below, but don't know how to make heads or tails.  

I still launch GNS3 successfully as admin and everything looks good, VM and local come up Green, but there are some errors in the server log during GNS3 booting up.  See below. 

**When I try to launch most projects I get the following error (From Gui Log)**
2019-07-20 11:29:05 CRITICAL __init__.py:245 Internal server error http://127.0.0.1:3080/v2/compute/projects/313a3e29-7ad6-407d-b006-ac4713e978bf/nat/nodes
error msg

**Windows Build Info:**

OS Name: Microsoft Windows 10 Pro
OS Version: 10.0.17763 N/A Build 17763

GNS3 vm version:  0.10.14
GNS3 version: 2.1.21

VMWare Player
VMware® Workstation 12 Player
12.5.9 build-7535481

Server and Gui logs are listed below in full, but i copied this part to show where something doesn't appear to go well.  Unfortunately, i don't know if this was always occuring or if this is new and the source of the problem, as I never reviewed the logs when things were working.  :)

**Error Snippet from Server.log (Full log below) - this occurs during launch GNS3**

2019-07-20 12:20:05 INFO compute.py:420 Connecting to compute 'vm'
2019-07-20 12:20:05 INFO helpers.py:534 127.0.0.1 [20/Jul/2019:16:20:05 +0000] "GET /v2/compute/network/interfaces HTTP/1.1" 500 307 "-" "Python/3.6 aiohttp/2.3.10"
2019-07-20 12:20:05 ERROR base_events.py:1285 Task exception was never retrieved
future: <Task finished coro=<GNS3VM._check_network() done, defined at ./gns3-server\gns3server\controller\gns3vm\__init__.py:311> exception=<HTTPInternalServerError Internal Server Error not prepared>>
Traceback (most recent call last):
File "./gns3-server\gns3server\controller\gns3vm\__init__.py", line 329, in _check_network
File "./gns3-server\gns3server\controller\compute.py", line 155, in interfaces
File "./gns3-server\gns3server\controller\compute.py", line 622, in get
File "./gns3-server\gns3server\controller\compute.py", line 398, in http_query
File "./gns3-server\gns3server\controller\compute.py", line 602, in _run_http_query
aiohttp.web_exceptions.HTTPInternalServerError: Internal Server Error

**No Error Snippet when launching the one project that still works**

2019-07-20 12:32:45 INFO helpers.py:534 127.0.0.1 [20/Jul/2019:16:32:45 +0000] "GET /v2/computes HTTP/1.1" 200 1822 "-" "GNS3 QT Client v2.1.21"
2019-07-20 12:32:47 INFO helpers.py:534 127.0.0.1 [20/Jul/2019:16:32:47 +0000] "GET /v2/computes HTTP/1.1" 200 1822 "-" "GNS3 QT Client v2.1.21"
2019-07-20 12:32:49 INFO helpers.py:534 127.0.0.1 [20/Jul/2019:16:32:49 +0000] "GET /v2/computes HTTP/1.1" 200 1821 "-" "GNS3 QT Client v2.1.21"
2019-07-20 12:32:51 INFO helpers.py:534 127.0.0.1 [20/Jul/2019:16:32:51 +0000] "GET /v2/computes HTTP/1.1" 200 1822 "-" "GNS3 QT Client v2.1.21"
2019-07-20 12:32:53 INFO helpers.py:534 127.0.0.1 [20/Jul/2019:16:32:53 +0000] "POST /v2/projects/load HTTP/1.1" 201 749 "-" "GNS3 QT Client v2.1.21"
2019-07-20 12:32:53 INFO helpers.py:534 127.0.0.1 [20/Jul/2019:16:32:53 +0000] "GET /v2/projects/65bb2444-ecb3-4bcb-97bd-c012345b0ee4/nodes HTTP/1.1" 200 13331 "-" "GNS3 QT Client v2.1.21"
2019-07-20 12:32:53 INFO helpers.py:534 127.0.0.1 [20/Jul/2019:16:32:53 +0000] "GET /v2/projects/65bb2444-ecb3-4bcb-97bd-c012345b0ee4/links HTTP/1.1" 200 4008 "-" "GNS3 QT Client v2.1.21"
2019-07-20 12:32:53 INFO helpers.py:534 127.0.0.1 [20/Jul/2019:16:32:53 +0000] "GET /v2/projects/65bb2444-ecb3-4bcb-97bd-c012345b0ee4/drawings HTTP/1.1" 200 867 "-" "GNS3 QT Client v2.1.21"

**gns3_gui.log**

2019-07-20 12:19:34 INFO logger.py:126 Log level: INFO
2019-07-20 12:19:34 INFO main.py:259 GNS3 GUI version 2.1.21
2019-07-20 12:19:34 INFO main.py:260 Copyright (c) 2007-2019 GNS3 Technologies Inc.
2019-07-20 12:19:34 INFO main.py:262 Application started with C:\Program Files\GNS3\gns3.exe
2019-07-20 12:19:41 WARNING local_server.py:374 The NPF or NPCAP service is not installed, please install Winpcap or Npcap and reboot.
2019-07-20 12:20:34 CRITICAL __init__.py:245 Internal server error http://127.0.0.1:3080/v2/compute/projects/313a3e29-7ad6-407d-b006-ac4713e978bf/nat/nodes

**gns3_server.log**

2019-07-20 12:19:42 INFO run.py:212 GNS3 server version 2.1.21
2019-07-20 12:19:42 INFO run.py:214 Copyright (c) 2007-2019 GNS3 Technologies Inc.
2019-07-20 12:19:42 INFO run.py:217 Config file C:\Users\tarmstrong\AppData\Roaming\GNS3\gns3_server.ini loaded
2019-07-20 12:19:42 WARNING run.py:223 Local mode is enabled. Beware, clients will have full control on your filesystem
2019-07-20 12:19:42 INFO run.py:231 Running with Python 3.6.8 and has PID 3224
2019-07-20 12:19:42 INFO web_server.py:283 Starting server on 127.0.0.1:3080
2019-07-20 12:19:42 INFO __init__.py:65 Load controller configuration file C:\Users\tarmstrong\AppData\Roaming\GNS3\gns3_controller.conf
2019-07-20 12:19:42 INFO __init__.py:168 Start controller
2019-07-20 12:19:43 INFO compute.py:79 Create compute local
2019-07-20 12:19:43 INFO compute.py:420 Connecting to compute 'local'
2019-07-20 12:19:43 INFO helpers.py:534 127.0.0.1 [20/Jul/2019:16:19:43 +0000] "GET /v2/version HTTP/1.1" 200 227 "-" "GNS3 QT Client v2.1.21"
2019-07-20 12:19:43 INFO helpers.py:534 127.0.0.1 [20/Jul/2019:16:19:43 +0000] "GET /v2/compute/capabilities HTTP/1.1" 200 519 "-" "Python/3.6 aiohttp/2.3.10"
2019-07-20 12:19:43 INFO __init__.py:280 Start the GNS3 VM
2019-07-20 12:19:43 INFO compute.py:79 Create compute vm
2019-07-20 12:19:43 INFO helpers.py:534 127.0.0.1 [20/Jul/2019:16:19:43 +0000] "GET /v2/computes HTTP/1.1" 200 1384 "-" "GNS3 QT Client v2.1.21"
2019-07-20 12:19:43 INFO helpers.py:534 127.0.0.1 [20/Jul/2019:16:19:43 +0000] "GET /v2/appliances/templates HTTP/1.1" 200 650908 "-" "GNS3 QT Client v2.1.21"
2019-07-20 12:19:43 INFO helpers.py:534 127.0.0.1 [20/Jul/2019:16:19:43 +0000] "GET /v2/appliances HTTP/1.1" 200 4892 "-" "GNS3 QT Client v2.1.21"
2019-07-20 12:19:43 INFO helpers.py:534 127.0.0.1 [20/Jul/2019:16:19:43 +0000] "GET /v2/appliances/templates HTTP/1.1" 200 650908 "-" "GNS3 QT Client v2.1.21"
2019-07-20 12:19:43 INFO helpers.py:534 127.0.0.1 [20/Jul/2019:16:19:43 +0000] "GET /v2/appliances HTTP/1.1" 200 4892 "-" "GNS3 QT Client v2.1.21"
2019-07-20 12:19:43 INFO helpers.py:534 127.0.0.1 [20/Jul/2019:16:19:43 +0000] "GET /v2/projects HTTP/1.1" 200 183 "-" "GNS3 QT Client v2.1.21"
2019-07-20 12:19:43 INFO __init__.py:613 Searching for VMware VMs in directory "C:\Users\tarmstrong\OneDrive - VT Group\Documents\Virtual Machines"
2019-07-20 12:19:43 INFO __init__.py:397 Executing vmrun with command: 'C:\Program Files (x86)\VMware\VMware VIX\vmrun.exe' -T player checkToolsState 'C:\Users\tarmstrong\OneDrive - VT Group\Documents\Virtual Machines\GNS3 VM\GNS3 VM.vmx'
2019-07-20 12:19:43 INFO helpers.py:534 127.0.0.1 [20/Jul/2019:16:19:43 +0000] "GET /v2/version HTTP/1.1" 200 227 "-" "GNS3 QT Client v2.1.21"
2019-07-20 12:19:43 INFO helpers.py:534 127.0.0.1 [20/Jul/2019:16:19:43 +0000] "GET /v2/projects HTTP/1.1" 200 183 "-" "GNS3 QT Client v2.1.21"
2019-07-20 12:19:43 INFO helpers.py:534 127.0.0.1 [20/Jul/2019:16:19:43 +0000] "GET /v2/symbols/linux_guest.svg/raw HTTP/1.1" 200 64741 "-" "GNS3 QT Client v2.1.21"
2019-07-20 12:19:43 INFO helpers.py:534 127.0.0.1 [20/Jul/2019:16:19:43 +0000] "GET /v2/symbols/:/symbols/router.svg/raw HTTP/1.1" 200 11037 "-" "GNS3 QT Client v2.1.21"
2019-07-20 12:19:43 INFO helpers.py:534 127.0.0.1 [20/Jul/2019:16:19:43 +0000] "GET /v2/symbols/:/symbols/route_switch_processor.svg/raw HTTP/1.1" 200 25208 "-" "GNS3 QT Client v2.1.21"
2019-07-20 12:19:43 INFO helpers.py:534 127.0.0.1 [20/Jul/2019:16:19:43 +0000] "GET /v2/symbols/:/symbols/multilayer_switch.svg/raw HTTP/1.1" 200 21517 "-" "GNS3 QT Client v2.1.21"
2019-07-20 12:19:43 WARNING symbols.py:94 Could not retrieve symbol ':/symbols/guest.svg'
2019-07-20 12:19:43 INFO helpers.py:534 127.0.0.1 [20/Jul/2019:16:19:43 +0000] "GET /v2/symbols/:/symbols/guest.svg/raw HTTP/1.1" 200 18843 "-" "GNS3 QT Client v2.1.21"
2019-07-20 12:19:43 WARNING symbols.py:94 Could not retrieve symbol 'loadbalancer.svg'
2019-07-20 12:19:43 INFO helpers.py:534 127.0.0.1 [20/Jul/2019:16:19:43 +0000] "GET /v2/symbols/loadbalancer.svg/raw HTTP/1.1" 200 18843 "-" "GNS3 QT Client v2.1.21"
2019-07-20 12:19:44 INFO helpers.py:534 127.0.0.1 [20/Jul/2019:16:19:44 +0000] "GET /v2/symbols/:/symbols/firewall.svg/raw HTTP/1.1" 200 9626 "-" "GNS3 QT Client v2.1.21"
2019-07-20 12:19:44 INFO helpers.py:534 127.0.0.1 [20/Jul/2019:16:19:44 +0000] "GET /v2/symbols/:/symbols/asa.svg/raw HTTP/1.1" 200 18812 "-" "GNS3 QT Client v2.1.21"
2019-07-20 12:19:44 INFO __init__.py:397 Executing vmrun with command: 'C:\Program Files (x86)\VMware\VMware VIX\vmrun.exe' -T player list
2019-07-20 12:19:44 WARNING symbols.py:94 Could not retrieve symbol 'mgmt_station.svg'
2019-07-20 12:19:44 INFO helpers.py:534 127.0.0.1 [20/Jul/2019:16:19:44 +0000] "GET /v2/symbols/mgmt_station.svg/raw HTTP/1.1" 200 18843 "-" "GNS3 QT Client v2.1.21"
2019-07-20 12:19:44 WARNING symbols.py:94 Could not retrieve symbol 'cisco-fmcv.svg'
2019-07-20 12:19:44 INFO helpers.py:534 127.0.0.1 [20/Jul/2019:16:19:44 +0000] "GET /v2/symbols/cisco-fmcv.svg/raw HTTP/1.1" 200 18843 "-" "GNS3 QT Client v2.1.21"
2019-07-20 12:19:44 WARNING symbols.py:94 Could not retrieve symbol 'cisco-ise.svg'
2019-07-20 12:19:44 INFO helpers.py:534 127.0.0.1 [20/Jul/2019:16:19:44 +0000] "GET /v2/symbols/cisco-ise.svg/raw HTTP/1.1" 200 18843 "-" "GNS3 QT Client v2.1.21"
2019-07-20 12:19:44 INFO helpers.py:534 127.0.0.1 [20/Jul/2019:16:19:44 +0000] "GET /v2/symbols/:/symbols/ids.svg/raw HTTP/1.1" 200 13373 "-" "GNS3 QT Client v2.1.21"
2019-07-20 12:19:44 INFO helpers.py:534 127.0.0.1 [20/Jul/2019:16:19:44 +0000] "GET /v2/symbols/:/symbols/wlan_controller.svg/raw HTTP/1.1" 200 261470 "-" "GNS3 QT Client v2.1.21"
2019-07-20 12:19:44 INFO vmware_gns3_vm.py:154 Update GNS3 VM settings
2019-07-20 12:19:44 INFO vmware_gns3_vm.py:88 GNS3 VM vCPU count set to 1 and RAM amount set to 2048
2019-07-20 12:19:44 INFO __init__.py:397 Executing vmrun with command: 'C:\Program Files (x86)\VMware\VMware VIX\vmrun.exe' -T player start 'C:\Users\tarmstrong\OneDrive - VT Group\Documents\Virtual Machines\GNS3 VM\GNS3 VM.vmx'
2019-07-20 12:19:44 WARNING symbols.py:94 Could not retrieve symbol 'ethernet_switch.svg'
2019-07-20 12:19:44 INFO helpers.py:534 127.0.0.1 [20/Jul/2019:16:19:44 +0000] "GET /v2/symbols/ethernet_switch.svg/raw HTTP/1.1" 200 18843 "-" "GNS3 QT Client v2.1.21"
2019-07-20 12:19:44 WARNING symbols.py:94 Could not retrieve symbol 'firefox.svg'
2019-07-20 12:19:44 INFO helpers.py:534 127.0.0.1 [20/Jul/2019:16:19:44 +0000] "GET /v2/symbols/firefox.svg/raw HTTP/1.1" 200 18843 "-" "GNS3 QT Client v2.1.21"
2019-07-20 12:19:44 WARNING symbols.py:94 Could not retrieve symbol 'fortinet.svg'
2019-07-20 12:19:44 INFO helpers.py:534 127.0.0.1 [20/Jul/2019:16:19:44 +0000] "GET /v2/symbols/fortinet.svg/raw HTTP/1.1" 200 18843 "-" "GNS3 QT Client v2.1.21"
2019-07-20 12:19:44 INFO helpers.py:534 127.0.0.1 [20/Jul/2019:16:19:44 +0000] "GET /v2/symbols/:/symbols/cloud.svg/raw HTTP/1.1" 200 27982 "-" "GNS3 QT Client v2.1.21"
2019-07-20 12:19:44 WARNING symbols.py:94 Could not retrieve symbol 'juniper-vqfx.svg'
2019-07-20 12:19:44 INFO helpers.py:534 127.0.0.1 [20/Jul/2019:16:19:44 +0000] "GET /v2/symbols/juniper-vqfx.svg/raw HTTP/1.1" 200 18843 "-" "GNS3 QT Client v2.1.21"
2019-07-20 12:19:44 WARNING symbols.py:94 Could not retrieve symbol 'juniper-vmx.svg'
2019-07-20 12:19:44 INFO helpers.py:534 127.0.0.1 [20/Jul/2019:16:19:44 +0000] "GET /v2/symbols/juniper-vmx.svg/raw HTTP/1.1" 200 18843 "-" "GNS3 QT Client v2.1.21"
2019-07-20 12:19:44 INFO helpers.py:534 127.0.0.1 [20/Jul/2019:16:19:44 +0000] "GET /v2/symbols/:/symbols/router_firewall.svg/raw HTTP/1.1" 200 50061 "-" "GNS3 QT Client v2.1.21"
2019-07-20 12:19:44 WARNING symbols.py:94 Could not retrieve symbol 'mgmt_station_docker.svg'
2019-07-20 12:19:44 INFO helpers.py:534 127.0.0.1 [20/Jul/2019:16:19:44 +0000] "GET /v2/symbols/mgmt_station_docker.svg/raw HTTP/1.1" 200 18843 "-" "GNS3 QT Client v2.1.21"
2019-07-20 12:19:44 INFO helpers.py:534 127.0.0.1 [20/Jul/2019:16:19:44 +0000] "GET /v2/symbols/ostinato-3d-icon.svg/raw HTTP/1.1" 200 55835 "-" "GNS3 QT Client v2.1.21"
2019-07-20 12:19:44 WARNING symbols.py:94 Could not retrieve symbol 'pan-vm-fw.svg'
2019-07-20 12:19:44 INFO helpers.py:534 127.0.0.1 [20/Jul/2019:16:19:44 +0000] "GET /v2/symbols/pan-vm-fw.svg/raw HTTP/1.1" 200 18843 "-" "GNS3 QT Client v2.1.21"
2019-07-20 12:19:44 WARNING symbols.py:94 Could not retrieve symbol 'parrotlogo.png'
2019-07-20 12:19:44 INFO helpers.py:534 127.0.0.1 [20/Jul/2019:16:19:44 +0000] "GET /v2/symbols/parrotlogo.png/raw HTTP/1.1" 200 18843 "-" "GNS3 QT Client v2.1.21"
2019-07-20 12:19:44 WARNING symbols.py:94 Could not retrieve symbol 'securityonion-logo.png'
2019-07-20 12:19:44 INFO helpers.py:534 127.0.0.1 [20/Jul/2019:16:19:44 +0000] "GET /v2/symbols/securityonion-logo.png/raw HTTP/1.1" 200 18843 "-" "GNS3 QT Client v2.1.21"
2019-07-20 12:19:44 WARNING symbols.py:94 Could not retrieve symbol 'vRIN.svg'
2019-07-20 12:19:44 INFO helpers.py:534 127.0.0.1 [20/Jul/2019:16:19:44 +0000] "GET /v2/symbols/vRIN.svg/raw HTTP/1.1" 200 18843 "-" "GNS3 QT Client v2.1.21"
2019-07-20 12:19:44 WARNING symbols.py:94 Could not retrieve symbol 'microsoft.svg'
2019-07-20 12:19:44 INFO helpers.py:534 127.0.0.1 [20/Jul/2019:16:19:44 +0000] "GET /v2/symbols/microsoft.svg/raw HTTP/1.1" 200 18843 "-" "GNS3 QT Client v2.1.21"
2019-07-20 12:19:44 INFO helpers.py:534 127.0.0.1 [20/Jul/2019:16:19:44 +0000] "GET /v2/symbols/:/symbols/vpcs_guest.svg/raw HTTP/1.1" 200 19495 "-" "GNS3 QT Client v2.1.21"
2019-07-20 12:19:44 INFO helpers.py:534 127.0.0.1 [20/Jul/2019:16:19:44 +0000] "GET /v2/symbols/:/symbols/ethernet_switch.svg/raw HTTP/1.1" 200 9273 "-" "GNS3 QT Client v2.1.21"
2019-07-20 12:19:44 INFO helpers.py:534 127.0.0.1 [20/Jul/2019:16:19:44 +0000] "GET /v2/symbols/:/symbols/hub.svg/raw HTTP/1.1" 200 7636 "-" "GNS3 QT Client v2.1.21"
2019-07-20 12:19:44 INFO helpers.py:534 127.0.0.1 [20/Jul/2019:16:19:44 +0000] "GET /v2/symbols/:/symbols/frame_relay_switch.svg/raw HTTP/1.1" 200 10027 "-" "GNS3 QT Client v2.1.21"
2019-07-20 12:19:44 INFO helpers.py:534 127.0.0.1 [20/Jul/2019:16:19:44 +0000] "GET /v2/symbols/:/symbols/atm_switch.svg/raw HTTP/1.1" 200 9959 "-" "GNS3 QT Client v2.1.21"
2019-07-20 12:19:44 INFO helpers.py:534 127.0.0.1 [20/Jul/2019:16:19:44 +0000] "GET /v2/computes HTTP/1.1" 200 1384 "-" "GNS3 QT Client v2.1.21"
2019-07-20 12:19:46 INFO helpers.py:534 127.0.0.1 [20/Jul/2019:16:19:46 +0000] "GET /v2/computes HTTP/1.1" 200 1384 "-" "GNS3 QT Client v2.1.21"
2019-07-20 12:19:47 INFO vmware_gns3_vm.py:164 GNS3 VM has been started
2019-07-20 12:19:47 INFO vmware_gns3_vm.py:169 Waiting for GNS3 VM IP
2019-07-20 12:19:48 INFO helpers.py:534 127.0.0.1 [20/Jul/2019:16:19:48 +0000] "GET /v2/computes HTTP/1.1" 200 1384 "-" "GNS3 QT Client v2.1.21"
2019-07-20 12:19:50 INFO helpers.py:534 127.0.0.1 [20/Jul/2019:16:19:50 +0000] "GET /v2/computes HTTP/1.1" 200 1384 "-" "GNS3 QT Client v2.1.21"
2019-07-20 12:19:52 INFO helpers.py:534 127.0.0.1 [20/Jul/2019:16:19:52 +0000] "GET /v2/computes HTTP/1.1" 200 1384 "-" "GNS3 QT Client v2.1.21"
2019-07-20 12:19:54 INFO helpers.py:534 127.0.0.1 [20/Jul/2019:16:19:54 +0000] "GET /v2/computes HTTP/1.1" 200 1384 "-" "GNS3 QT Client v2.1.21"
2019-07-20 12:19:55 INFO vmware_gns3_vm.py:183 GNS3 VM IP address set to 192.168.147.128
2019-07-20 12:19:56 INFO helpers.py:534 127.0.0.1 [20/Jul/2019:16:19:56 +0000] "GET /v2/computes HTTP/1.1" 200 1385 "-" "GNS3 QT Client v2.1.21"
2019-07-20 12:19:58 INFO helpers.py:534 127.0.0.1 [20/Jul/2019:16:19:58 +0000] "GET /v2/computes HTTP/1.1" 200 1385 "-" "GNS3 QT Client v2.1.21"
2019-07-20 12:20:00 INFO helpers.py:534 127.0.0.1 [20/Jul/2019:16:20:00 +0000] "GET /v2/computes HTTP/1.1" 200 1385 "-" "GNS3 QT Client v2.1.21"
2019-07-20 12:20:02 INFO helpers.py:534 127.0.0.1 [20/Jul/2019:16:20:02 +0000] "GET /v2/computes HTTP/1.1" 200 1385 "-" "GNS3 QT Client v2.1.21"
2019-07-20 12:20:04 INFO helpers.py:534 127.0.0.1 [20/Jul/2019:16:20:04 +0000] "GET /v2/computes HTTP/1.1" 200 1384 "-" "GNS3 QT Client v2.1.21"
2019-07-20 12:20:05 INFO compute.py:420 Connecting to compute 'vm'
2019-07-20 12:20:05 INFO helpers.py:534 127.0.0.1 [20/Jul/2019:16:20:05 +0000] "GET /v2/compute/network/interfaces HTTP/1.1" 500 307 "-" "Python/3.6 aiohttp/2.3.10"
2019-07-20 12:20:05 ERROR base_events.py:1285 Task exception was never retrieved
future: <Task finished coro=<GNS3VM._check_network() done, defined at ./gns3-server\gns3server\controller\gns3vm\__init__.py:311> exception=<HTTPInternalServerError Internal Server Error not prepared>>
Traceback (most recent call last):
File "./gns3-server\gns3server\controller\gns3vm\__init__.py", line 329, in _check_network
File "./gns3-server\gns3server\controller\compute.py", line 155, in interfaces
File "./gns3-server\gns3server\controller\compute.py", line 622, in get
File "./gns3-server\gns3server\controller\compute.py", line 398, in http_query
File "./gns3-server\gns3server\controller\compute.py", line 602, in _run_http_query
aiohttp.web_exceptions.HTTPInternalServerError: Internal Server Error
2019-07-20 12:20:06 INFO helpers.py:534 127.0.0.1 [20/Jul/2019:16:20:06 +0000] "GET /v2/computes HTTP/1.1" 200 1821 "-" "GNS3 QT Client v2.1.21"
2019-07-20 12:20:08 INFO helpers.py:534 127.0.0.1 [20/Jul/2019:16:20:08 +0000] "GET /v2/computes HTTP/1.1" 200 1821 "-" "GNS3 QT Client v2.1.21"
2019-07-20 12:20:10 INFO helpers.py:534 127.0.0.1 [20/Jul/2019:16:20:10 +0000] "GET /v2/computes HTTP/1.1" 200 1821 "-" "GNS3 QT Client v2.1.21"
2019-07-20 12:20:12 INFO helpers.py:534 127.0.0.1 [20/Jul/2019:16:20:12 +0000] "GET /v2/computes HTTP/1.1" 200 1822 "-" "GNS3 QT Client v2.1.21"
2019-07-20 12:20:14 INFO helpers.py:534 127.0.0.1 [20/Jul/2019:16:20:14 +0000] "GET /v2/computes HTTP/1.1" 200 1822 "-" "GNS3 QT Client v2.1.21"
2019-07-20 12:20:16 INFO helpers.py:534 127.0.0.1 [20/Jul/2019:16:20:16 +0000] "GET /v2/computes HTTP/1.1" 200 1822 "-" "GNS3 QT Client v2.1.21"
2019-07-20 12:20:18 INFO helpers.py:534 127.0.0.1 [20/Jul/2019:16:20:18 +0000] "GET /v2/computes HTTP/1.1" 200 1822 "-" "GNS3 QT Client v2.1.21"
2019-07-20 12:20:20 INFO helpers.py:534 127.0.0.1 [20/Jul/2019:16:20:20 +0000] "GET /v2/computes HTTP/1.1" 200 1821 "-" "GNS3 QT Client v2.1.21"
2019-07-20 12:20:22 INFO helpers.py:534 127.0.0.1 [20/Jul/2019:16:20:22 +0000] "GET /v2/computes HTTP/1.1" 200 1822 "-" "GNS3 QT Client v2.1.21"
2019-07-20 12:20:24 INFO helpers.py:534 127.0.0.1 [20/Jul/2019:16:20:24 +0000] "GET /v2/computes HTTP/1.1" 200 1822 "-" "GNS3 QT Client v2.1.21"
2019-07-20 12:20:26 INFO helpers.py:534 127.0.0.1 [20/Jul/2019:16:20:26 +0000] "GET /v2/computes HTTP/1.1" 200 1822 "-" "GNS3 QT Client v2.1.21"
2019-07-20 12:20:28 INFO helpers.py:534 127.0.0.1 [20/Jul/2019:16:20:28 +0000] "GET /v2/computes HTTP/1.1" 200 1822 "-" "GNS3 QT Client v2.1.21"
2019-07-20 12:20:30 INFO helpers.py:534 127.0.0.1 [20/Jul/2019:16:20:30 +0000] "GET /v2/computes HTTP/1.1" 200 1821 "-" "GNS3 QT Client v2.1.21"
2019-07-20 12:20:32 INFO helpers.py:534 127.0.0.1 [20/Jul/2019:16:20:32 +0000] "GET /v2/computes HTTP/1.1" 200 1821 "-" "GNS3 QT Client v2.1.21"
2019-07-20 12:20:33 INFO helpers.py:534 127.0.0.1 [20/Jul/2019:16:20:33 +0000] "GET /v2/computes HTTP/1.1" 200 1821 "-" "GNS3 QT Client v2.1.21"
2019-07-20 12:20:34 INFO project.py:81 Project 313a3e29-7ad6-407d-b006-ac4713e978bf with path 'C:\Users\tarmstrong\OneDrive - VT Group\Documents\__PROJECTS\GNS3\gns3-vm' created
2019-07-20 12:20:34 INFO helpers.py:534 127.0.0.1 [20/Jul/2019:16:20:34 +0000] "POST /v2/compute/projects HTTP/1.1" 201 302 "-" "Python/3.6 aiohttp/2.3.10"
2019-07-20 12:20:34 INFO helpers.py:534 127.0.0.1 [20/Jul/2019:16:20:34 +0000] "POST /v2/compute/projects/313a3e29-7ad6-407d-b006-ac4713e978bf/nat/nodes HTTP/1.1" 500 320 "-" "Python/3.6 aiohttp/2.3.10"
2019-07-20 12:20:34 INFO project.py:367 Project 313a3e29-7ad6-407d-b006-ac4713e978bf with path 'C:\Users\tarmstrong\OneDrive - VT Group\Documents\__PROJECTS\GNS3\gns3-vm' closed
2019-07-20 12:20:34 INFO helpers.py:534 127.0.0.1 [20/Jul/2019:16:20:34 +0000] "POST /v2/compute/projects/313a3e29-7ad6-407d-b006-ac4713e978bf/close HTTP/1.1" 204 224 "-" "Python/3.6 aiohttp/2.3.10"
2019-07-20 12:20:34 INFO helpers.py:534 127.0.0.1 [20/Jul/2019:16:20:34 +0000] "POST /v2/projects/load HTTP/1.1" 500 357 "-" "GNS3 QT Client v2.1.21"
2019-07-20 12:20:35 INFO helpers.py:534 127.0.0.1 [20/Jul/2019:16:20:35 +0000] "GET /v2/computes HTTP/1.1" 200 1821 "-" "GNS3 QT Client v2.1.21"
2019-07-20 12:20:37 INFO helpers.py:534 127.0.0.1 [20/Jul/2019:16:20:37 +0000] "GET /v2/computes HTTP/1.1" 200 1822 "-" "GNS3 QT Client v2.1.21"
2019-07-20 12:20:39 INFO helpers.py:534 127.0.0.1 [20/Jul/2019:16:20:39 +0000] "GET /v2/computes HTTP/1.1" 200 1822 "-" "GNS3 QT Client v2.1.21"
2019-07-20 12:20:41 INFO helpers.py:534 127.0.0.1 [20/Jul/2019:16:20:41 +0000] "GET /v2/computes HTTP/1.1" 200 1822 "-" "GNS3 QT Client v2.1.21"
2019-07-20 12:20:43 INFO helpers.py:534 127.0.0.1 [20/Jul/2019:16:20:43 +0000] "GET /v2/computes HTTP/1.1" 200 1821 "-" "GNS3 QT Client v2.1.21"
2019-07-20 12:20:45 INFO helpers.py:534 127.0.0.1 [20/Jul/2019:16:20:45 +0000] "GET /v2/computes HTTP/1.1" 200 1822 "-" "GNS3 QT Client v2.1.21"

**Comment by grossmj** [comment]
Looks like winpcap is not installed or you need to make sure your have the vmnet interfaces created on your system, especially vmnet8 is used by default for the NAT node on Windows.

**Comment by grossmj** [comment]
@melshman have you tried the above?

**Comment by grossmj** [comment]
@melshman ping
