### ISSUE TITLE
GNS3 server doesn't start, probably vmware related

### ISSUE THREAD

**Issue by icsterm** [GNS3/gns3-server#1653]
After renaming a project using the GNS3 GUI and reopening GNS3, the server fails to start (local server). I suspect it to be vmware related which I use for running VIRL images using QEMU.

Debug log of gns3-server:

```
2019-09-16 01:06:34 DEBUG web_server.py:279 Loading module Builtin
2019-09-16 01:06:34 DEBUG web_server.py:279 Loading module VPCS
2019-09-16 01:06:34 DEBUG web_server.py:279 Loading module VirtualBox
2019-09-16 01:06:34 DEBUG web_server.py:279 Loading module Dynamips
2019-09-16 01:06:34 DEBUG web_server.py:279 Loading module Qemu
2019-09-16 01:06:34 DEBUG web_server.py:279 Loading module VMware
2019-09-16 01:06:34 DEBUG web_server.py:279 Loading module TraceNG
2019-09-16 01:06:34 INFO web_server.py:283 Starting server on 127.0.0.1:3080
2019-09-16 01:06:34 INFO __init__.py:65 Load controller configuration file C:\Users\plm\AppData\Roaming\GNS3\gns3_controller.conf
2019-09-16 01:06:34 INFO __init__.py:168 Start controller
2019-09-16 01:06:34 INFO compute.py:79 Create compute local
2019-09-16 01:06:34 INFO compute.py:420 Connecting to compute 'local'
2019-09-16 01:06:34 DEBUG compute.py:563 Attempting request to compute: GET http://127.0.0.1:3080/v2/compute/capabilities {'content-type': 'application/json'}
2019-09-16 01:06:34 DEBUG base_events.py:780 connect <socket.socket fd=576, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6> to ('127.0.0.1', 3080)
2019-09-16 01:06:34 INFO base_events.py:1086 <Server sockets=[<socket.socket fd=560, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 3080)>]> is serving
2019-09-16 01:06:34 DEBUG base_events.py:1409 poll 500.000 ms took 187.000 ms: 2 events
2019-09-16 01:06:34 DEBUG proactor_events.py:505 <Server sockets=[<socket.socket fd=560, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 3080)>]> got a new connection from ('127.0.0.1', 29988): <socket.socket fd=564, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 3080), raddr=('127.0.0.1', 29988)>
2019-09-16 01:06:34 DEBUG base_events.py:826 <socket.socket fd=576, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 29988), raddr=('127.0.0.1', 3080)> connected to 127.0.0.1:3080: (<_ProactorSocketTransport fd=576 read=<_OverlappedFuture pending overlapped=<pending, 0x518a700> cb=[_ProactorReadPipeTransport._loop_reading()] created at C:\Python36-x64\lib\asyncio\windows_events.py:449>>, <aiohttp.client_proto.ResponseHandler object at 0x0000000004FDE6A0>)
2019-09-16 01:06:34 INFO response.py:56 GET /v2/compute/capabilities
2019-09-16 01:06:34 DEBUG response.py:57 {'content-type': 'application/json', 'Accept': '*/*', 'Accept-Encoding': 'gzip, deflate', 'Host': '127.0.0.1:3080', 'User-Agent': 'Python/3.6 aiohttp/2.3.10', 'Authorization': 'Basic YWRtaW46SFZFeGR3SjlQN2NKSVVDWVFBYWlGNnF2bUcwTm95MU00dDhCZjZ6Y29STEFhRUR6V1VmTVlOTVNJYXBEZXh5dg=='}
2019-09-16 01:06:34 DEBUG response.py:59 {}
2019-09-16 01:06:34 INFO response.py:60 Response: 200 OK
2019-09-16 01:06:34 DEBUG response.py:61 {'Connection': 'close', 'X-Route': '/v2/compute/capabilities', 'Server': 'Python/3.6 GNS3/2.1.21', 'Content-Type': 'application/json'}
2019-09-16 01:06:34 DEBUG response.py:63 {'node_types': ['cloud', 'ethernet_hub', 'ethernet_switch', 'nat', 'vpcs', 'virtualbox', 'dynamips', 'frame_relay_switch', 'atm_switch', 'qemu', 'vmware', 'traceng'], 'platform': 'win32', 'version': '2.1.21'}
2019-09-16 01:06:34 INFO helpers.py:534 127.0.0.1 [15/Sep/2019:22:06:34 +0000] "GET /v2/compute/capabilities HTTP/1.1" 200 519 "-" "Python/3.6 aiohttp/2.3.10"
2019-09-16 01:06:34 DEBUG topology.py:122 Read topology C:\Users\plm\GNS3\projects\STP-LAB\STP-LAB.gns3
2019-09-16 01:06:34 DEBUG topology.py:122 Read topology C:\Users\plm\GNS3\projects\STP-LAB\STP-LAB.gns3
2019-09-16 01:06:34 DEBUG proactor_events.py:222 <_ProactorSocketTransport fd=564> received EOF
2019-09-16 01:06:34 CRITICAL run.py:255 Critical error while running the server: Not Found
Traceback (most recent call last):
  File "./gns3-server\gns3server\controller\__init__.py", line 507, in get_compute
KeyError: 'vm'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./gns3-server\gns3server\run.py", line 249, in run
  File "./gns3-server\gns3server\web\web_server.py", line 286, in run
  File "./gns3-server\gns3server\web\web_server.py", line 85, in _run_application
  File "C:\Python36-x64\lib\asyncio\base_events.py", line 484, in run_until_complete
  File "C:\Python36-x64\lib\site-packages\aiohttp\web.py", line 264, in startup
  File "C:\Python36-x64\lib\site-packages\aiohttp\signals.py", line 51, in send
  File "C:\Python36-x64\lib\site-packages\aiohttp\signals.py", line 17, in _send
  File "./gns3-server\gns3server\web\web_server.py", line 210, in _on_startup
  File "./gns3-server\gns3server\controller\__init__.py", line 203, in start
  File "./gns3-server\gns3server\controller\__init__.py", line 308, in load_projects
  File "./gns3-server\gns3server\controller\__init__.py", line 581, in load_project
  File "./gns3-server\gns3server\utils\asyncio\__init__.py", line 161, in wrapper
  File "./gns3-server\gns3server\controller\project.py", line 883, in open
  File "./gns3-server\gns3server\controller\project.py", line 837, in open
  File "./gns3-server\gns3server\controller\__init__.py", line 510, in get_compute
aiohttp.web_exceptions.HTTPNotFound: Not Found
2019-09-16 01:06:34 DEBUG get_resource.py:39 Clean egg cache T:\TEMP\tmpw4eogv2y
```

gns3_server.ini:

```
[Server]
path = C:\Program Files\GNS3\gns3server.EXE
ubridge_path = C:\Program Files\GNS3\ubridge.EXE
host = 127.0.0.1
port = 3080
images_path = C:\Users\plm\GNS3\images
projects_path = C:\Users\plm\GNS3\projects
appliances_path = C:\Users\plm\GNS3\appliances
additional_images_paths = 
symbols_path = C:\Users\plm\GNS3\symbols
configs_path = C:\Users\plm\GNS3\configs
report_errors = False
auto_start = True
allow_console_from_anywhere = False
auth = False
user = admin
password = HVExdwJ9P7cJIUCYQAaiF6qvmG0Noy1M4t8Bf6zcoRLAaEDzWUfMYNMSIapDexyv
protocol = http
console_start_port_range = 5000
console_end_port_range = 10000
udp_start_port_range = 10000
udp_end_port_range = 20000

[Dynamips]
allocate_aux_console_ports = False
ghost_ios_support = True
sparse_memory_support = True
mmap_support = True
dynamips_path = C:\Program Files\GNS3\dynamips\dynamips.EXE

[VMware]
host_type = ws
vmnet_start_range = 2
vmnet_end_range = 19
block_host_traffic = True
vmrun_path = C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe
```

gns3_controller.conf:

```
{
    "computes": [],
    "settings": {
        "Builtin": {},
        "Docker": {
            "containers": []
        },
        "Dynamips": {
            "allocate_aux_console_ports": false,
            "dynamips_path": "C:\\Program Files\\GNS3\\dynamips\\dynamips.EXE",
            "ghost_ios_support": true,
            "mmap_support": true,
            "routers": [],
            "sparse_memory_support": true
        },
        "GraphicsView": {
            "default_label_color": "#000000",
            "default_label_font": "MS Shell Dlg 2,10,-1,5,75,0,0,0,0,0,Bold",
            "draw_link_status_points": true,
            "draw_rectangle_selected_item": false,
            "grid_size": 75,
            "limit_size_node_symbols": true,
            "scene_height": 1000,
            "scene_width": 2000,
            "show_grid": false,
            "show_interface_labels": false,
            "show_interface_labels_on_new_project": false,
            "show_layers": false,
            "snap_to_grid": false,
            "zoom": null
        },
        "IOU": {
            "devices": [],
            "iourc_content": "[license]\ngns3vm = ;",
            "license_check": true
        },
        "Qemu": {
            "enable_kvm": true,
            "require_kvm": true,
            "vms": [
                {
                    "acpi_shutdown": false,
                    "adapter_type": "e1000",
                    "adapters": 16,
                    "appliance_id": "9b62b77d-ca64-4eb1-aaf5-b898c4cafb92",
                    "bios_image": "",
                    "boot_priority": "c",
                    "category": 0,
                    "cdrom_image": "",
                    "console_type": "telnet",
                    "cpu_throttling": 0,
                    "cpus": 1,
                    "default_name_format": "R{0}",
                    "first_port_name": "",
                    "hda_disk_image": "vios-adventerprisek9-m.vmdk.SPA.156-2.T",
                    "hda_disk_interface": "virtio",
                    "hdb_disk_image": "IOSv_startup_config.img",
                    "hdb_disk_interface": "virtio",
                    "hdc_disk_image": "",
                    "hdc_disk_interface": "ide",
                    "hdd_disk_image": "",
                    "hdd_disk_interface": "ide",
                    "initrd": "",
                    "kernel_command_line": "",
                    "kernel_image": "",
                    "legacy_networking": false,
                    "linked_clone": true,
                    "mac_address": null,
                    "name": "ROUTER",
                    "node_type": "qemu",
                    "options": "-nographic",
                    "platform": "",
                    "port_name_format": "Gi0/{0}",
                    "port_segment_size": 0,
                    "process_priority": "normal",
                    "qemu_path": "/usr/bin/qemu-system-x86_64",
                    "ram": 512,
                    "server": "vm",
                    "symbol": ":/symbols/router.svg",
                    "usage": "There is no default password and enable password. There is no default configuration present."
                },
                {
                    "acpi_shutdown": false,
                    "adapter_type": "e1000",
                    "adapters": 16,
                    "appliance_id": "c5668edc-9060-4398-8a6d-ee0805825752",
                    "bios_image": "",
                    "boot_priority": "c",
                    "category": 1,
                    "cdrom_image": "",
                    "console_type": "telnet",
                    "cpu_throttling": 0,
                    "cpus": 1,
                    "default_name_format": "SW{0}",
                    "first_port_name": "",
                    "hda_disk_image": "vios_l2-adventerprisek9-m.03.2017.qcow2",
                    "hda_disk_interface": "virtio",
                    "hdb_disk_image": "",
                    "hdb_disk_interface": "ide",
                    "hdc_disk_image": "",
                    "hdc_disk_interface": "ide",
                    "hdd_disk_image": "",
                    "hdd_disk_interface": "ide",
                    "initrd": "",
                    "kernel_command_line": "",
                    "kernel_image": "",
                    "legacy_networking": false,
                    "linked_clone": true,
                    "mac_address": null,
                    "name": "SWITCH",
                    "node_type": "qemu",
                    "options": "-nographic",
                    "platform": "",
                    "port_name_format": "Gi{1}/{0}",
                    "port_segment_size": 16,
                    "process_priority": "normal",
                    "qemu_path": "/usr/bin/qemu-system-x86_64",
                    "ram": 768,
                    "server": "vm",
                    "symbol": ":/symbols/multilayer_switch.svg",
                    "usage": "There is no default password and enable password. There is no default configuration present."
                }
            ]
        },
        "VMware": {
            "block_host_traffic": true,
            "host_type": "ws",
            "vmnet_end_range": 19,
            "vmnet_start_range": 2,
            "vmrun_path": "C:\\Program Files (x86)\\VMware\\VMware Workstation\\vmrun.exe",
            "vms": []
        },
        "VPCS": {
            "vpcs_path": ""
        },
        "VirtualBox": {
            "vboxmanage_path": ""
        },
        "modification_uuid": "55e2f3a3-01cb-4387-bcde-bb72c49bbf58"
    },
    "gns3vm": {
        "vmname": "GNS3 VM",
        "when_exit": "keep",
        "headless": true,
        "enable": true,
        "engine": "vmware",
        "ram": 12288,
        "vcpus": 8
    },
    "version": "2.1.21"
}
```

Bug also reported here by other users:
https://www.gns3.com/community/discussion/error-while-getting-compute-li-3

and here:
https://gns3.com/community/discussion/connection-to-the-local-server-f

**Comment by icsterm** [comment]
Found the issue myself.
It seems ticking "leave project running backgroung " option in my project generates this error. Editing the .gns3 file of the project and setting  " "auto_close": true ", instead of false, fixes the issue.

**Comment by grossmj** [comment]
This issue has been fixed a while ago. It should work well in version 2.2. Please comment back if this is not the case.

Thanks.
