### ISSUE TITLE
Exception when exporting debug data

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-server#1684]
```
2019-11-06 21:18:38 ERROR server_handler.py:154 Could not export debug information 'dict' object has no attribute 'id'
Traceback (most recent call last):
  File "./gns3-server\gns3server\handlers\api\controller\server_handler.py", line 151, in debug
  File "./gns3-server\gns3server\handlers\api\controller\server_handler.py", line 223, in _getDebugData
AttributeError: 'dict' object has no attribute 'id'
```

**Comment by grossmj** [comment]
Fixed.
