### ISSUE TITLE
gns3server cannot start Virtualbox instance

### ISSUE THREAD

**Issue by GunstarCowboy** [GNS3/gns3-server#1687]
*GNS3 v2.2.2 on Linux (Ubuntu 18) will not start a Virtualbox instance, failing with the error:*

**Error while creating node from template: Internal server error http://127.0.0.1:3080/v2/compute/projects/063e144d-edbe-4119-a755-5c915037798b/virtualbox/nodes**

*DEBUG-level output from gns3server instance:*

2019-11-08 13:43:57 DEBUG base_node.py:112 VirtualBox: Lubuntu-1 [aee7a391-09ac-4a3a-8ba8-bb92ca414c7a] initialized. Console port None
2019-11-08 13:43:57 INFO __init__.py:112 Executing VBoxManage with command: /usr/bin/VBoxManage --nologo list systemproperties
2019-11-08 13:43:57 INFO virtualbox_vm.py:196 VirtualBox VM 'Lubuntu-1' [aee7a391-09ac-4a3a-8ba8-bb92ca414c7a] created
2019-11-08 13:43:57 INFO __init__.py:112 Executing VBoxManage with command: /usr/bin/VBoxManage --nologo showvminfo --machinereadable -- Lubuntu
2019-11-08 13:43:57 INFO virtualbox_vm.py:683 VirtualBox VM 'Lubuntu-1' [aee7a391-09ac-4a3a-8ba8-bb92ca414c7a] can have a maximum of 8 network adapters for chipset PIIX3
2019-11-08 13:43:57 INFO virtualbox_vm.py:695 VirtualBox VM 'Lubuntu-1' [aee7a391-09ac-4a3a-8ba8-bb92ca414c7a] has changed the number of Ethernet adapters to 1
2019-11-08 13:43:57 ERROR route.py:236 Uncaught exception detected: <class 'TypeError'>
Traceback (most recent call last):
  File "/usr/share/gns3/gns3-server/lib/python3.6/site-packages/gns3server/web/route.py", line 196, in control_schema
    await func(request, response)
  File "/usr/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
    return self.gen.send(None)
  File "/usr/share/gns3/gns3-server/lib/python3.6/site-packages/gns3server/handlers/api/compute/virtualbox_handler.py", line 68, in create
    await vm.set_ram(ram)
  File "/usr/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
    return self.gen.send(None)
  File "/usr/share/gns3/gns3-server/lib/python3.6/site-packages/gns3server/compute/virtualbox/virtualbox_vm.py", line 611, in set_ram
    await self._modify_vm('--memory {}'.format(ram))
  File "/usr/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
    return self.gen.send(None)
  File "/usr/share/gns3/gns3-server/lib/python3.6/site-packages/gns3server/compute/virtualbox/virtualbox_vm.py", line 149, in _modify_vm
    await self.manager.execute("modifyvm", [self._uuid] + args)
  File "/usr/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
    return self.gen.send(None)
  File "/usr/share/gns3/gns3-server/lib/python3.6/site-packages/gns3server/compute/virtualbox/__init__.py", line 111, in execute
    command_string = " ".join(command)
TypeError: sequence item 3: expected str instance, NoneType found

**Comment by grossmj** [comment]
This should have been fixed already: https://github.com/GNS3/gns3-server/issues/1685

Thanks :)
