### ISSUE TITLE
Cannot start gns3server 2.2.8

### ISSUE THREAD

**Issue by squeeb** [GNS3/gns3-server#1750]
```
May 07 20:08:46 gns3.parksq.crigby.net gns3server[27941]: Traceback (most recent call last):
May 07 20:08:46 gns3.parksq.crigby.net gns3server[27941]:   File "/usr/local/bin/gns3server", line 11, in <module>
May 07 20:08:46 gns3.parksq.crigby.net gns3server[27941]:     load_entry_point('gns3-server==2.2.8', 'console_scripts', 'gns3server')()
May 07 20:08:46 gns3.parksq.crigby.net gns3server[27941]:   File "/usr/local/lib/python3.6/dist-packages/gns3_server-2.2.8-py3.6.egg/gns3server/main.py", line 82, in main
May 07 20:08:46 gns3.parksq.crigby.net gns3server[27941]:     from gns3server.run import run
May 07 20:08:46 gns3.parksq.crigby.net gns3server[27941]:   File "/usr/local/lib/python3.6/dist-packages/gns3_server-2.2.8-py3.6.egg/gns3server/run.py", line 32, in <module>
May 07 20:08:46 gns3.parksq.crigby.net gns3server[27941]:     from gns3server.web.web_server import WebServer
May 07 20:08:46 gns3.parksq.crigby.net gns3server[27941]:   File "/usr/local/lib/python3.6/dist-packages/gns3_server-2.2.8-py3.6.egg/gns3server/web/web_server.py", line 45, in <module>
May 07 20:08:46 gns3.parksq.crigby.net gns3server[27941]:     import gns3server.handlers
May 07 20:08:46 gns3.parksq.crigby.net gns3server[27941]:   File "/usr/local/lib/python3.6/dist-packages/gns3_server-2.2.8-py3.6.egg/gns3server/handlers/__init__.py", line 22, in <module>
May 07 20:08:46 gns3.parksq.crigby.net gns3server[27941]:     from gns3server.handlers.api.compute import *
May 07 20:08:46 gns3.parksq.crigby.net gns3server[27941]:   File "/usr/local/lib/python3.6/dist-packages/gns3_server-2.2.8-py3.6.egg/gns3server/handlers/api/compute/__init__.py", line 29, in <module>
May 07 20:08:46 gns3.parksq.crigby.net gns3server[27941]:     from .server_handler import ServerHandler
May 07 20:08:46 gns3.parksq.crigby.net gns3server[27941]:   File "/usr/local/lib/python3.6/dist-packages/gns3_server-2.2.8-py3.6.egg/gns3server/handlers/api/compute/server_handler.py", line 29, in <module>
May 07 20:08:46 gns3.parksq.crigby.net gns3server[27941]:     from psutil._common import bytes2human
May 07 20:08:46 gns3.parksq.crigby.net gns3server[27941]: ImportError: cannot import name 'bytes2human'
```

**Comment by grossmj** [comment]
How have you installed gns3server?

**Comment by squeeb** [comment]
Yes, however - I managed to resolve it by using pip to upgrade the version of psutil to the latest available for Python 3.6.

**Comment by squeeb** [comment]
Whoops, misread.. I downloaded the source and ran `python3 setup.py install`

**Comment by grossmj** [comment]
Ok, all good then :+1:
