### ISSUE TITLE
REST API odd behavior

### ISSUE THREAD

**Issue by vint66** [GNS3/gns3-server#1754]
GNS3 v2.2.8 running on remote Ubuntu 18.04.

My intention is to change project attributes (example below changing name, taken form gns3 doc):

curl -i -X PUT 'http://localhost:3080/v2/projects/10010203-0405-0607-0809-0a0b0c0d0e0f' -d '{"name": "test2"}'

However it is not changing project name and is returning error below.

2020-05-09 10:22:10 ERROR route.py:242 Uncaught exception detected: <class 'AttributeError'>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/gns3server/web/route.py", line 198, in control_schema
    await func(request, response)
  File "/usr/local/lib/python3.6/dist-packages/gns3server/handlers/api/controller/project_handler.py", line 116, in update
    await project.update(**request.json)
  File "/usr/local/lib/python3.6/dist-packages/gns3server/controller/project.py", line 158, in update
    self.dump()
  File "/usr/local/lib/python3.6/dist-packages/gns3server/controller/project.py", line 1059, in dump
    topo = project_to_topology(self)
  File "/usr/local/lib/python3.6/dist-packages/gns3server/controller/topology.py", line 104, in project_to_topology
    computes.add(node.compute)
AttributeError: 'dict' object has no attribute 'compute'
2020-05-09 10:22:10 INFO web_log.py:233 127.0.0.1 [09/May/2020:17:22:10 +0000] "PUT /v2/projects/70271b36-15d2-4a52-b3ac-5afa33a3aa36 HTTP/1.1" 500 1070 "-" "curl/7.58.0"

What is odd that project name in project list (in GUI) was changed but actual project name in file (.gns3) was not and will restore original name after server restarts.
However if I open this project right after api call it will apply name to the .gns3 file.

Seems like issue with API for closed projects.

**Comment by grossmj** [comment]
Should be fixed now. Thanks :+1:
