### ISSUE TITLE
Adding Chromium appliance results in an "asyncio.exceptions.TimeoutError"

### ISSUE THREAD

**Issue by quantumpacket** [GNS3/gns3-server#1761]
**GNS3:** 2.2.8
**Docker:** 19.03.9
**OS:** Kali x64

I can install the Chromium appliance and it installs without error. However, when I drag the appliance into my project GNS3 produces these errors:

**gns3-gui**
```
2020-05-21 14:13:12 DEBUG http_client:534 POST http://localhost:3080/v2/projects/79afc5e3-0292-4b6a-bcd9-e6d24e396adb/templates/99028e46-926f-40e2-a50c-e15fc1cfd741{'x': -349, 'y': -345}
2020-05-21 14:13:22 DEBUG http_client:646 Response error: Error transferring http://admin@localhost:3080/v2/projects/79afc5e3-0292-4b6a-bcd9-e6d24e396adb/templates/99028e46-926f-40e2-a50c-e15fc1cfd741 - server replied: Internal Server Error (localhost:3080) for http://admin@localhost:3080/v2/projects/79afc5e3-0292-4b6a-bcd9-e6d24e396adb/templates/99028e46-926f-40e2-a50c-e15fc1cfd741 (error: 401)
2020-05-21 14:13:22 ERROR template_manager:226 Error while creating node from template: Internal server error http://localhost:3080/v2/compute/projects/79afc5e3-0292-4b6a-bcd9-e6d24e396adb/docker/nodes
```

**gns3server**
```
2020-05-21 14:39:08 ERROR route.py:242 Uncaught exception detected: <class 'asyncio.exceptions.TimeoutError'>
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.8/site-packages/gns3server/web/route.py", line 198, in control_schema
    await func(request, response)
  File "/home/user/.local/lib/python3.8/site-packages/gns3server/handlers/api/compute/docker_handler.py", line 51, in create
    container = await docker_manager.create_node(request.json.pop("name"),
  File "/home/user/.local/lib/python3.8/site-packages/gns3server/compute/base_manager.py", line 259, in create_node
    await node.create()
  File "/home/user/.local/lib/python3.8/site-packages/gns3server/compute/docker/docker_vm.py", line 394, in create
    await self._start_vnc()
  File "/home/user/.local/lib/python3.8/site-packages/gns3server/compute/docker/docker_vm.py", line 618, in _start_vnc
    await wait_for_file_creation(x11_socket)
  File "/home/user/.local/lib/python3.8/site-packages/gns3server/utils/asyncio/__init__.py", line 136, in wait_for_file_creation
    raise asyncio.TimeoutError()
asyncio.exceptions.TimeoutError
```

GNS3 was installed using the Debian buster [install instructions](https://docs.gns3.com/1QXVIihk7dsOL7Xr7Bmz4zRzTsJ02wklfImGuHwTlaA4/index.html#h.t4o6ollwqq07) from the documentation. Let me know if you need me to provide additional info.

**Comment by grossmj** [comment]
Do you only have this issue with the Chromium appliance?

**Comment by quantumpacket** [comment]
@grossmj yes, it's the only appliance that causes it. I have 2 other Docker container templates and they both work fine. Docker status is up and running with no reported issues.

**Comment by grossmj** [comment]
I couldn't reproduce the problem. However, I have increased the timeout from 10 to 60 seconds and provided more information in case there is an error. Let's see if this solves the problem after we release version 2.2.10

**Comment by grossmj** [comment]
@quantumpacket have you been able to try with the latest release?

**Comment by quantumpacket** [comment]
@grossmj It seems to get weirder each time. Installed v2.2.11, and both available Chromium appliances. When I drag/drop both to the work area they don't show up, but it appears it tries to. Because some timeout eventually occurs, and the following error appears in the Console:

> Error while creating node from template: x11 socket file "/tmp/.X11-unix/X100" does not exist

Docker is running as I am able to successfully drag/drop other Docker based appliances. I'll post a debug log as soon as I can.

**Comment by quantumpacket** [comment]
Looks to be Docker related. Maybe the appliance is not compatible with the Docker version?

**Docker:** 19.03.12, build 48a66213fe

**GNS3 GUI**
```
2020-07-18 13:34:05 DEBUG http_client:534 POST http://localhost:3080/v2/projects/e08b0460-e95d-42a0-8864-46aed65f96bd/templates/fd67422f-eb84-42aa-895d-7067870064c1 {'x': -95, 'y': -142}
2020-07-18 13:35:06 DEBUG http_client:646 Response error: Error transferring http://admin@localhost:3080/v2/projects/e08b0460-e95d-42a0-8864-46aed65f96bd/templates/fd67422f-eb84-42aa-895d-7067870064c1 - server replied: Conflict (localhost:3080) for http://admin@localhost:3080/v2/projects/e08b0460-e95d-42a0-8864-46aed65f96bd/templates/fd67422f-eb84-42aa-895d-7067870064c1 (error: 206)
2020-07-18 13:35:06 ERROR template_manager:226 Error while creating node from template: x11 socket file "/tmp/.X11-unix/X100" does not exist
```

**GNS3 Server**
```
2020-07-18 13:34:05 DEBUG compute.py:509 Attempting request to compute: POST http://localhost:3080/v2/compute/projects {'content-type': 'application/json'}
2020-07-18 13:34:05 INFO project.py:78 Project e08b0460-e95d-42a0-8864-46aed65f96bd with path '/X/untitled' created
2020-07-18 13:34:05 INFO response.py:58 POST /v2/compute/projects
2020-07-18 13:34:05 DEBUG response.py:59 {'Host': 'localhost:3080', 'Content-Type': 'application/json', 'Accept': '*/*', 'Accept-Encoding': 'gzip, deflate', 'User-Agent': 'Python/3.8 aiohttp/3.6.2', 'Authorization': 'Basic YWRtaW46MDF1N2NkMFNyRXNwV210RXJoTzE3ZHA4dGxsSE41UzU4R0c2d1Y2OTN0R2UwQ1E5WGhmdFlsRDkzMW5JSko4cA==', 'Content-Length': '116'}
2020-07-18 13:34:05 DEBUG response.py:61 {'name': 'untitled', 'project_id': 'e08b0460-e95d-42a0-8864-46aed65f96bd', 'path': '/X/untitled'}
2020-07-18 13:34:05 INFO response.py:62 Response: 201 Created
2020-07-18 13:34:05 DEBUG response.py:63 {'Connection': 'close', 'X-Route': '/v2/compute/projects', 'Server': 'Python/3.8 GNS3/2.2.11', 'Content-Type': 'application/json'}
2020-07-18 13:34:05 DEBUG response.py:65 {'name': 'untitled', 'project_id': 'e08b0460-e95d-42a0-8864-46aed65f96bd', 'variables': None}
2020-07-18 13:34:05 INFO web_log.py:233 ::1 [18/Jul/2020:17:34:05 +0000] "POST /v2/compute/projects HTTP/1.1" 201 303 "-" "Python/3.8 aiohttp/3.6.2"
2020-07-18 13:34:05 DEBUG compute.py:509 Attempting request to compute: POST http://localhost:3080/v2/compute/projects/e08b0460-e95d-42a0-8864-46aed65f96bd/docker/nodes {'content-type': 'application/json'}
2020-07-18 13:34:05 DEBUG port_manager.py:215 TCP port 5900 has been allocated
2020-07-18 13:34:05 DEBUG port_manager.py:215 TCP port 5000 has been allocated
2020-07-18 13:34:05 DEBUG base_node.py:110 Docker: Chromium-1 [939a942d-a82a-497d-a682-dcad6b618e5d] initialized. Console port 5900
2020-07-18 13:34:05 INFO docker_vm.py:1058 Docker container "Chromium-1" [939a942d-a82a-497d-a682-dcad6b618e5d]: number of Ethernet adapters changed to 1
2020-07-18 13:34:05 DEBUG docker_vm.py:110 Docker: Chromium-1 [gns3/chromium:latest] initialized.
2020-07-18 13:34:06 DEBUG __init__.py:118 Query Docker GET version params={} data={} Response: {'Platform': {'Name': 'Docker Engine - Community'}, 'Components': [{'Name': 'Engine', 'Version': '19.03.12', 'Details': {'ApiVersion': '1.40', 'Arch': 'amd64', 'BuildTime': '2020-06-22T15:44:21.000000000+00:00', 'Experimental': 'false', 'GitCommit': '48a66213fe', 'GoVersion': 'go1.13.10', 'KernelVersion': '5.6.0-kali2-amd64', 'MinAPIVersion': '1.12', 'Os': 'linux'}}, {'Name': 'containerd', 'Version': '1.2.13', 'Details': {'GitCommit': '7ad184331fa3e55e52b890ea95e65ba581ae3429'}}, {'Name': 'runc', 'Version': '1.0.0-rc10', 'Details': {'GitCommit': 'dc9208a3303feef5b3839f4323d9beb36df0a9dd'}}, {'Name': 'docker-init', 'Version': '0.18.0', 'Details': {'GitCommit': 'fec3683'}}], 'Version': '19.03.12', 'ApiVersion': '1.40', 'MinAPIVersion': '1.12', 'GitCommit': '48a66213fe', 'GoVersion': 'go1.13.10', 'Os': 'linux', 'Arch': 'amd64', 'KernelVersion': '5.6.0-kali2-amd64', 'BuildTime': '2020-06-22T15:44:21.000000000+00:00'}
2020-07-18 13:34:06 DEBUG __init__.py:118 Query Docker GET images/gns3/chromium:latest/json params={} data={} Response: {'Id': 'sha256:0e7a333aff85e405f60d125837458961f9e6238fe619c983495d7bca5120c3f1', 'RepoTags': ['gns3/chromium:latest'], 'RepoDigests': ['gns3/chromium@sha256:6cbaa28ef2fc837a56d25715d55ad1fff777bc01c6894ac5c90c4fc1da63db9f'], 'Parent': '', 'Comment': '', 'Created': '2019-01-23T15:14:27.528600653Z', 'Container': '631a9040978650b0205ce600f5091d53c4d182e4f017316df37dd407c6ba4456', 'ContainerConfig': {'Hostname': '631a90409786', 'Domainname': '', 'User': 'chromium', 'AttachStdin': False, 'AttachStdout': False, 'AttachStderr': False, 'Tty': False, 'OpenStdin': False, 'StdinOnce': False, 'Env': ['PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'], 'Cmd': ['/bin/sh', '-c', '#(nop) ', 'VOLUME [/data]'], 'ArgsEscaped': True, 'Image': 'sha256:a23111f3f7b51c6febbad0826fd40b299e58ed6ec231ba2cee17acf66ef948d9', 'Volumes': {'/data': {}}, 'WorkingDir': '', 'Entrypoint': ['/usr/bin/chromium'], 'OnBuild': None, 'Labels': {'maintainer': 'Jessie Frazelle <jess@linux.com>'}}, 'DockerVersion': '18.03.1-ee-3', 'Author': 'developers@gns3.net', 'Config': {'Hostname': '', 'Domainname': '', 'User': 'chromium', 'AttachStdin': False, 'AttachStdout': False, 'AttachStderr': False, 'Tty': False, 'OpenStdin': False, 'StdinOnce': False, 'Env': ['PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'], 'Cmd': ['--user-data-dir=/data'], 'ArgsEscaped': True, 'Image': 'sha256:a23111f3f7b51c6febbad0826fd40b299e58ed6ec231ba2cee17acf66ef948d9', 'Volumes': {'/data': {}}, 'WorkingDir': '', 'Entrypoint': ['/usr/bin/chromium'], 'OnBuild': None, 'Labels': {'maintainer': 'Jessie Frazelle <jess@linux.com>'}}, 'Architecture': 'amd64', 'Os': 'linux', 'Size': 654628448, 'VirtualSize': 654628448, 'GraphDriver': {'Data': {'LowerDir': '/var/lib/docker/overlay2/e90a762ad5373999c53f0928551bd06aa0c83f67efab24ac41777afd42f91b79/diff:/var/lib/docker/overlay2/d1c22a976c17f0a1ef2a681e350116b435b7d5b4a9879489622afe114c6a2402/diff:/var/lib/docker/overlay2/fc9cf82f5841dde509bc41521ed9f9c3e9c0e82cda956679d0092d362d600540/diff', 'MergedDir': '/var/lib/docker/overlay2/b0b5ab7fe6aca7aa69de974520eb723c04cf9e31bd86afb6facfd93d88bf7734/merged', 'UpperDir': '/var/lib/docker/overlay2/b0b5ab7fe6aca7aa69de974520eb723c04cf9e31bd86afb6facfd93d88bf7734/diff', 'WorkDir': '/var/lib/docker/overlay2/b0b5ab7fe6aca7aa69de974520eb723c04cf9e31bd86afb6facfd93d88bf7734/work'}, 'Name': 'overlay2'}, 'RootFS': {'Type': 'layers', 'Layers': ['sha256:f9e3dfea6554a8747c023f0a58d8d883567c583a13a6330f12f67b6b72e96ee8', 'sha256:e960585c6369cdbf0890a28d2a87078d5945ea03413de24b46e3d488d6347a51', 'sha256:11249b1708cdbba4f6c10b92f7263fc1c05c9f69572d7991be115c85039acceb', 'sha256:b37fc9a0fcc8db4759095bdbc54076c52d60e7243848ef60da44a14b677d9f84']}, 'Metadata': {'LastTagTime': '0001-01-01T00:00:00Z'}}
2020-07-18 13:35:06 ERROR route.py:217 Node error detected: DockerError
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.8/site-packages/gns3server/compute/docker/docker_vm.py", line 619, in _start_vnc
    await wait_for_file_creation(x11_socket)
  File "/home/user/.local/lib/python3.8/site-packages/gns3server/utils/asyncio/__init__.py", line 136, in wait_for_file_creation
    raise asyncio.TimeoutError()
asyncio.exceptions.TimeoutError
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.8/site-packages/gns3server/web/route.py", line 198, in control_schema
    await func(request, response)
  File "/home/user/.local/lib/python3.8/site-packages/gns3server/handlers/api/compute/docker_handler.py", line 51, in create
    container = await docker_manager.create_node(request.json.pop("name"),
  File "/home/user/.local/lib/python3.8/site-packages/gns3server/compute/base_manager.py", line 259, in create_node
    await node.create()
  File "/home/user/.local/lib/python3.8/site-packages/gns3server/compute/docker/docker_vm.py", line 394, in create
    await self._start_vnc()
  File "/home/user/.local/lib/python3.8/site-packages/gns3server/compute/docker/docker_vm.py", line 621, in _start_vnc
    raise DockerError('x11 socket file "{}" does not exist'.format(x11_socket))
gns3server.compute.docker.docker_error.DockerError: x11 socket file "/tmp/.X11-unix/X100" does not exist
2020-07-18 13:35:06 INFO response.py:58 POST /v2/compute/projects/e08b0460-e95d-42a0-8864-46aed65f96bd/docker/nodes
2020-07-18 13:35:06 DEBUG response.py:59 {'Host': 'localhost:3080', 'Content-Type': 'application/json', 'Accept': '*/*', 'Accept-Encoding': 'gzip, deflate', 'User-Agent': 'Python/3.8 aiohttp/3.6.2', 'Authorization': 'Basic YWRtaW46MDF1N2NkMFNyRXNwV210RXJoTzE3ZHA4dGxsSE41UzU4R0c2d1Y2OTN0R2UwQ1E5WGhmdFlsRDkzMW5JSko4cA==', 'Content-Length': '250'}
2020-07-18 13:35:06 DEBUG response.py:61 {'adapters': 1, 'console_http_port': 80, 'console_http_path': '/', 'console_resolution': '1024x768', 'extra_volumes': [], 'console_type': 'vnc', 'node_id': '939a942d-a82a-497d-a682-dcad6b618e5d'}
2020-07-18 13:35:06 INFO response.py:62 Response: 409 Conflict
2020-07-18 13:35:06 DEBUG response.py:63 {'Connection': 'close', 'X-Route': '/v2/compute/projects/{project_id}/docker/nodes', 'Server': 'Python/3.8 GNS3/2.2.11', 'Content-Type': 'application/json'}
2020-07-18 13:35:06 DEBUG response.py:65 {'exception': 'DockerError', 'message': 'x11 socket file "/tmp/.X11-unix/X100" does not exist', 'status': 409}
2020-07-18 13:35:06 INFO web_log.py:233 127.0.0.1 [18/Jul/2020:17:34:05 +0000] "POST /v2/compute/projects/e08b0460-e95d-42a0-8864-46aed65f96bd/docker/nodes HTTP/1.1" 409 349 "-" "Python/3.8 aiohttp/3.6.2"
2020-07-18 13:35:06 INFO response.py:58 POST /v2/projects/e08b0460-e95d-42a0-8864-46aed65f96bd/templates/fd67422f-eb84-42aa-895d-7067870064c1
2020-07-18 13:35:06 DEBUG response.py:59 {'Host': 'localhost:3080', 'Authorization': 'Basic YWRtaW46MDF1N2NkMFNyRXNwV210RXJoTzE3ZHA4dGxsSE41UzU4R0c2d1Y2OTN0R2UwQ1E5WGhmdFlsRDkzMW5JSko4cA==', 'User-Agent': 'GNS3 QT Client v2.2.11', 'Content-Type': 'application/json', 'Content-Length': '21', 'Connection': 'Keep-Alive', 'Accept-Encoding': 'gzip, deflate', 'Accept-Language': 'en-US,*'}
2020-07-18 13:35:06 DEBUG response.py:61 {'x': -95, 'y': -142}
2020-07-18 13:35:06 INFO response.py:62 Response: 409 Conflict
2020-07-18 13:35:06 DEBUG response.py:63 {'Connection': 'close', 'X-Route': '/v2/projects/{project_id}/templates/{template_id}', 'Server': 'Python/3.8 GNS3/2.2.11', 'Content-Type': 'application/json'}
2020-07-18 13:35:06 DEBUG response.py:65 {'message': 'x11 socket file "/tmp/.X11-unix/X100" does not exist', 'status': 409}
2020-07-18 13:35:06 INFO web_log.py:233 ::1 [18/Jul/2020:17:34:05 +0000] "POST /v2/projects/e08b0460-e95d-42a0-8864-46aed65f96bd/templates/fd67422f-eb84-42aa-895d-7067870064c1 HTTP/1.1" 409 319 "-" "GNS3 QT Client v2.2.11"
```

**Comment by cristian-ciobanu** [comment]
I'm experiencing the same exception when trying to drag a Docker container on the topology. I does happen with any Docker container. I also restarted docker service and the same exception is thrown.

Running GNS3 server version 2.2.33.1 on Ubuntu 22.04 Python 3.10

```
2022-09-02 08:08:45 INFO docker_vm.py:1078 Docker container "Ostinato-1" [dcbc36b7-46ce-461a-bc50-5c8e0a9ddbd4]: number of Ethernet adapters changed to 2
2022-09-02 08:09:30 ERROR route.py:217 Node error detected: DockerError
Traceback (most recent call last):
  File "/usr/share/gns3/gns3-server/lib/python3.10/site-packages/gns3server/compute/docker/docker_vm.py", line 632, in _start_vnc
    await wait_for_file_creation(x11_socket)
  File "/usr/share/gns3/gns3-server/lib/python3.10/site-packages/gns3server/utils/asyncio/__init__.py", line 136, in wait_for_file_creation
    raise asyncio.TimeoutError()
asyncio.exceptions.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/gns3/gns3-server/lib/python3.10/site-packages/gns3server/web/route.py", line 198, in control_schema
    await func(request, response)
  File "/usr/share/gns3/gns3-server/lib/python3.10/site-packages/gns3server/handlers/api/compute/docker_handler.py", line 51, in create
    container = await docker_manager.create_node(request.json.pop("name"),
  File "/usr/share/gns3/gns3-server/lib/python3.10/site-packages/gns3server/compute/base_manager.py", line 259, in create_node
    await node.create()
  File "/usr/share/gns3/gns3-server/lib/python3.10/site-packages/gns3server/compute/docker/docker_vm.py", line 404, in create
    await self._start_vnc()
  File "/usr/share/gns3/gns3-server/lib/python3.10/site-packages/gns3server/compute/docker/docker_vm.py", line 634, in _start_vnc
    raise DockerError('x11 socket file "{}" does not exist'.format(x11_socket))
gns3server.compute.docker.docker_error.DockerError: x11 socket file "/tmp/.X11-unix/X126" does not exist
2022-09-02 08:09:30 INFO web_log.py:206 127.0.0.1 [02/Sep/2022:08:08:30 +0000] "POST /v2/compute/projects/43c7a6d0-3c08-4a94-a118-b5a22cd5d02d/docker/nodes HTTP/1.1" 409 350 "-" "Python/3.10 aiohttp/3.8.1"
```
