### ISSUE TITLE
Error when exiting with Ctrl+C

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-server#177]
```
2015-05-05 11:02:53 WARNING server.py:106 Server has got signal SIGINT, exiting...
Exception ignored in: <bound method _UnixSelectorEventLoop.__del__ of <_UnixSelectorEventLoop running=False closed=True debug=False>>
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/asyncio/base_events.py", line 361, in __del__
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/asyncio/unix_events.py", line 57, in close
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/asyncio/unix_events.py", line 138, in remove_signal_handler
TypeError: signal handler must be signal.SIG_IGN, signal.SIG_DFL, or a callable object
```

**Comment by noplay** [comment]
It's only on OSX...

**Comment by noplay** [comment]
It's a Python issue:
http://bugs.python.org/issue23548

We need to ensure it's closed
