### ISSUE TITLE
Cannot start gns3server 2.2.10

### ISSUE THREAD

**Issue by jean-christophe-manciot** [GNS3/gns3-server#1785]
Debian bullseye 11.0
gns3-server 2.2.10
python3 3.8.2-3

```
gns3server --debug
Traceback (most recent call last):
  File "/usr/bin/gns3server", line 34, in <module>
    sys.exit(load_entry_point('gns3-server==2.2.10', 'console_scripts', 'gns3server')())
  File "/usr/bin/gns3server", line 23, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/lib/python3.8/importlib/metadata.py", line 504, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.8/importlib/metadata.py", line 177, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: gns3-server
```
No such issue with 2.2.9.

**Comment by grossmj** [comment]
How have you installed GNS3?

**Comment by jean-christophe-manciot** [comment]
BTW, I encounter the same issue when building on Ubuntu focal (20.04).

I've been building all my gns3 deb packages from sources for years; with the server, it goes mostly like this as root in a bash script (some details are spared):
```
package=gns3-server
python3_version=$($(which python3) --version | cut -d ' ' -f 2 | sed -E 's|([0-9]\.[0-9]).*|\1|g')

pip3 install -r requirements.txt
pip3 install -r dev-requirements.txt
install -vm644 init/gns3.service.systemd ../${package}-build/lib/systemd/system/gns3.service
sed -Ei 's|/var/run|/run|g' ../${package}-build/lib/systemd/system/gns3.service
chown root: ../${package}-build/lib/systemd/system/gns3.service
install -vm644 requirements.txt ../${package}-build//usr/lib/python${python3_version}/site-packages/${package}-requirements.txt

python${python3_version} setup.py install --prefix="../${package}-build/usr"

# Removing unneeded scripts/binaries
# delivered by pip3 packages or other apt packages
for file in ../${package}-build/usr/bin/chardetect ../${package}-build/usr/bin/cpuinfo ../${package}-build/usr/bin/distro ../${package}-build/usr/bin/easy_install ../${package}-build/usr/bin/easy_install-${python3_version} ../${package}-build/usr/bin/jsonschema ../${package}-build/usr/bin/raven ../${package}-build/usr/lib/python${python3_version}/site-packages/easy-install.pth ../${package}-build/usr/lib/python${python3_version}/site-packages/setuptools.pth
do
        rm -v "$file"
done

# Workarounds to issue #1753
sed -Ei 's|/usr/local|/usr|g' ../${package}-build/lib/systemd/system/gns3.service
for file in ../${package}-build/usr/bin/*
do
        sed -i "/import sys/a sys.path.append('/usr/lib/python3.8/site-packages')" "$file"
done
```
Then the package is built from ../${package}-build with fpm.

You can check them out from [here for Ubuntu focal](https://git.sdxlive.com/PPA/tree/Ubuntu/pool/stable/g/gns3-server) (2.2.10 built) or [here for Debian bullseye](https://git.sdxlive.com/DR/tree/Debian/pool/stable/g/gns3-server) (2.2.10 not built).

**Comment by jean-christophe-manciot** [comment]
@grossmj 
My bad:
I modified this:
```
python${python3_version} setup.py install --prefix="../${package}-build/usr"
```
to:
```
python${python3_version} setup.py install --root="../${package}-build" --install-layout=deb --single-version-externally-managed 
```
and now the server starts without any issue.

This also means that issue #1753 is solved.
