### ISSUE TITLE
"Internal server error" when editing a project

### ISSUE THREAD

**Issue by candlerb** [GNS3/gns3-server#1825]
I get "Internal Server Error" when editing project settings immediately after restoring a project from snapshot. After re-opening the project, the settings changes have been applied - so this is really just a minor nuisance.  However there's a backtrace, so it should be fixable.

**GNS3 version and operating system**
 - OS: macOS 10.14.6 (for gns3-gui)
 - GNS3 version 2.2.14
 - gns3-server running on remote Linux server, bare metal Ubuntu 18.04

**To Reproduce**
1. Go to `Edit > Manage Snapshots` and restore from a snapshot
2. Go to `File > Manage Project`
3. Check "Leave this project running in the background when closing GNS3", and click "OK"

**Screenshots or videos**
![image](https://user-images.githubusercontent.com/44789/94988959-0d6ec400-0569-11eb-9e31-e586d0a75bdf.png)

Running `journalctl --follow ...` I see the following backtrace when the error occurs:

```
Oct 03 11:09:56 brian-kit systemd-journald[532]: Suppressed 362 messages from gns3@nsrc.service
Oct 03 11:09:56 brian-kit gns3server[21661]: 2020-10-03 11:09:56 ERROR route.py:242 Uncaught exception detected: <class 'TypeError'>
Oct 03 11:09:56 brian-kit gns3server[21661]: Traceback (most recent call last):
Oct 03 11:09:56 brian-kit gns3server[21661]:   File "/usr/share/gns3/gns3-server/lib/python3.6/site-packages/gns3server/web/route.py", line 198, in control_schema
Oct 03 11:09:56 brian-kit gns3server[21661]:     await func(request, response)
Oct 03 11:09:56 brian-kit gns3server[21661]:   File "/usr/share/gns3/gns3-server/lib/python3.6/site-packages/gns3server/handlers/api/compute/project_handler.py", line 99, in update_project
Oct 03 11:09:56 brian-kit gns3server[21661]:     variables=request.json.get("variables", None)
Oct 03 11:09:56 brian-kit gns3server[21661]:   File "/usr/share/gns3/gns3-server/lib/python3.6/site-packages/gns3server/compute/project.py", line 305, in update
Oct 03 11:09:56 brian-kit gns3server[21661]:     await node.update()
Oct 03 11:09:56 brian-kit gns3server[21661]: TypeError: update() missing 2 required positional arguments: 'name' and 'value'
Oct 03 11:09:56 brian-kit gns3server[21661]: 2020-10-03 11:09:56 INFO web_log.py:233 127.0.0.1 [03/Oct/2020:10:09:56 +0000] "PUT /v2/compute/projects/dd17577a-a39a-4d2b-b765-f76a736018cc HTTP/1.1" 500 880 "-" "Python/3.6 aiohttp/3.6.2"
Oct 03 11:09:56 brian-kit gns3server[21661]: 2020-10-03 11:09:56 INFO web_log.py:233 10.12.0.101 [03/Oct/2020:10:09:56 +0000] "PUT /v2/projects/dd17577a-a39a-4d2b-b765-f76a736018cc HTTP/1.1" 500 355 "-" "GNS3 QT Client v2.2.14"
Oct 03 11:09:56 brian-kit gns3server[21661]: 2020-10-03 11:09:56 INFO project_handler.py:280 Client has disconnected from notification stream for project ID 'dd17577a-a39a-4d2b-b765-f76a736018cc' (WebSocket method)
Oct 03 11:09:56 brian-kit gns3server[21661]: 2020-10-03 11:09:56 INFO web_log.py:233 10.12.0.101 [03/Oct/2020:10:09:56 +0000] "GET /v2/computes HTTP/1.1" 200 1021 "-" "GNS3 QT Client v2.2.14"
Oct 03 11:10:30 brian-kit gns3server[21661]: 2020-10-03 11:10:30 INFO web_log.py:233 10.12.0.101 [03/Oct/2020:10:10:30 +0000] "GET /v2/computes HTTP/1.1" 200 1021 "-" "GNS3 QT Client v2.2.14"
```

This referenced source line is [here](https://github.com/GNS3/gns3-server/blob/master/gns3server/compute/project.py#L305).

**Additional info**

The project has qemu and NAT nodes:

```
$ grep node_type project.gns3  | sort | uniq -c
      8                 "node_type": "nat",
     56                 "node_type": "qemu",
$ 
```

I was surprised to see `http://127.0.0.1/...` in the error, since the GNS3 GUI is remote (the macOS client is on 10.12.0.101 and the Linux server is on 100.64.0.1).  It seems as if the GNS3 server is making a request to itself??

**Comment by candlerb** [comment]
Some more log info.  First I [disabled rate limiting](https://bani.com.br/2015/06/systemd-journal-what-does-systemd-journal-suppressed-n-messages-from-system-slice-mean/) in journald, by setting

```
RateLimitIntervalSec=0
RateLimitBurst=0
```

I then did a restore from snapshot; typed a divider (`========`) into the journald output; and then did edit project.  The problem reproduced as before.

```
...
Oct 03 11:26:12 brian-kit gns3server[21661]: 2020-10-03 11:26:12 INFO web_log.py:233 127.0.0.1 [03/Oct/2020:10:26:12 +0000] "POST /v2/compute/projects/dd17577a-a39a-4d2b-b765-f76a736018cc/qemu/nodes/cf3acc85-f3b2-422d-aa1c-69e0fd5e4b9d/adapters/0/ports/0/nio HTTP/1.1" 201 378 "-" "Python/3.6 aiohttp/3.6.2"
Oct 03 11:26:12 brian-kit gns3server[21661]: 2020-10-03 11:26:12 INFO qemu_vm.py:1349 QEMU VM "core1-campus6" [290404b1-4583-46d8-b2dd-00844dc2588a]: NIO UDP added to adapter 3
Oct 03 11:26:12 brian-kit gns3server[21661]: 2020-10-03 11:26:12 INFO web_log.py:233 127.0.0.1 [03/Oct/2020:10:26:12 +0000] "POST /v2/compute/projects/dd17577a-a39a-4d2b-b765-f76a736018cc/qemu/nodes/290404b1-4583-46d8-b2dd-00844dc2588a/adapters/3/ports/0/nio HTTP/1.1" 201 378 "-" "Python/3.6 aiohttp/3.6.2"
Oct 03 11:26:12 brian-kit gns3server[21661]: 2020-10-03 11:26:12 INFO web_log.py:233 127.0.0.1 [03/Oct/2020:10:26:12 +0000] "POST /v2/compute/projects/dd17577a-a39a-4d2b-b765-f76a736018cc/ports/udp HTTP/1.1" 201 243 "-" "Python/3.6 aiohttp/3.6.2"
Oct 03 11:26:12 brian-kit gns3server[21661]: 2020-10-03 11:26:12 INFO web_log.py:233 127.0.0.1 [03/Oct/2020:10:26:12 +0000] "POST /v2/compute/projects/dd17577a-a39a-4d2b-b765-f76a736018cc/ports/udp HTTP/1.1" 201 243 "-" "Python/3.6 aiohttp/3.6.2"
Oct 03 11:26:12 brian-kit gns3server[21661]: 2020-10-03 11:26:12 INFO qemu_vm.py:1349 QEMU VM "srv1-campus6" [cf3acc85-f3b2-422d-aa1c-69e0fd5e4b9d]: NIO UDP added to adapter 1
Oct 03 11:26:12 brian-kit gns3server[21661]: 2020-10-03 11:26:12 INFO web_log.py:233 127.0.0.1 [03/Oct/2020:10:26:12 +0000] "POST /v2/compute/projects/dd17577a-a39a-4d2b-b765-f76a736018cc/qemu/nodes/cf3acc85-f3b2-422d-aa1c-69e0fd5e4b9d/adapters/1/ports/0/nio HTTP/1.1" 201 378 "-" "Python/3.6 aiohttp/3.6.2"
Oct 03 11:26:12 brian-kit gns3server[21661]: 2020-10-03 11:26:12 INFO cloud.py:399 Cloud "NAT-8" [699f93de-d764-470a-b1f9-a02ac8e318b4]: NIO NIO UDP bound to port 0
Oct 03 11:26:12 brian-kit gns3server[21661]: 2020-10-03 11:26:12 INFO web_log.py:233 127.0.0.1 [03/Oct/2020:10:26:12 +0000] "POST /v2/compute/projects/dd17577a-a39a-4d2b-b765-f76a736018cc/nat/nodes/699f93de-d764-470a-b1f9-a02ac8e318b4/adapters/0/ports/0/nio HTTP/1.1" 201 377 "-" "Python/3.6 aiohttp/3.6.2"
Oct 03 11:26:12 brian-kit gns3server[21661]: 2020-10-03 11:26:12 INFO web_log.py:233 10.12.0.101 [03/Oct/2020:10:25:49 +0000] "POST /v2/projects/dd17577a-a39a-4d2b-b765-f76a736018cc/snapshots/b8482ff8-c130-40d5-adae-25463a351bc7/restore HTTP/1.1" 201 790 "-" "GNS3 QT Client v2.2.14"
Oct 03 11:26:12 brian-kit gns3server[21661]: 2020-10-03 11:26:12 INFO web_log.py:233 10.12.0.101 [03/Oct/2020:10:26:12 +0000] "POST /v2/projects/dd17577a-a39a-4d2b-b765-f76a736018cc/open HTTP/1.1" 201 763 "-" "GNS3 QT Client v2.2.14"
Oct 03 11:26:13 brian-kit gns3server[21661]: 2020-10-03 11:26:13 INFO web_log.py:233 10.12.0.101 [03/Oct/2020:10:26:12 +0000] "GET /v2/projects/dd17577a-a39a-4d2b-b765-f76a736018cc/nodes HTTP/1.1" 200 459702 "-" "GNS3 QT Client v2.2.14"
Oct 03 11:26:13 brian-kit gns3server[21661]: 2020-10-03 11:26:13 INFO web_log.py:233 10.12.0.101 [03/Oct/2020:10:26:13 +0000] "GET /v2/projects/dd17577a-a39a-4d2b-b765-f76a736018cc/links HTTP/1.1" 200 102026 "-" "GNS3 QT Client v2.2.14"
=============
Oct 03 11:26:14 brian-kit gns3server[21661]: 2020-10-03 11:26:14 INFO web_log.py:233 10.12.0.101 [03/Oct/2020:10:26:14 +0000] "GET /v2/projects/dd17577a-a39a-4d2b-b765-f76a736018cc/drawings HTTP/1.1" 200 205 "-" "GNS3 QT Client v2.2.14"
Oct 03 11:26:32 brian-kit gns3server[21661]: 2020-10-03 11:26:32 ERROR route.py:242 Uncaught exception detected: <class 'TypeError'>
Oct 03 11:26:32 brian-kit gns3server[21661]: Traceback (most recent call last):
Oct 03 11:26:32 brian-kit gns3server[21661]:   File "/usr/share/gns3/gns3-server/lib/python3.6/site-packages/gns3server/web/route.py", line 198, in control_schema
Oct 03 11:26:32 brian-kit gns3server[21661]:     await func(request, response)
Oct 03 11:26:32 brian-kit gns3server[21661]:   File "/usr/share/gns3/gns3-server/lib/python3.6/site-packages/gns3server/handlers/api/compute/project_handler.py", line 99, in update_project
Oct 03 11:26:32 brian-kit gns3server[21661]:     variables=request.json.get("variables", None)
Oct 03 11:26:32 brian-kit gns3server[21661]:   File "/usr/share/gns3/gns3-server/lib/python3.6/site-packages/gns3server/compute/project.py", line 305, in update
Oct 03 11:26:32 brian-kit gns3server[21661]:     await node.update()
Oct 03 11:26:32 brian-kit gns3server[21661]: TypeError: update() missing 2 required positional arguments: 'name' and 'value'
Oct 03 11:26:32 brian-kit gns3server[21661]: 2020-10-03 11:26:32 INFO web_log.py:233 127.0.0.1 [03/Oct/2020:10:26:32 +0000] "PUT /v2/compute/projects/dd17577a-a39a-4d2b-b765-f76a736018cc HTTP/1.1" 500 880 "-" "Python/3.6 aiohttp/3.6.2"
Oct 03 11:26:32 brian-kit gns3server[21661]: 2020-10-03 11:26:32 INFO web_log.py:233 10.12.0.101 [03/Oct/2020:10:26:32 +0000] "PUT /v2/projects/dd17577a-a39a-4d2b-b765-f76a736018cc HTTP/1.1" 500 355 "-" "GNS3 QT Client v2.2.14"
Oct 03 11:26:32 brian-kit gns3server[21661]: 2020-10-03 11:26:32 INFO project_handler.py:280 Client has disconnected from notification stream for project ID 'dd17577a-a39a-4d2b-b765-f76a736018cc' (WebSocket method)
```

All the logs after the divider appeared at once.  There was one message from 11:26:14, which was apparently delayed from just after the restore, and then 11:26:32 for the rest.

**Comment by grossmj** [comment]
Fixed.
