### ISSUE TITLE
Uvicorn doesn't resolve host

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-server#1840]
```
2020-11-07 15:22:20 WARNING gns3server.controller.compute:383 Cannot connect to compute 'local': Cannot connect to host localhost:3080 ssl:default [Connect call failed ('127.0.0.1', 3080)]
2020-11-07 15:22:20 CRITICAL gns3server.run:356 Critical error while running the server: 'localhost' does not appear to be an IPv4 or IPv6 address
Traceback (most recent call last):
  File "/home/grossmj/PycharmProjects/gns3-server/gns3server/run.py", line 349, in run
    loop.run_until_complete(server.serve())
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/grossmj/PycharmProjects/gns3-server/venv/lib/python3.8/site-packages/uvicorn/main.py", line 436, in serve
    await self.startup(sockets=sockets)
  File "/home/grossmj/PycharmProjects/gns3-server/venv/lib/python3.8/site-packages/uvicorn/main.py", line 526, in startup
    if isinstance(ip_address(config.host), IPv6Address):
  File "/usr/lib/python3.8/ipaddress.py", line 53, in ip_address
    raise ValueError('%r does not appear to be an IPv4 or IPv6 address' %
ValueError: 'localhost' does not appear to be an IPv4 or IPv6 address
```

**Comment by grossmj** [comment]
Looks like there is a problem in uvicorn that is being worked on: https://github.com/encode/uvicorn/pull/827
