### ISSUE TITLE
Exception with endpoints returning HTTP status code 204 (no content)

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-server#1891]
```
2021-05-06 16:32:45 ERROR uvicorn Exception in ASGI application
Traceback (most recent call last):
  File "/home/grossmj/PycharmProjects/gns3-server/venv-test/lib/python3.8/site-packages/uvicorn-0.13.4-py3.8.egg/uvicorn/protocols/http/h11_impl.py", line 396, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/grossmj/PycharmProjects/gns3-server/venv-test/lib/python3.8/site-packages/uvicorn-0.13.4-py3.8.egg/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/home/grossmj/PycharmProjects/gns3-server/venv-test/lib/python3.8/site-packages/fastapi-0.63.0-py3.8.egg/fastapi/applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
  File "/home/grossmj/PycharmProjects/gns3-server/venv-test/lib/python3.8/site-packages/starlette-0.13.6-py3.8.egg/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/grossmj/PycharmProjects/gns3-server/venv-test/lib/python3.8/site-packages/starlette-0.13.6-py3.8.egg/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/home/grossmj/PycharmProjects/gns3-server/venv-test/lib/python3.8/site-packages/starlette-0.13.6-py3.8.egg/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/grossmj/PycharmProjects/gns3-server/venv-test/lib/python3.8/site-packages/starlette-0.13.6-py3.8.egg/starlette/middleware/base.py", line 26, in __call__
    await response(scope, receive, send)
  File "/home/grossmj/PycharmProjects/gns3-server/venv-test/lib/python3.8/site-packages/starlette-0.13.6-py3.8.egg/starlette/responses.py", line 228, in __call__
    await run_until_first_complete(
  File "/home/grossmj/PycharmProjects/gns3-server/venv-test/lib/python3.8/site-packages/starlette-0.13.6-py3.8.egg/starlette/concurrency.py", line 18, in run_until_first_complete
    [task.result() for task in done]
  File "/home/grossmj/PycharmProjects/gns3-server/venv-test/lib/python3.8/site-packages/starlette-0.13.6-py3.8.egg/starlette/concurrency.py", line 18, in <listcomp>
    [task.result() for task in done]
  File "/home/grossmj/PycharmProjects/gns3-server/venv-test/lib/python3.8/site-packages/starlette-0.13.6-py3.8.egg/starlette/responses.py", line 223, in stream_response
    await send({"type": "http.response.body", "body": chunk, "more_body": True})
  File "/home/grossmj/PycharmProjects/gns3-server/venv-test/lib/python3.8/site-packages/starlette-0.13.6-py3.8.egg/starlette/middleware/errors.py", line 156, in _send
    await send(message)
  File "/home/grossmj/PycharmProjects/gns3-server/venv-test/lib/python3.8/site-packages/uvicorn-0.13.4-py3.8.egg/uvicorn/protocols/http/h11_impl.py", line 492, in send
    output = self.conn.send(event)
  File "/home/grossmj/PycharmProjects/gns3-server/venv-test/lib/python3.8/site-packages/h11-0.12.0-py3.8.egg/h11/_connection.py", line 468, in send
    data_list = self.send_with_data_passthrough(event)
  File "/home/grossmj/PycharmProjects/gns3-server/venv-test/lib/python3.8/site-packages/h11-0.12.0-py3.8.egg/h11/_connection.py", line 501, in send_with_data_passthrough
    writer(event, data_list.append)
  File "/home/grossmj/PycharmProjects/gns3-server/venv-test/lib/python3.8/site-packages/h11-0.12.0-py3.8.egg/h11/_writers.py", line 58, in __call__
    self.send_data(event.data, write)
  File "/home/grossmj/PycharmProjects/gns3-server/venv-test/lib/python3.8/site-packages/h11-0.12.0-py3.8.egg/h11/_writers.py", line 78, in send_data
    raise LocalProtocolError("Too much data for declared Content-Length")
h11._util.LocalProtocolError: Too much data for declared Content-Length
```

There is an open issue on fastapi regarding this problem: https://github.com/tiangolo/fastapi/issues/2832

**Comment by grossmj** [comment]
I decided to use the `return Response(status_code=HTTP_204_NO_CONTENT)` workaround even if I wish it could be cleaner...
