### ISSUE TITLE
GNS3 server critical error with Python 3.10.0

### ISSUE THREAD

**Issue by nuqleo** [GNS3/gns3-server#1940]
Hi,

gns3server failed to run in Fedora 35 with Python 3.10.0

2021-08-13 01:23:15 INFO run.py:218 GNS3 server version 2.2.23
2021-08-13 01:23:15 INFO run.py:220 Copyright (c) 2007-2021 GNS3 Technologies Inc.
2021-08-13 01:23:15 INFO run.py:223 Config file /home/user/.config/GNS3/2.2/gns3_server.conf loaded
2021-08-13 01:23:15 INFO run.py:242 Running with Python 3.10.0 and has PID 2024
2021-08-13 01:23:15 INFO run.py:78 Current locale is ru_RU.UTF-8
2021-08-13 01:23:15 INFO web_server.py:318 Starting server on localhost:3080
/usr/lib/python3.10/site-packages/gns3server/web/web_server.py:86: RuntimeWarning: coroutine 'Application.startup' was never awaited
  self._server, startup_res = self._loop.run_until_complete(asyncio.gather(srv, self._app.startup(), loop=self._loop))
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
2021-08-13 01:23:15 CRITICAL run.py:266 Critical error while running the server: gather() got an unexpected keyword argument 'loop'
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/gns3server/run.py", line 260, in run
    server.run()
  File "/usr/lib/python3.10/site-packages/gns3server/web/web_server.py", line 321, in run
    if self._run_application(self._handler, self._ssl_context) is False:
  File "/usr/lib/python3.10/site-packages/gns3server/web/web_server.py", line 86, in _run_application
    self._server, startup_res = self._loop.run_until_complete(asyncio.gather(srv, self._app.startup(), loop=self._loop))
TypeError: gather() got an unexpected keyword argument 'loop'
/usr/lib/python3.10/site-packages/gns3server/run.py:268: RuntimeWarning: coroutine 'BaseEventLoop.create_server' was never awaited
  return
RuntimeWarning: Enable tracemalloc to get the object allocation traceback

$ python --version
Python 3.10.0rc1

**Comment by grossmj** [comment]
Fixed, thanks! :+1:
