### ISSUE TITLE
VMs from vmware fusion doesnt start when connected to topology mac Big Sur osx

### ISSUE THREAD

**Issue by jacuinde** [GNS3/gns3-server#2027]
**GNS3 Version 2.22.29
VMWare fusion 12.1.2
Mac OSX Big Sur 11.2.3

VM Running Windows 7 x64** 

I have a GNS3 Topolgy with a WIndows 7 x64 VM connected to NAT Cloud like the following link

<img width="1390" alt="Screen Shot 2022-01-24 at 10 32 38 PM" src="https://user-images.githubusercontent.com/5535629/150925124-a4d2f2f9-9d8e-4b5e-b842-d3f913225724.png">

VM fails to connect to my topology with the following error in Mac OSX Big Sur but works OK with MAC OSX Catalina

2022-01-24 22:32:05 INFO __init__.py:426 Executing vmrun with command: '/Applications/VMware Fusion.app/Contents/Library/vmrun' -T fusion list
2022-01-24 22:32:05 INFO base_node.py:655 Starting new uBridge hypervisor 172.16.233.1:52629
2022-01-24 22:32:05 INFO hypervisor.py:169 starting ubridge: ['/Applications/GNS3.app/Contents/MacOS/ubridge', '-H', '172.16.233.1:52629']
2022-01-24 22:32:05 INFO hypervisor.py:171 logging to /Users/jacuinde/GNS3/projects/untitled/project-files/vmware/91de7a9c-39fa-4724-a99e-41a539940c41/ubridge.log
2022-01-24 22:32:05 INFO hypervisor.py:179 ubridge started PID=3181
2022-01-24 22:32:05 INFO base_node.py:658 Hypervisor 172.16.233.1:52629 has successfully started
2022-01-24 22:32:05 INFO ubridge_hypervisor.py:83 Connected to uBridge hypervisor on 172.16.233.1:52629 after 0.1033 seconds
2022-01-24 22:32:05 INFO __init__.py:426 Executing vmrun with command: '/Applications/VMware Fusion.app/Contents/Library/vmrun' -T fusion start '/Users/jacuinde/Virtual Machines.localized/Site Survey Win 7.vmwarevm/Site Survey Win 7.vmx'
2022-01-24 22:32:07 ERROR route.py:242 Uncaught exception detected: <class 'AttributeError'>
Traceback (most recent call last):
  File "gns3-server/gns3server/web/route.py", line 198, in control_schema
  File "gns3-server/gns3server/handlers/api/compute/vmware_handler.py", line 157, in start
  File "gns3-server/gns3server/compute/vmware/vmware_vm.py", line 471, in start
  File "gns3-server/gns3server/compute/vmware/vmware_vm.py", line 346, in _add_ubridge_connection
  File "gns3-server/gns3server/compute/vmware/__init__.py", line 347, in find_bridge_interface
AttributeError: 'list' object has no attribute 'keys'
2022-01-24 22:32:07 INFO crash_report.py:166 Crash report sent with event ID: 742c4cb4ba594704b4862f4fde9fc55c
2022-01-24 22:32:07 INFO web_log.py:206 172.16.233.1 [25/Jan/2022:06:32:05 +0000] "POST /v2/compute/projects/58aaaa8e-f554-485b-8afa-8e2b8ad44de4/vmware/nodes/91de7a9c-39fa-4724-a99e-41a539940c41/start HTTP/1.1" 500 836 "-" "Python/3.7 aiohttp/3.7.4.post0"
2022-01-24 22:32:07 INFO web_log.py:206 172.16.233.1 [25/Jan/2022:06:32:05 +0000] "POST /v2/projects/58aaaa8e-f554-485b-8afa-8e2b8ad44de4/nodes/91de7a9c-39fa-4724-a99e-41a539940c41/start HTTP/1.1" 500 436 "-" "GNS3 QT Client v2.2.29"
2022-01-24 22:32:07 WARNING connectionpool.py:811 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1076)'))': /api/38482/store/
2022-01-24 22:32:07 WARNING connectionpool.py:811 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1076)'))': /api/38482/store/
2022-01-24 22:32:07 WARNING connectionpool.py:811 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1076)'))': /api/38482/store/

**Comment by jacuinde** [comment]
Downgrading to Catalina shows no issues

**Comment by jacuinde** [comment]
Heres the server log

[gns3_server.log](https://github.com/GNS3/gns3-server/files/7931217/gns3_server.log)

**Comment by 0xksdata** [comment]
I am having a similar error occur while on ESXi & the client being on Win 10 when attempting to configure the NAT node.
Should I open a new issue for this? 
![image](https://user-images.githubusercontent.com/41391415/160303346-fadb28b5-a8dd-442d-a633-18b3ac235bce.png)

**Comment by grossmj** [comment]
I pushed a fix, I will test on macOS Big Sur soon.

**Comment by grossmj** [comment]
Should be fixed now. I also solved the SSL errors.
