### ISSUE TITLE
GNS3 Export debug information generates nice 500 Gigabyte file

### ISSUE THREAD

**Issue by josephmhiggins** [GNS3/gns3-server#2059]
GNS3 2.2.31 Windows 10 Virtualbox 6.1
- This originally crossed my path before with VMware WS Pro 16.1 a few weeks ago.

It will terminate someone's computer because they might not realize that all their hard disk space is gone. I accidentally did that once before buy recording a screen and forgetting about it. But Windows 10 saved me a little hard disk space so I could reboot and logon and delete the .mov

Started running GNS3 Export Debug Information

2022-04-28 16:56:36 ERROR server_handler.py:188 Could not export debug information 'dict' object has no attribute 'id'
Traceback (most recent call last):
  File "gns3-server\gns3server\handlers\api\controller\server_handler.py", line 185, in debug
  File "gns3-server\gns3server\handlers\api\controller\server_handler.py", line 257, in _getDebugData
AttributeError: 'dict' object has no attribute 'id'
2022-04-28 16:56:36 INFO web_log.py:206 192.168.56.1 [28/Apr/2022:16:56:36 +0000] "GET /v2/compute/debug HTTP/1.1" 200 3300 "-" "Python/3.7 aiohttp/3.7.4.post0"
2022-04-28 16:56:36 INFO web_log.py:206 192.168.56.1 [28/Apr/2022:16:56:36 +0000] "POST /v2/debug HTTP/1.1" 201 191 "-" "GNS3 QT Client v2.2.31"

20220428_171947 GNS3 Export Debug Information looks to have crashed - break time
20220428_174759 Windows Task Manager - End Task Gns3 File is > 200Gigabyte

The gns3_server.log is only 89 lines:

2022-04-28 16:49:02 INFO run.py:219 GNS3 server version 2.2.31
2022-04-28 16:49:02 INFO run.py:221 Copyright (c) 2007-2022 GNS3 Technologies Inc.
2022-04-28 16:49:02 INFO run.py:224 Config file C:\Users\joe_I7\AppData\Roaming\GNS3\2.2\profiles\vbox\gns3_server.ini loaded
2022-04-28 16:49:02 WARNING run.py:230 Local mode is enabled. Beware, clients will have full control on your filesystem
2022-04-28 16:49:02 INFO run.py:237 HTTP authentication is enabled with username 'admin'
2022-04-28 16:49:02 INFO run.py:244 Running with Python 3.7.5 and has PID 22652
2022-04-28 16:49:02 WARNING __init__.py:366 Config disk: image 'config.img' missing
2022-04-28 16:49:02 INFO web_server.py:318 Starting server on 192.168.56.1:80
2022-04-28 16:49:02 INFO __init__.py:63 Load controller configuration file C:\Users\joe_I7\AppData\Roaming\GNS3\2.2\profiles\vbox\gns3_controller.ini
2022-04-28 16:49:02 INFO __init__.py:67 Controller is starting
2022-04-28 16:49:02 INFO compute.py:64 Create compute local
2022-04-28 16:49:02 INFO compute.py:364 Connecting to compute 'local'
2022-04-28 16:49:02 INFO web_log.py:206 192.168.56.1 [28/Apr/2022:16:49:02 +0000] "GET /v2/compute/capabilities HTTP/1.1" 200 519 "-" "Python/3.7 aiohttp/3.7.4.post0"
2022-04-28 16:49:02 INFO __init__.py:314 Start the GNS3 VM
2022-04-28 16:49:02 INFO compute.py:64 Create compute vm
2022-04-28 16:49:02 INFO __init__.py:65 A path to VBoxManage has not been configured, trying to find it...
2022-04-28 16:49:02 INFO __init__.py:112 Executing VBoxManage with command: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe --nologo list systemproperties
2022-04-28 16:49:02 INFO notification_handler.py:50 New client has connected to compute WebSocket
2022-04-28 16:49:02 INFO compute.py:434 Connected to compute 'local' WebSocket 'http://192.168.56.1:80/v2/compute/notifications/ws'
2022-04-28 16:49:02 INFO web_log.py:206 192.168.56.1 [28/Apr/2022:16:49:02 +0000] "GET /v2/version HTTP/1.1" 200 227 "-" "GNS3 QT Client v2.2.31"
2022-04-28 16:49:03 INFO notification_handler.py:73 New client has connected to controller WebSocket
2022-04-28 16:49:03 INFO web_log.py:206 192.168.56.1 [28/Apr/2022:16:49:03 +0000] "GET /v2/version HTTP/1.1" 200 227 "-" "GNS3 QT Client v2.2.31"
2022-04-28 16:49:03 INFO web_log.py:206 192.168.56.1 [28/Apr/2022:16:49:03 +0000] "GET /v2/templates HTTP/1.1" 200 5145 "-" "GNS3 QT Client v2.2.31"
2022-04-28 16:49:03 INFO web_log.py:206 192.168.56.1 [28/Apr/2022:16:49:03 +0000] "GET /v2/computes HTTP/1.1" 200 1377 "-" "GNS3 QT Client v2.2.31"
2022-04-28 16:49:03 INFO web_log.py:206 192.168.56.1 [28/Apr/2022:16:49:03 +0000] "GET /v2/projects HTTP/1.1" 200 183 "-" "GNS3 QT Client v2.2.31"
2022-04-28 16:49:03 INFO web_log.py:206 192.168.56.1 [28/Apr/2022:16:49:03 +0000] "GET /v2/projects HTTP/1.1" 200 183 "-" "GNS3 QT Client v2.2.31"
2022-04-28 16:49:03 INFO web_log.py:206 192.168.56.1 [28/Apr/2022:16:49:03 +0000] "GET /v2/appliances?symbol_theme=Classic HTTP/1.1" 200 1426271 "-" "GNS3 QT Client v2.2.31"
2022-04-28 16:49:03 INFO web_log.py:206 192.168.56.1 [28/Apr/2022:16:49:03 +0000] "GET /v2/symbols/%3A/symbols/classic/router.svg/raw HTTP/1.1" 200 11037 "-" "GNS3 QT Client v2.2.31"
2022-04-28 16:49:03 INFO web_log.py:206 192.168.56.1 [28/Apr/2022:16:49:03 +0000] "GET /v2/symbols/%3A/symbols/ethernet_switch.svg/raw HTTP/1.1" 200 9273 "-" "GNS3 QT Client v2.2.31"
2022-04-28 16:49:03 INFO web_log.py:206 192.168.56.1 [28/Apr/2022:16:49:03 +0000] "GET /v2/symbols/%3A/symbols/docker_guest.svg/raw HTTP/1.1" 200 26604 "-" "GNS3 QT Client v2.2.31"
2022-04-28 16:49:03 INFO web_log.py:206 192.168.56.1 [28/Apr/2022:16:49:03 +0000] "GET /v2/symbols/%3A/symbols/vpcs_guest.svg/raw HTTP/1.1" 200 19495 "-" "GNS3 QT Client v2.2.31"
2022-04-28 16:49:04 INFO __init__.py:112 Executing VBoxManage with command: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe --nologo showvminfo GNS3 VM --machinereadable
2022-04-28 16:49:04 INFO __init__.py:112 Executing VBoxManage with command: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe --nologo showvminfo GNS3 VM --machinereadable
2022-04-28 16:49:04 INFO __init__.py:112 Executing VBoxManage with command: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe --nologo showvminfo GNS3 VM --machinereadable
2022-04-28 16:49:04 INFO __init__.py:112 Executing VBoxManage with command: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe --nologo list hostonlyifs
2022-04-28 16:49:04 INFO __init__.py:112 Executing VBoxManage with command: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe --nologo list dhcpservers
2022-04-28 16:49:04 INFO __init__.py:112 Executing VBoxManage with command: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe --nologo showvminfo GNS3 VM --machinereadable
2022-04-28 16:49:04 INFO virtualbox_gns3_vm.py:259 "GNS3 VM" state is poweroff
2022-04-28 16:49:04 INFO virtualbox_gns3_vm.py:263 Update GNS3 VM vCPUs and RAM settings
2022-04-28 16:49:04 INFO __init__.py:112 Executing VBoxManage with command: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe --nologo modifyvm GNS3 VM --cpus 1
2022-04-28 16:49:04 INFO virtualbox_gns3_vm.py:379 GNS3 VM vCPU count set to 1
2022-04-28 16:49:04 INFO __init__.py:112 Executing VBoxManage with command: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe --nologo modifyvm GNS3 VM --memory 2048
2022-04-28 16:49:04 INFO virtualbox_gns3_vm.py:389 GNS3 VM RAM amount set to 2048
2022-04-28 16:49:04 INFO virtualbox_gns3_vm.py:267 Update GNS3 VM Hardware Virtualization setting
2022-04-28 16:49:04 INFO __init__.py:112 Executing VBoxManage with command: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe --nologo modifyvm GNS3 VM --nested-hw-virt on
2022-04-28 16:49:04 INFO virtualbox_gns3_vm.py:397 Nested hardware virtualization enabled
2022-04-28 16:49:04 INFO __init__.py:112 Executing VBoxManage with command: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe --nologo startvm GNS3 VM
2022-04-28 16:49:11 INFO __init__.py:112 Executing VBoxManage with command: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe --nologo showvminfo GNS3 VM --machinereadable
2022-04-28 16:49:12 INFO virtualbox_gns3_vm.py:291 Removing GNS3VM NAT port forwarding rule from interface 2
2022-04-28 16:49:12 INFO __init__.py:112 Executing VBoxManage with command: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe --nologo controlvm GNS3 VM natpf2 delete GNS3VM
2022-04-28 16:49:12 INFO virtualbox_gns3_vm.py:295 Adding GNS3VM NAT port forwarding rule with port 4580 to interface 2
2022-04-28 16:49:12 INFO __init__.py:112 Executing VBoxManage with command: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe --nologo controlvm GNS3 VM natpf2 GNS3VM,tcp,127.0.0.1,4580,,80
2022-04-28 16:49:55 INFO virtualbox_gns3_vm.py:300 GNS3 VM has been started with IP 192.168.56.101
2022-04-28 16:50:05 INFO compute.py:364 Connecting to compute 'vm'
2022-04-28 16:50:05 INFO compute.py:434 Connected to compute 'vm' WebSocket 'http://192.168.56.101:80/v2/compute/notifications/ws'
2022-04-28 16:50:05 INFO web_log.py:206 192.168.56.1 [28/Apr/2022:16:50:05 +0000] "GET /v2/compute/network/interfaces HTTP/1.1" 200 2690 "-" "Python/3.7 aiohttp/3.7.4.post0"
2022-04-28 16:50:24 INFO web_log.py:206 192.168.56.1 [28/Apr/2022:16:50:24 +0000] "GET /v2/computes HTTP/1.1" 200 1815 "-" "GNS3 QT Client v2.2.31"
2022-04-28 16:50:29 INFO web_log.py:206 192.168.56.1 [28/Apr/2022:16:50:29 +0000] "GET /v2/projects HTTP/1.1" 200 3389 "-" "GNS3 QT Client v2.2.31"
2022-04-28 16:50:44 INFO project_handler.py:403 Project 'gns3endhost-gns3cloud-only-version-003' imported in 0.2870 seconds
2022-04-28 16:50:44 INFO web_log.py:206 192.168.56.1 [28/Apr/2022:16:50:44 +0000] "POST /v2/projects/37190090-b236-4d27-849b-39383c1a8b3e/import?name=gns3endhost-gns3cloud-only-version-003&path=C%3A%5CUsers%5Cjoe_I7%5CGNS3%5CProjects%5Cmarketplace%5Ctest-imports%5Cgns3endhost-gns3cloud-only-version-003 HTTP/1.1" 201 872 "-" "GNS3 QT Client v2.2.31"
2022-04-28 16:50:44 INFO project.py:78 Project 37190090-b236-4d27-849b-39383c1a8b3e with path 'C:\Users\joe_I7\GNS3\Projects\marketplace\test-imports\gns3endhost-gns3cloud-only-version-003' created
2022-04-28 16:50:44 INFO web_log.py:206 192.168.56.1 [28/Apr/2022:16:50:44 +0000] "POST /v2/compute/projects HTTP/1.1" 201 333 "-" "Python/3.7 aiohttp/3.7.4.post0"
2022-04-28 16:50:44 INFO base_node.py:655 Starting new uBridge hypervisor 192.168.56.1:4626
2022-04-28 16:50:44 INFO hypervisor.py:169 starting ubridge: ['C:\\Program Files\\GNS3\\ubridge.EXE', '-H', '192.168.56.1:4626']
2022-04-28 16:50:44 INFO hypervisor.py:171 logging to C:\Users\joe_I7\GNS3\Projects\marketplace\test-imports\gns3endhost-gns3cloud-only-version-003\project-files\builtin\eb1be634-446f-4739-b241-010892f089ca\ubridge.log
2022-04-28 16:50:44 INFO hypervisor.py:179 ubridge started PID=3492
2022-04-28 16:50:44 INFO base_node.py:658 Hypervisor 192.168.56.1:4626 has successfully started
2022-04-28 16:50:44 INFO ubridge_hypervisor.py:83 Connected to uBridge hypervisor on 192.168.56.1:4626 after 0.1014 seconds
2022-04-28 16:50:45 INFO cloud.py:215 Cloud "Cloud1" [eb1be634-446f-4739-b241-010892f089ca] has been created
2022-04-28 16:50:45 INFO web_log.py:206 192.168.56.1 [28/Apr/2022:16:50:44 +0000] "POST /v2/compute/projects/37190090-b236-4d27-849b-39383c1a8b3e/cloud/nodes HTTP/1.1" 201 2007 "-" "Python/3.7 aiohttp/3.7.4.post0"
2022-04-28 16:50:46 INFO web_log.py:206 192.168.56.1 [28/Apr/2022:16:50:46 +0000] "POST /v2/compute/projects/37190090-b236-4d27-849b-39383c1a8b3e/ports/udp HTTP/1.1" 201 243 "-" "Python/3.7 aiohttp/3.7.4.post0"
2022-04-28 16:50:46 INFO cloud.py:399 Cloud "Cloud1" [eb1be634-446f-4739-b241-010892f089ca]: NIO NIO UDP bound to port 2
2022-04-28 16:50:46 ERROR cloud.py:405 Cannot add NIO on cloud "Cloud1": Could not find NPF id for interface eth2
2022-04-28 16:50:46 INFO base_node.py:669 Stopping uBridge hypervisor 192.168.56.1:4626
2022-04-28 16:50:46 INFO hypervisor.py:208 Stopping uBridge process PID=3492
2022-04-28 16:50:46 INFO web_log.py:206 192.168.56.1 [28/Apr/2022:16:50:46 +0000] "POST /v2/compute/projects/37190090-b236-4d27-849b-39383c1a8b3e/cloud/nodes/eb1be634-446f-4739-b241-010892f089ca/adapters/0/ports/2/nio HTTP/1.1" 201 384 "-" "Python/3.7 aiohttp/3.7.4.post0"
2022-04-28 16:50:46 INFO web_log.py:206 192.168.56.1 [28/Apr/2022:16:50:44 +0000] "POST /v2/projects/37190090-b236-4d27-849b-39383c1a8b3e/open HTTP/1.1" 201 870 "-" "GNS3 QT Client v2.2.31"
2022-04-28 16:50:47 INFO project_handler.py:272 New client has connected to the notification stream for project ID '37190090-b236-4d27-849b-39383c1a8b3e' (WebSocket method)
2022-04-28 16:50:47 INFO web_log.py:206 192.168.56.1 [28/Apr/2022:16:50:47 +0000] "GET /v2/projects/37190090-b236-4d27-849b-39383c1a8b3e/nodes HTTP/1.1" 200 6372 "-" "GNS3 QT Client v2.2.31"
2022-04-28 16:50:47 INFO web_log.py:206 192.168.56.1 [28/Apr/2022:16:50:47 +0000] "GET /v2/projects/37190090-b236-4d27-849b-39383c1a8b3e/links HTTP/1.1" 200 1536 "-" "GNS3 QT Client v2.2.31"
2022-04-28 16:50:47 INFO web_log.py:206 192.168.56.1 [28/Apr/2022:16:50:47 +0000] "GET /v2/projects/37190090-b236-4d27-849b-39383c1a8b3e/drawings HTTP/1.1" 200 7969 "-" "GNS3 QT Client v2.2.31"
2022-04-28 16:56:06 INFO web_log.py:206 192.168.56.1 [28/Apr/2022:16:56:06 +0000] "GET /v2/computes HTTP/1.1" 200 1812 "-" "GNS3 QT Client v2.2.31"
2022-04-28 16:56:36 ERROR server_handler.py:188 Could not export debug information 'dict' object has no attribute 'id'
Traceback (most recent call last):
  File "gns3-server\gns3server\handlers\api\controller\server_handler.py", line 185, in debug
  File "gns3-server\gns3server\handlers\api\controller\server_handler.py", line 257, in _getDebugData
AttributeError: 'dict' object has no attribute 'id'
2022-04-28 16:56:36 INFO web_log.py:206 192.168.56.1 [28/Apr/2022:16:56:36 +0000] "GET /v2/compute/debug HTTP/1.1" 200 3300 "-" "Python/3.7 aiohttp/3.7.4.post0"
2022-04-28 16:56:36 INFO web_log.py:206 192.168.56.1 [28/Apr/2022:16:56:36 +0000] "POST /v2/debug HTTP/1.1" 201 191 "-" "GNS3 QT Client v2.2.31"

- command prompt:
C:\Users\joe_I7\GNS3\Projects\marketplace\test-imports\gns3endhost-gns3cloud-only-version-003>dir
 Volume in drive C is OS
 Volume Serial Number is 5804-FB6C

 Directory of C:\Users\joe_I7\GNS3\Projects\marketplace\test-imports\gns3endhost-gns3cloud-only-version-003

04/28/2022  05:45 PM    <DIR>          .
04/28/2022  05:45 PM    <DIR>          ..
04/28/2022  04:50 PM             1,399 docker-cloud-export.gns3project
04/28/2022  05:42 PM   203,529,598,978 export-debug-info.zip
04/28/2022  04:50 PM            23,010 gns3-endhost-1.vim
04/28/2022  04:50 PM             1,468 gns3-endhost-2.vim
04/28/2022  04:50 PM             7,539 gns3-endhost-3.vim
04/28/2022  04:50 PM            15,592 gns3endhost-gns3cloud-only-version-003.gns3
04/28/2022  04:50 PM    <DIR>          project-files
04/28/2022  04:50 PM               115 README.txt
04/28/2022  04:50 PM           102,580 topology-final.PNG
04/28/2022  04:50 PM           106,116 topology.PNG
               9 File(s) 203,529,856,797 bytes
               3 Dir(s)  542,332,329,984 bytes free

C:\Users\joe_I7\GNS3\Projects\marketplace\test-imports\gns3endhost-gns3cloud-only-version-003>

**Comment by josephmhiggins** [comment]
Ean,
You were the one that introduced me to the command a few weeks ago. When it generated the 350G file, I spent 10 seconds looking at it and it looked like it was recursive calls to the same bunch of commands over and over again.

I can not get involved with it - at all.

The command just came out, so the gns3 developers will have to figure out how to make it user-friendly.
Windbg is a powershell module/script to troubleshoot Windows 10.
I have not run Windbg in over a year so my memory may be a little shaky.
But I remember a master log file that says
"starting windbg master log proces with c:\windb.log

windbg.log
calling script01 with log at c:\winddg\log\script01.log

...script01.log
"dir c:\"
"dir $home"

..then I go in and read the log and read all the commands and get to learn; that's cool.

The gns3 developers can architect that export debug information the way they want. I am not getting involved.

**Comment by josephmhiggins** [comment]
export debug information is a similar tool to windbg
well...I would say it is designed differently, but I have not seen it work yet.
The developers can design it anyway they want.

**Comment by josephmhiggins** [comment]
I did it again with a working project - the original exported project.
It worked fine.

I did it again on the imported project. It crashed again at about 30G (crashed means I did Task Manager - GNS3 - End Task)

I went into troubleshooting mode and it built some more 30G files and I settled on as a process, using 003.gns3 as nickname for the imported project


20220429_173852 copied ...003.gns3 to 
C:\Users\joe_I7\GNS3\Projects\marketplace\test-imports\gns3endhost-gns3cloud-only-version-005\...003.gns3
checked all \version-003\ subidirectories for large pcap files - nothing
copied
subidirectories of C:\Users\joe_I7\GNS3\Projects\marketplace\test-imports\gns3endhost-gns3cloud-only-version-003\ 
to
subidirectories of C:\Users\joe_I7\GNS3\Projects\marketplace\test-imports\gns3endhost-gns3cloud-only-version-005\ 


PS > Get-ChildItem -Recurse | Select FullName | Format-Table -AutoSize

FullName                                                                                                                                  
--------                                                                                                                                  
C:\Users\joe_I7\GNS3\Projects\marketplace\test-imports\gns3endhost-gns3cloud-only-version-005\builtin                                     
C:\Users\joe_I7\GNS3\Projects\marketplace\test-imports\gns3endhost-gns3cloud-only-version-005\docker                                      
C:\Users\joe_I7\GNS3\Projects\marketplace\test-imports\gns3endhost-gns3cloud-only-version-005\dynamips                                    
C:\Users\joe_I7\GNS3\Projects\marketplace\test-imports\gns3endhost-gns3cloud-only-version-005\gns3endhost-gns3cloud-only-version-003.gns3 
C:\Users\joe_I7\GNS3\Projects\marketplace\test-imports\gns3endhost-gns3cloud-only-version-005\builtin\eb1be634-446f-4739-b241-010892f089ca
C:\Users\joe_I7\GNS3\Projects\marketplace\test-imports\gns3endhost-gns3cloud-only-version-005\dynamips\ilt_2017072410_mips64e             
C:\Users\joe_I7\GNS3\Projects\marketplace\test-imports\gns3endhost-gns3cloud-only-version-005\dynamips\ilt_2017072410_mips64j             
C:\Users\joe_I7\GNS3\Projects\marketplace\test-imports\gns3endhost-gns3cloud-only-version-005\dynamips\ilt_2017072410_ppc32e              
C:\Users\joe_I7\GNS3\Projects\marketplace\test-imports\gns3endhost-gns3cloud-only-version-005\dynamips\ilt_2017072410_ppc32j              
C:\Users\joe_I7\GNS3\Projects\marketplace\test-imports\gns3endhost-gns3cloud-only-version-005\dynamips\ilt_2019071212_mips64e             
C:\Users\joe_I7\GNS3\Projects\marketplace\test-imports\gns3endhost-gns3cloud-only-version-005\dynamips\ilt_2019071212_mips64j             
C:\Users\joe_I7\GNS3\Projects\marketplace\test-imports\gns3endhost-gns3cloud-only-version-005\dynamips\ilt_2019071212_ppc32e              
C:\Users\joe_I7\GNS3\Projects\marketplace\test-imports\gns3endhost-gns3cloud-only-version-005\dynamips\ilt_2019071212_ppc32j              



PS >  


ran gns3 -help -export debug information
crashed again and built another 20G file until I task manager - end task
C:\Users\joe_I7\GNS3\Projects\marketplace\test-imports\gns3endhost-gns3cloud-only-version-005>dir
 Volume in drive C is OS
 Volume Serial Number is 5804-FB6C

 Directory of C:\Users\joe_I7\GNS3\Projects\marketplace\test-imports\gns3endhost-gns3cloud-only-version-005

04/29/2022  05:52 PM    <DIR>          .
04/29/2022  05:52 PM    <DIR>          ..
04/29/2022  05:37 PM    <DIR>          builtin
04/28/2022  04:50 PM    <DIR>          docker
04/29/2022  05:37 PM    <DIR>          dynamips
04/29/2022  05:51 PM    21,016,592,411 export-debug-information-005.zip
04/29/2022  05:47 PM            15,592 gns3endhost-gns3cloud-only-version-003.gns3
04/29/2022  05:47 PM            15,592 gns3endhost-gns3cloud-only-version-003.txt
04/29/2022  05:51 PM    <DIR>          project-files
               3 File(s) 21,016,623,595 bytes
               6 Dir(s)  457,486,962,688 bytes free

C:\Users\joe_I7\GNS3\Projects\marketplace\test-imports\gns3endhost-gns3cloud-only-version-005>

[gns3endhost-gns3cloud-only-version-003.txt](https://github.com/GNS3/gns3-server/files/8592768/gns3endhost-gns3cloud-only-version-003.txt)

Project looks okay to me.
But it must be the project.

**Comment by josephmhiggins** [comment]
When I ran the export debug information on the original project that was exported, the exported debug information. I did it 2x and one time I started the docker and the filename has that in it.
[test-export-docker-started.zip](https://github.com/GNS3/gns3-server/files/8592862/test-export-docker-started.zip)

**Comment by josephmhiggins** [comment]
The export portable project has the same characteristics of
1. the Kali Linux VM 'Installing the VM', and
2. the Cisco ISE VM installation

No information presentation to the user as to the progress.

For this bug, GNS3 becomes unresponsive (normal Windows users would
use Task Manager and scroll the process into view to see 'Not Responding' or
a whirling icon shows up - which is different than an hourglass).

So the answers to these powershell queries should not be as shown:

ADMIN > $PGNS3Server = Get-Process -Name gns3server
$PGNS3Server.HasExited
$PGNS3Server.Responding

False
True

ADMIN > 


The answer to the powershell queries when the export portable project is hosed should be
False
False

I only learned about the Process.Responding about 5 hours ago, so...I do not know sure and I am busy with Kali.

For the Kali VM which has already spend 4 hours installing and has about
1 hour left to install, it is now at 87% completion level.
I had to login to the GNS3 VM and look at the qcow image being built because
I could have accidentally chosen a 3000G hard disk image size instead of a
30G size. But Kali does not tell me an instantaneous size of the disk from
second to second. Virtualization writing to the hard disk is just slow.

87% means nothing to me.

Cisco ISE is the same thing. GNS3 users show up and say the screen is
frozen at (I do not know - I must have deleted my README.txt)
"ISE is doing something." Then someone has to tell them, that's just the way it is.

Process.Responding Property looks good and I think I can use it for 
Visual Basic. I was going to say last night to keep an upper boundary
on the size of the .gns3project, but David Bombal includes base images
in his video,so that idea was shot down.

GNS3's writing to the hard disk is fast. 2Gig is about 30 seconds.
I think that is about right. The 350G file created was about 30 minutes, I guess.

**Comment by josephmhiggins** [comment]
I have identified the root cause.

Higgins Diagnostic Theorem:
A nominal diagnostic utility can never be designed at a certain user level to go into a state, of that user level, of "not responding".

This implementation violates my theorem.

In other words, any non-"life or death" program/system is allowed to go into a state of "not responding".

I only know of 2 non-OEM specific cases:
1. ram test in bios, and
2. a special diagnostic tool to get the error code of a "check engine" light on a car

In either of those 2 cases a not responding requires the system to be replaced.

I only read amateur books and this theorem/approach is not in there.


I have not tested if gns3 is found to be in a responding state though and I do not if I want to.

**Comment by grossmj** [comment]
The debug endpoint only works for a local server and it will be gone/refactored in version 3.0
