### ISSUE TITLE
Backport reset all console connections

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-server#2072]
See https://github.com/GNS3/gns3-server/issues/1619#issuecomment-1122283639

**Comment by grossmj** [comment]
Added in https://github.com/GNS3/gns3-server/commit/bdd703a0dcdfe1230600a3dd4d979c6a65b4eedc and https://github.com/GNS3/gns3-gui/commit/084d14c17e151953981b0a1a1dd4ebbdb473c231

**Comment by cristian-ciobanu** [comment]
I have tried to use this feature but I think it does not work or at least I do not know exactly how to use it.

I have a qemu node in my topology which is using telnet protocol for console. The console of the node was frozen and I tried to use this option by going to **Control ---> Reset all console connections**,
After a clicked on it, for 10 - 20 seconds the server progress bar started to spin  and in the end it thrown an Internal server error.

This is what I found in the server logs:

**2022-07-22 07:45:13 INFO web_log.py:206 127.0.0.1 [22/Jul/2022:07:45:13 +0000] "POST /v2/compute/projects/c0854bcf-0e5e-4f1c-bb9b-93c794082d56/qemu/nodes/1d83fb36-4687-4
417-80e5-21c09040955d/console/reset HTTP/1.1" 204 195 "-" "Python/3.10 aiohttp/3.8.1"
2022-07-22 07:45:19 ERROR route.py:242 Uncaught exception detected: <class 'ConnectionRefusedError'>
Traceback (most recent call last):
  File "/usr/share/gns3/gns3-server/lib/python3.10/site-packages/gns3server/web/route.py", line 198, in control_schema
    await func(request, response)
  File "/usr/share/gns3/gns3-server/lib/python3.10/site-packages/gns3server/handlers/api/compute/qemu_handler.py", line 611, in reset_console
    await vm.reset_console()
  File "/usr/share/gns3/gns3-server/lib/python3.10/site-packages/gns3server/compute/base_node.py", line 406, in reset_console
    await self.start_wrap_console()
  File "/usr/share/gns3/gns3-server/lib/python3.10/site-packages/gns3server/compute/base_node.py", line 383, in start_wrap_console
    raise e
  File "/usr/share/gns3/gns3-server/lib/python3.10/site-packages/gns3server/compute/base_node.py", line 379, in start_wrap_console
    (reader, writer) = await asyncio.open_connection(host="127.0.0.1", port=self._internal_console_port)
  File "/usr/lib/python3.10/asyncio/streams.py", line 47, in open_connection
    transport, _ = await loop.create_connection(
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1064, in create_connection
    raise exceptions[0]
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1049, in create_connection
    sock = await self._connect_sock(
  File "/usr/lib/python3.10/asyncio/base_events.py", line 960, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/lib/python3.10/asyncio/selector_events.py", line 499, in sock_connect
    return await fut
  File "/usr/lib/python3.10/asyncio/selector_events.py", line 534, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('127.0.0.1', 5001)
2022-07-22 07:45:19 INFO crash_report.py:166 Crash report sent with event ID: 94aa29b169444bcfbd99d7b47e89f8b6**

The node console was still frozen and the only way to fix is to reboot the device.

**Comment by kangver** [comment]
This feature work very well. Please also add this future to Web GUI. Thank you :)

**Comment by grossmj** [comment]
> This feature work very well. Please also add this to Web GUI. Thank you :)

Please can you open a new issue? Thanks 👍
