### ISSUE TITLE
Exception when opening project

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-server#2098]
```
2022-08-24 12:03:09 INFO project.py:352 Project 2a51b7ec-0cb3-476a-a844-388bbbdc7a6e with path '/home/gns3/GNS3/projects/2a51b7ec-0cb3-476a-a844-388bbbdc7a6e' closed
2022-08-24 12:03:09 ERROR h11_impl.py:406 Exception in ASGI application
Traceback (most recent call last):
  File "/home/gns3/gns3-server/venv/lib/python3.7/site-packages/uvicorn-0.18.2-py3.7.egg/uvicorn/protocols/http/h11_impl.py", line 403, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/gns3/gns3-server/venv/lib/python3.7/site-packages/uvicorn-0.18.2-py3.7.egg/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/home/gns3/gns3-server/venv/lib/python3.7/site-packages/fastapi-0.79.0-py3.7.egg/fastapi/applications.py", line 269, in __call__
    await super().__call__(scope, receive, send)
  File "/home/gns3/gns3-server/venv/lib/python3.7/site-packages/starlette-0.19.1-py3.7.egg/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/gns3/gns3-server/venv/lib/python3.7/site-packages/starlette-0.19.1-py3.7.egg/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/gns3/gns3-server/venv/lib/python3.7/site-packages/starlette-0.19.1-py3.7.egg/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/gns3/gns3-server/venv/lib/python3.7/site-packages/starlette-0.19.1-py3.7.egg/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/home/gns3/gns3-server/venv/lib/python3.7/site-packages/starlette-0.19.1-py3.7.egg/starlette/exceptions.py", line 93, in __call__
    raise exc
  File "/home/gns3/gns3-server/venv/lib/python3.7/site-packages/starlette-0.19.1-py3.7.egg/starlette/exceptions.py", line 82, in __call__
    await self.app(scope, receive, sender)
  File "/home/gns3/gns3-server/venv/lib/python3.7/site-packages/fastapi-0.79.0-py3.7.egg/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/home/gns3/gns3-server/venv/lib/python3.7/site-packages/fastapi-0.79.0-py3.7.egg/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/home/gns3/gns3-server/venv/lib/python3.7/site-packages/starlette-0.19.1-py3.7.egg/starlette/routing.py", line 670, in __call__
    await route.handle(scope, receive, send)
  File "/home/gns3/gns3-server/venv/lib/python3.7/site-packages/starlette-0.19.1-py3.7.egg/starlette/routing.py", line 266, in handle
    await self.app(scope, receive, send)
  File "/home/gns3/gns3-server/venv/lib/python3.7/site-packages/starlette-0.19.1-py3.7.egg/starlette/routing.py", line 65, in app
    response = await func(request)
  File "/home/gns3/gns3-server/venv/lib/python3.7/site-packages/fastapi-0.79.0-py3.7.egg/fastapi/routing.py", line 228, in app
    dependant=dependant, values=values, is_coroutine=is_coroutine
  File "/home/gns3/gns3-server/venv/lib/python3.7/site-packages/fastapi-0.79.0-py3.7.egg/fastapi/routing.py", line 160, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/gns3/gns3-server/venv/lib/python3.7/site-packages/gns3_server-3.0.0dev4_6fa3f85b-py3.7.egg/gns3server/api/routes/controller/projects.py", line 188, in open_project
    await project.open()
  File "/home/gns3/gns3-server/venv/lib/python3.7/site-packages/gns3_server-3.0.0dev4_6fa3f85b-py3.7.egg/gns3server/utils/asyncio/__init__.py", line 146, in wrapper
    return await f(oself, *args, **kwargs)
  File "/home/gns3/gns3-server/venv/lib/python3.7/site-packages/gns3_server-3.0.0dev4_6fa3f85b-py3.7.egg/gns3server/controller/project.py", line 1020, in open
    raise e
  File "/home/gns3/gns3-server/venv/lib/python3.7/site-packages/gns3_server-3.0.0dev4_6fa3f85b-py3.7.egg/gns3server/controller/project.py", line 961, in open
    await self.add_node(compute, name, node_id, dump=False, **node)
  File "/home/gns3/gns3-server/venv/lib/python3.7/site-packages/gns3_server-3.0.0dev4_6fa3f85b-py3.7.egg/gns3server/controller/project.py", line 592, in add_node
    self.emit_notification("node.created", node.asdict())
  File "/home/gns3/gns3-server/venv/lib/python3.7/site-packages/gns3_server-3.0.0dev4_6fa3f85b-py3.7.egg/gns3server/controller/node.py", line 835, in asdict
    "ports": [port.asdict() for port in self.ports]
  File "/home/gns3/gns3-server/venv/lib/python3.7/site-packages/gns3_server-3.0.0dev4_6fa3f85b-py3.7.egg/gns3server/controller/node.py", line 835, in <listcomp>
    "ports": [port.asdict() for port in self.ports]
  File "/home/gns3/gns3-server/venv/lib/python3.7/site-packages/gns3_server-3.0.0dev4_6fa3f85b-py3.7.egg/gns3server/controller/ports/port.py", line 99, in asdict
    "short_name": self.short_name,
  File "/home/gns3/gns3-server/venv/lib/python3.7/site-packages/gns3_server-3.0.0dev4_6fa3f85b-py3.7.egg/gns3server/controller/ports/port.py", line 86, in short_name
    elif "/" in self._name:
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by grossmj** [comment]
Content of the project file:

```
{
    "auto_close": true,
    "auto_open": false,
    "auto_start": false,
    "drawing_grid_size": 25,
    "grid_size": 75,
    "name": "Test-For-editing",
    "project_id": "2a51b7ec-0cb3-476a-a844-388bbbdc7a6e",
    "revision": 9,
    "scene_height": 1000,
    "scene_width": 2000,
    "show_grid": false,
    "show_interface_labels": false,
    "show_layers": false,
    "snap_to_grid": false,
    "supplier": null,
    "topology": {
        "computes": [],
        "drawings": [],
        "links": [
            {
                "filters": {},
                "link_id": "2f72abfd-606c-4e7f-ae20-13fbd607f600",
                "link_style": {},
                "nodes": [
                    {
                        "adapter_number": 0,
                        "label": {
                            "rotation": 0,
                            "style": "font-size: 10; font-style: Verdana",
                            "text": "eth0",
                            "x": 83,
                            "y": 30
                        },
                        "node_id": "65db17dd-4838-4688-886f-24e1af30c2f9",
                        "port_number": 0
                    },
                    {
                        "adapter_number": 0,
                        "label": {
                            "rotation": 0,
                            "style": "font-size: 10; font-style: Verdana",
                            "text": "e0",
                            "x": -19,
                            "y": 30
                        },
                        "node_id": "66ba8ddd-4b81-471c-8565-219b49b29d8d",
                        "port_number": 0
                    }
                ],
                "suspend": false
            },
            {
                "filters": {},
                "link_id": "be142c90-bf38-4238-8bcc-2cc3fd6a46e6",
                "link_style": {},
                "nodes": [
                    {
                        "adapter_number": 1,
                        "label": {
                            "rotation": 0,
                            "style": "font-size: 10; font-style: Verdana",
                            "text": "eth1",
                            "x": 79,
                            "y": 45
                        },
                        "node_id": "65db17dd-4838-4688-886f-24e1af30c2f9",
                        "port_number": 0
                    },
                    {
                        "adapter_number": 1,
                        "label": {
                            "rotation": 0,
                            "style": "font-size: 10; font-style: Verdana",
                            "text": "em0",
                            "x": -22,
                            "y": 8
                        },
                        "node_id": "a4ab159c-d36d-4bd9-addb-1ce3aceb0daa",
                        "port_number": 0
                    }
                ],
                "suspend": false
            },
            {
                "filters": {},
                "link_id": "eb1d3656-c29c-4e3b-b3c4-635cc0c28c22",
                "link_style": {},
                "nodes": [
                    {
                        "adapter_number": 2,
                        "label": {
                            "rotation": 0,
                            "style": "font-size: 10; font-style: Verdana",
                            "text": "em1",
                            "x": -22,
                            "y": 44
                        },
                        "node_id": "a4ab159c-d36d-4bd9-addb-1ce3aceb0daa",
                        "port_number": 0
                    },
                    {
                        "adapter_number": 0,
                        "label": {
                            "rotation": 0,
                            "style": "font-size: 10; font-style: Verdana",
                            "text": "e0",
                            "x": 77,
                            "y": 8
                        },
                        "node_id": "c05273fa-6a66-41a4-8f1b-60e3e309e572",
                        "port_number": 0
                    }
                ],
                "suspend": false
            },
            {
                "filters": {},
                "link_id": "c9632698-20dd-472d-98b2-da43930090cc",
                "link_style": {},
                "nodes": [
                    {
                        "adapter_number": 3,
                        "label": {
                            "rotation": 0,
                            "style": "font-size: 10; font-style: Verdana",
                            "text": "em2",
                            "x": -19,
                            "y": 31
                        },
                        "node_id": "a4ab159c-d36d-4bd9-addb-1ce3aceb0daa",
                        "port_number": 0
                    },
                    {
                        "adapter_number": 0,
                        "label": {
                            "rotation": 0,
                            "style": "font-size: 10; font-style: Verdana",
                            "text": "eth0",
                            "x": 83,
                            "y": 29
                        },
                        "node_id": "b85cf0f2-818e-4602-854b-e62006ee285f",
                        "port_number": 0
                    }
                ],
                "suspend": false
            }
        ],
        "nodes": [
            {
                "aux": null,
                "aux_type": "none",
                "compute_id": "local",
                "console": 5021,
                "console_auto_start": false,
                "console_type": "telnet",
                "custom_adapters": [
                    {
                        "adapter_number": 0,
                        "adapter_type": "e1000"
                    },
                    {
                        "adapter_number": 1,
                        "adapter_type": "e1000"
                    },
                    {
                        "adapter_number": 2,
                        "adapter_type": "e1000"
                    },
                    {
                        "adapter_number": 3,
                        "adapter_type": "e1000"
                    },
                    {
                        "adapter_number": 4,
                        "adapter_type": "e1000"
                    },
                    {
                        "adapter_number": 5,
                        "adapter_type": "e1000"
                    },
                    {
                        "adapter_number": 6,
                        "adapter_type": "e1000"
                    },
                    {
                        "adapter_number": 7,
                        "adapter_type": "e1000"
                    }
                ],
                "first_port_name": "",
                "height": 45,
                "label": {
                    "rotation": 0,
                    "style": "font-family: TypeWriter;font-size: 10.0;font-weight: bold;fill: #000000;fill-opacity: 1.0;",
                    "text": "FRR-1",
                    "x": 10,
                    "y": -25
                },
                "locked": false,
                "name": "FRR-1",
                "node_id": "65db17dd-4838-4688-886f-24e1af30c2f9",
                "node_type": "qemu",
                "port_name_format": "eth{0}",
                "port_segment_size": 0,
                "properties": {
                    "adapter_type": "e1000",
                    "adapters": 8,
                    "bios_image": "",
                    "bios_image_md5sum": null,
                    "boot_priority": "c",
                    "cdrom_image": "",
                    "cdrom_image_md5sum": null,
                    "cpu_throttling": 0,
                    "cpus": 1,
                    "create_config_disk": false,
                    "created_at": "2022-04-08T04:53:16",
                    "custom_adapters": [
                        {
                            "adapter_number": 0,
                            "adapter_type": "e1000",
                            "mac_address": null,
                            "port_name": null
                        },
                        {
                            "adapter_number": 1,
                            "adapter_type": "e1000",
                            "mac_address": null,
                            "port_name": null
                        },
                        {
                            "adapter_number": 2,
                            "adapter_type": "e1000",
                            "mac_address": null,
                            "port_name": null
                        },
                        {
                            "adapter_number": 3,
                            "adapter_type": "e1000",
                            "mac_address": null,
                            "port_name": null
                        },
                        {
                            "adapter_number": 4,
                            "adapter_type": "e1000",
                            "mac_address": null,
                            "port_name": null
                        },
                        {
                            "adapter_number": 5,
                            "adapter_type": "e1000",
                            "mac_address": null,
                            "port_name": null
                        },
                        {
                            "adapter_number": 6,
                            "adapter_type": "e1000",
                            "mac_address": null,
                            "port_name": null
                        },
                        {
                            "adapter_number": 7,
                            "adapter_type": "e1000",
                            "mac_address": null,
                            "port_name": null
                        }
                    ],
                    "hda_disk_image": "frr-7.3.1.qcow2",
                    "hda_disk_image_backed": null,
                    "hda_disk_image_md5sum": "e6bd9591a5c630bfe2c8688dc043b20b",
                    "hda_disk_interface": "ide",
                    "hdb_disk_image": "",
                    "hdb_disk_image_backed": null,
                    "hdb_disk_image_md5sum": null,
                    "hdb_disk_interface": "none",
                    "hdc_disk_image": "",
                    "hdc_disk_image_backed": null,
                    "hdc_disk_image_md5sum": null,
                    "hdc_disk_interface": "none",
                    "hdd_disk_image": "",
                    "hdd_disk_image_backed": null,
                    "hdd_disk_image_md5sum": null,
                    "hdd_disk_interface": "none",
                    "initrd": "",
                    "initrd_md5sum": null,
                    "kernel_command_line": "",
                    "kernel_image": "",
                    "kernel_image_md5sum": null,
                    "linked_clone": true,
                    "mac_address": "0c:db:17:dd:00:00",
                    "maxcpus": 1,
                    "on_close": "power_off",
                    "options": "",
                    "platform": "x86_64",
                    "process_priority": "normal",
                    "qemu_path": "/usr/bin/qemu-system-x86_64",
                    "ram": 256,
                    "replicate_network_connection_state": true,
                    "updated_at": "2022-04-08T04:53:16",
                    "usage": "Credentials: root / root\nIf you exit from the router CLI, you can get back by typing 'vtysh' to the console.",
                    "version": "7.3.1"
                },
                "symbol": ":/symbols/classic/router.svg",
                "template_id": "59c55a13-5556-4fe2-9d8a-161c66f7576d",
                "width": 66,
                "x": -612,
                "y": -254,
                "z": 1
            },
            {
                "aux": null,
                "aux_type": "none",
                "compute_id": "local",
                "console": 5028,
                "console_auto_start": false,
                "console_type": "telnet",
                "custom_adapters": [
                    {
                        "adapter_number": 0,
                        "adapter_type": "e1000",
                        "mac_address": null,
                        "port_name": null
                    },
                    {
                        "adapter_number": 1,
                        "adapter_type": "e1000",
                        "mac_address": null,
                        "port_name": null
                    },
                    {
                        "adapter_number": 2,
                        "adapter_type": "e1000",
                        "mac_address": null,
                        "port_name": null
                    },
                    {
                        "adapter_number": 3,
                        "adapter_type": "e1000",
                        "mac_address": null,
                        "port_name": null
                    },
                    {
                        "adapter_number": 4,
                        "adapter_type": "e1000",
                        "mac_address": null,
                        "port_name": null
                    },
                    {
                        "adapter_number": 5,
                        "adapter_type": "e1000",
                        "mac_address": null,
                        "port_name": null
                    },
                    {
                        "adapter_number": 6,
                        "adapter_type": "e1000",
                        "mac_address": null,
                        "port_name": null
                    },
                    {
                        "adapter_number": 7,
                        "adapter_type": "e1000",
                        "mac_address": null,
                        "port_name": null
                    }
                ],
                "first_port_name": "",
                "height": 45,
                "label": {
                    "rotation": 0,
                    "style": "font-family: TypeWriter;font-size: 10.0;font-weight: bold;fill: #000000;fill-opacity: 1.0;",
                    "text": "FRR-2",
                    "x": 10,
                    "y": -25
                },
                "locked": false,
                "name": "FRR-2",
                "node_id": "b85cf0f2-818e-4602-854b-e62006ee285f",
                "node_type": "qemu",
                "port_name_format": "eth{0}",
                "port_segment_size": 0,
                "properties": {
                    "adapter_type": "e1000",
                    "adapters": 8,
                    "bios_image": "",
                    "bios_image_md5sum": null,
                    "boot_priority": "c",
                    "cdrom_image": "",
                    "cdrom_image_md5sum": null,
                    "cpu_throttling": 0,
                    "cpus": 1,
                    "create_config_disk": false,
                    "created_at": "2022-04-08T04:53:16",
                    "custom_adapters": [
                        {
                            "adapter_number": 0,
                            "adapter_type": "e1000",
                            "mac_address": null,
                            "port_name": null
                        },
                        {
                            "adapter_number": 1,
                            "adapter_type": "e1000",
                            "mac_address": null,
                            "port_name": null
                        },
                        {
                            "adapter_number": 2,
                            "adapter_type": "e1000",
                            "mac_address": null,
                            "port_name": null
                        },
                        {
                            "adapter_number": 3,
                            "adapter_type": "e1000",
                            "mac_address": null,
                            "port_name": null
                        },
                        {
                            "adapter_number": 4,
                            "adapter_type": "e1000",
                            "mac_address": null,
                            "port_name": null
                        },
                        {
                            "adapter_number": 5,
                            "adapter_type": "e1000",
                            "mac_address": null,
                            "port_name": null
                        },
                        {
                            "adapter_number": 6,
                            "adapter_type": "e1000",
                            "mac_address": null,
                            "port_name": null
                        },
                        {
                            "adapter_number": 7,
                            "adapter_type": "e1000",
                            "mac_address": null,
                            "port_name": null
                        }
                    ],
                    "hda_disk_image": "frr-7.3.1.qcow2",
                    "hda_disk_image_backed": null,
                    "hda_disk_image_md5sum": "e6bd9591a5c630bfe2c8688dc043b20b",
                    "hda_disk_interface": "ide",
                    "hdb_disk_image": "",
                    "hdb_disk_image_backed": null,
                    "hdb_disk_image_md5sum": null,
                    "hdb_disk_interface": "none",
                    "hdc_disk_image": "",
                    "hdc_disk_image_backed": null,
                    "hdc_disk_image_md5sum": null,
                    "hdc_disk_interface": "none",
                    "hdd_disk_image": "",
                    "hdd_disk_image_backed": null,
                    "hdd_disk_image_md5sum": null,
                    "hdd_disk_interface": "none",
                    "initrd": "",
                    "initrd_md5sum": null,
                    "kernel_command_line": "",
                    "kernel_image": "",
                    "kernel_image_md5sum": null,
                    "linked_clone": true,
                    "mac_address": "0c:5c:f0:f2:00:00",
                    "maxcpus": 1,
                    "on_close": "power_off",
                    "options": "",
                    "platform": "x86_64",
                    "process_priority": "normal",
                    "qemu_path": "/usr/bin/qemu-system-x86_64",
                    "ram": 256,
                    "replicate_network_connection_state": true,
                    "updated_at": "2022-04-08T04:53:16",
                    "usage": "Credentials: root / root\nIf you exit from the router CLI, you can get back by typing 'vtysh' to the console.",
                    "version": "7.3.1"
                },
                "symbol": ":/symbols/classic/router.svg",
                "template_id": "59c55a13-5556-4fe2-9d8a-161c66f7576d",
                "width": 66,
                "x": -604,
                "y": -57,
                "z": 1
            },
            {
                "aux": null,
                "aux_type": "none",
                "compute_id": "local",
                "console": 5031,
                "console_auto_start": false,
                "console_type": "telnet",
                "custom_adapters": [],
                "first_port_name": "em0",
                "height": 59,
                "label": {
                    "rotation": 0,
                    "style": "font-family: TypeWriter;font-size: 10.0;font-weight: bold;fill: #000000;fill-opacity: 1.0;",
                    "text": "OpenBSD-1",
                    "x": -8,
                    "y": -25
                },
                "locked": false,
                "name": "OpenBSD-1",
                "node_id": "a4ab159c-d36d-4bd9-addb-1ce3aceb0daa",
                "node_type": "qemu",
                "port_name_format": "em{0}",
                "port_segment_size": 0,
                "properties": {
                    "adapter_type": "e1000",
                    "adapters": 8,
                    "bios_image": "",
                    "bios_image_md5sum": null,
                    "boot_priority": "c",
                    "cdrom_image": "",
                    "cdrom_image_md5sum": null,
                    "cpu_throttling": 0,
                    "cpus": 1,
                    "create_config_disk": false,
                    "created_at": "2022-06-20T05:36:11",
                    "custom_adapters": [],
                    "hda_disk_image": "openbsd-5.8.qcow2",
                    "hda_disk_image_backed": null,
                    "hda_disk_image_md5sum": "b2488d81bbe1328ae3d6072ccd7e0bc2",
                    "hda_disk_interface": "ide",
                    "hdb_disk_image": "",
                    "hdb_disk_image_backed": null,
                    "hdb_disk_image_md5sum": null,
                    "hdb_disk_interface": "none",
                    "hdc_disk_image": "",
                    "hdc_disk_image_backed": null,
                    "hdc_disk_image_md5sum": null,
                    "hdc_disk_interface": "none",
                    "hdd_disk_image": "",
                    "hdd_disk_image_backed": null,
                    "hdd_disk_image_md5sum": null,
                    "hdd_disk_interface": "none",
                    "initrd": "",
                    "initrd_md5sum": null,
                    "kernel_command_line": "",
                    "kernel_image": "",
                    "kernel_image_md5sum": null,
                    "linked_clone": true,
                    "mac_address": "0c:ab:15:9c:00:00",
                    "maxcpus": 1,
                    "on_close": "power_off",
                    "options": "",
                    "platform": "x86_64",
                    "process_priority": "normal",
                    "qemu_path": "/usr/bin/qemu-system-x86_64",
                    "ram": 256,
                    "replicate_network_connection_state": true,
                    "updated_at": "2022-06-20T05:36:11",
                    "usage": "User root, password gns3",
                    "version": "5.8"
                },
                "symbol": ":/symbols/classic/qemu_guest.svg",
                "template_id": "573a94e0-7f64-46b6-b148-940177440721",
                "width": 65,
                "x": -89,
                "y": 21,
                "z": 1
            },
            {
                "aux": null,
                "aux_type": null,
                "compute_id": "local",
                "console": 5034,
                "console_auto_start": false,
                "console_type": "telnet",
                "custom_adapters": [],
                "first_port_name": null,
                "height": 59,
                "label": {
                    "rotation": 0,
                    "style": "font-family: TypeWriter;font-size: 10.0;font-weight: bold;fill: #000000;fill-opacity: 1.0;",
                    "text": "PC1",
                    "x": 18,
                    "y": -25
                },
                "locked": false,
                "name": "PC1",
                "node_id": "66ba8ddd-4b81-471c-8565-219b49b29d8d",
                "node_type": "vpcs",
                "port_name_format": "Ethernet{0}",
                "port_segment_size": 0,
                "properties": {
                    "created_at": "2022-03-31T08:14:01",
                    "updated_at": "2022-03-31T08:14:01",
                    "usage": null
                },
                "symbol": ":/symbols/vpcs_guest.svg",
                "template_id": "345588fb-45a1-49d6-9921-323481c2c3ce",
                "width": 65,
                "x": -129,
                "y": -209,
                "z": 1
            },
            {
                "aux": null,
                "aux_type": null,
                "compute_id": "local",
                "console": 5036,
                "console_auto_start": false,
                "console_type": "telnet",
                "custom_adapters": [],
                "first_port_name": null,
                "height": 60,
                "label": {
                    "rotation": 0,
                    "style": "font-family: TypeWriter;font-size: 10.0;font-weight: bold;fill: #000000;fill-opacity: 1.0;",
                    "text": "PC2",
                    "x": 15,
                    "y": -25
                },
                "locked": false,
                "name": "PC2",
                "node_id": "c05273fa-6a66-41a4-8f1b-60e3e309e572",
                "node_type": "vpcs",
                "port_name_format": "Ethernet{0}",
                "port_segment_size": 0,
                "properties": {
                    "usage": null
                },
                "symbol": ":/symbols/affinity/square/blue/client.svg",
                "template_id": "52136454-1f50-590a-94e4-816bd02d1062",
                "width": 60,
                "x": -375,
                "y": 134,
                "z": 1
            }
        ]
    },
    "type": "topology",
    "variables": null,
    "version": "3.0.0dev3",
    "zoom": 100
```
