### ISSUE TITLE
export portable project < gns3 version 3.0 on Windows 10 host with localserver enabled fails on large files

### ISSUE THREAD

**Issue by josephmhiggins** [GNS3/gns3-server#2136]
ref: https://gns3.com/error-while-duplicating-project

Matias originally tried to do the old "save project as".
I had him switch to export portable project; it failed on the windows server 2016 node.

Both he and I are running windows 10 with gns3 2.2.34 and usting the gns3 vm

I created a project with the windows server 2016 (the use as linked based vm was checked on his and mine) and that the only node.

In gns3 2.2.34, on windows 10 with the local server enabled and vmware workstation pro 16.2.1 running locally; it failed.
It fails every time around 2.5Gigabytes.
There is absolutely nothing that useful on my localhost in the gns3_server.log, gns3_gui.log, and there is nothing useful
in /var/log/syslog on the gns3 vm and I do not know where to look for any kind of http server errors

But wireshark captures the problem. A tiny slice of the wireshark capture is included.

I tried a host binding of localhost; it failed.
I tried a host binding of x.x.x.1, where x.x.x. is the subnet of the gns3vm; it failed
i configured gns3 have the gns3 vm be the main server and disabled my windows 10 host as a localserver; it worked.

The local server sends a tcp windows zero segment and it does that "forever" in this capture.
The captures I have are all gigabytes and I *think* "forever" is about 1, 2, or 5 and then the gns3 server or the gns3 local server sends a fin.

There's nothing in the logs. Nothing.
There is absolutely nothing in the gns3 source code that I can make sense of.
The gns3 file is uploaded as a .txt file.

[ending3.zip](https://github.com/GNS3/gns3-server/files/10086892/ending3.zip)

[win2016.txt](https://github.com/GNS3/gns3-server/files/10086917/win2016.txt)

**Comment by josephmhiggins** [comment]
i am investigating this again with solarwinds and going to change the way i start gns3 by starting the gns3server first in debug mode to a logfile in the directory of the project and rerun my packet capture to use tshark instead of wireshark.

**Comment by josephmhiggins** [comment]
VMware VMnet1 is a 1 gig link on gns3 2.2.34 and it took 18:17 to 19:08 and then it stopped sending "1500" byte packets according to wireshark.

The wireshark capture shows almost everything clean during the transfer.
On Windows 10, it shows:
-a----         12/9/2022   7:45 PM     3734550483 exported.gns3project                                                                                                                          
-a----         12/9/2022  10:19 PM         342982 exportproject.log                                                                                                                             
-a----         12/9/2022  10:57 PM      807908416 exportproject.pcapng 

A 3Gig file taking 90minutes to download on a 1Gig link.
The Windows 2016 qcow2 on the VMWare Workstation Pro 16.2.1 is
gns3@gns3vm:/opt/gns3/projects/b043f0be-df5e-48dd-8119-25b8438e9928/project-files/qemu/6c8347c6-1535-4d7f-b248-836496ccb616$ ls -al
total 6715876
drwxr-xr-x 2 gns3 gns3       4096 Nov 24 13:31 .
drwxr-xr-x 3 gns3 gns3       4096 Nov 24 13:20 ..
-rw-r--r-- 1 gns3 gns3 6876495872 Nov 24 13:31 hda_disk.qcow2

I think the project should be zipped in 150 seconds (2minutes) and download in 60 seconds.
The offset is latency is minutes.
This was run with minimal Firefox browsers open. My Microsoft Word does open quite a few TCP connections.
But this is not even remotely close.

I do not want to detailed analysis because this is off my almost 2 magnitudes. I suspect that gns3 can not handle big files.

I think this should be labeled a bug.

**Comment by josephmhiggins** [comment]
Something is wrong here.

The gns3_server.log in debug mode shows something like this:
00:00:00 export completed
00:45:00 done exporting project

so there is a 45 minute gap that I have no explanation for.
The primary suspect is MsMpEng,exe (that is the Microsoft AntiMalware Service Executable)

But my custom graph with a PSCustomObject is not picking up anything.
I think there may be more than 1 problem with this code.
The primary problem is that if i say that I want to export a project to ....
**...\somedir\sandbox
then GNS3 MUST honor my request. That is m project. I guarantee that it is safe.
GNS3 MUST NOT build a temporary file than in any other place that I specify - my "sandbox"
GNS3 MUST NOT send any packets to any file other than to  ...\somedir\sandbox**

I am concerned about this MsMpEng.exe.


DateTime              Time AntiMalware VmwareVmx Gns3Server Vmnet0
2/15/2022 2:51:33 AM 3161        1.28      2.86      16.95 

But I do not see anything with my graphs. I do not know what is causing this problem.
I use something like this in my powershell code:
            $ProcessAntiMalStr = '\Process(MsMpEng)\% Processor Time'
            $AntiMalSampleArr = Get-Counter -Counter $ProcessAntiMalStr


which produces in my code something like this:
DateTime              Time AntiMalware VmwareVmx Gns3Server Vmnet0
--------              ---- ----------- --------- ---------- ------
12/15/2022 3:01:46 AM 3773        8.02      0.26      19.20       

Oh...........This is gns3server2.2.34
gns32.2.34 makesa difference.
The statement to start the gns3server is:
C:\Program Files\GNS3>gns3server --local --debug --log "C:\Users\joe_I7\AppData\Roaming\GNS3\2.2\gns3_server.log"


Oh............I have an error is my log start......this is really complicated. It looks like I am not dealing with just  1 bug:
I am dealing with 
1. a timeout during the transfer of the export project,
2. a 45 minute gap in logging, and now
3. this:

C:\Program Files\GNS3>gns3server --local --debug --log "C:\Users\joe_I7\AppData\Roaming\GNS3\2.2\gns3_server.log"
--- Logging error ---
Traceback (most recent call last):
  File "C:\Python37-x64\lib\logging\__init__.py", line 1028, in emit
  File "C:\Python37-x64\lib\encodings\cp1252.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode character '\u2011' in position 634478: character maps to <undefined>
Call stack:
  File "C:\Python37-x64\Lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 113, in run


"a 45 minute gap in logging" is the worst - gns3 does a great job in logging - but not here - it has fallen apart.

**Comment by josephmhiggins** [comment]
Here is the "full" log session
2022-12-15 02:00:16 DEBUG compute.py:510 Attempting request to compute: GET http://192.168.15.128:80/v2/compute/projects/b043f0be-df5e-48dd-8119-25b8438e9928/files {'content-type': 'application/json'}
2022-12-15 02:03:52 DEBUG export_project.py:96 Downloading file 'project-files/dynamips/ilt_2022052400_mips64j' from compute 'vm'
2022-12-15 02:03:52 DEBUG export_project.py:96 Downloading file 'project-files/dynamips/ilt_2022052400_ppc32e' from compute 'vm'
2022-12-15 02:03:53 DEBUG export_project.py:96 Downloading file 'project-files/dynamips/ilt_2022052400_ppc32j' from compute 'vm'
2022-12-15 02:03:53 DEBUG export_project.py:96 Downloading file 'project-files/dynamips/ilt_2022052400_mips64e' from compute 'vm'
2022-12-15 02:03:53 DEBUG export_project.py:96 Downloading file 'project-files/qemu/6c8347c6-1535-4d7f-b248-836496ccb616/hda_disk.qcow2' from compute 'vm'
2022-12-15 03:00:37 INFO response.py:58 GET /v2/projects/b043f0be-df5e-48dd-8119-25b8438e9928/export?include_images=no&include_snapshots=no&reset_mac_addresses=no&compression=zip
2022-12-15 03:00:37 DEBUG response.py:59 {'Host': '192.168.15.1:80', 'Authorization': 'Basic YWRtaW46UFc4ZlRtbEpsMlJHd3dYelFSYmMwa1RpMW9pblVTUUY4VlF4ZDkzNHM3emxlaFkwWElmNHVXMVhDbWxxR2dCUQ==', 'User-Agent': 'GNS3 QT Client v2.2.34', 'Content-Type': 'application/json', 'Content-Length': '2', 'Connection': 'Keep-Alive', 'Accept-Encoding': 'gzip, deflate', 'Accept-Language': 'en-US,*'}
2022-12-15 03:00:37 DEBUG response.py:61 {'include_images': 'no', 'include_snapshots': 'no', 'reset_mac_addresses': 'no', 'compression': 'zip'}
2022-12-15 03:00:37 INFO response.py:62 Response: 200 OK
2022-12-15 03:00:37 DEBUG response.py:63 {'Connection': 'close', 'X-Route': '/v2/projects/{project_id}/export', 'Server': 'Python/3.7 GNS3/2.2.34', 'Content-Type': 'application/gns3project', 'CONTENT-DISPOSITION': 'attachment; filename="win2016.gns3project"'}
2022-12-15 03:37:01 INFO project_handler.py:351 Project 'win2016' exported in 5805.0400 seconds


Attached should be the chart.
About the 300 second range, the export begins and gns3server cpu usage goes up.
Again, this is with gns3 < 3.0 and the server is on a Windows 10 host. I do not know anything about >= 3.0
The file was "downloaded" completely at 03:00 (after about 3500 seconds or so on the chart)
Then the chart appears to show AntiMalware kicking in.
The previous successful wireshark capture, where I was looking for but never found ZeroWindow, showed that the transfer rate was almost a rock steady 200Mbps, which is fine for me.

I suspect the whole file is being downloaded somewhere and then zipped in one fell "swoop" and then that is when Antimalware starts kicking in. From what I see with .NET, a zip file can be added to piece by piece. One of my powershell books has an anecdote from a professional programmer that warns of designing something in one fell "swoop" and the solution he reveals is to do it piece by piece.

![chart](https://user-images.githubusercontent.com/85327995/207868969-4dba1460-bde7-4b2f-94ce-7e82fe36f76a.png)

**Comment by josephmhiggins** [comment]
I will do this again. This time I will turn off antimalware on the directory which will be the final resting place of the file.
If that chart is clean, then that will be the definitive way to export a project on Windows 10 with MsMpEng.exe running.

Note: exporting a project in increments could be dangerous because the antimalware might be running throughout the entire export process.

It is completely illegal to turn off antimalware, but completely legal to turn it off for the directory i export the project because *I* built the export. A VM would have to magically jump out of the .zip file to make that unsafe.

**Comment by josephmhiggins** [comment]
Done again.
Absolutely no time savings by excluding the directory from msmpeng.exe
2022-12-15 21:44:02 INFO project_handler.py:351 Project 'win2016' exported in 5744.5514 seconds

The spurious antimalware cpu usage at the beginning of the chart is just me visiting a few websites before i closed down all my browsers.

All previous failures I am blaming on mpsmpeng.exe

![chart-antimalware-excluded](https://user-images.githubusercontent.com/85327995/207976245-2e127e36-9d2e-423e-b48c-f0204ffdc092.png)

**Comment by josephmhiggins** [comment]
Oh, the y-axis on all those charts are in %cpu usage. Total cpu usage is not shown because nothing else is 'running'.
