### ISSUE TITLE
"No static busybox found" while installing from sources

### ISSUE THREAD

**Issue by elico** [GNS3/gns3-server#2158]
I am running the next commands:
```bash
git clone https://github.com/GNS3/gns3-server.git
cd gns3-server
git fetch --all --tags
git checkout tags/v2.2.36
pip3 install -r requirements.txt
python3 -m pip install .
```
and the out from the last command is:
```
Processing /opt/src/oracle8-bootstrap/gns3-server
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [1 lines of output]
      No static busybox found
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

Whats the difference between 2.2.35 to 2.2.36 that it requires busybox static binary to be present?

**Comment by elico** [comment]
@b-ehlers I copied the static binary from the older version and also from the latest ubuntu LTS but... I get the next error:
```
Jan 05 20:12:08 gns3-vm2.pxlab.ngtech gns3server[1437050]: 2023-01-05 20:12:08 ERROR route.py:221 Node error detected: DynamipsError
Jan 05 20:12:08 gns3-vm2.pxlab.ngtech gns3server[1437050]: Traceback (most recent call last):
Jan 05 20:12:08 gns3-vm2.pxlab.ngtech gns3server[1437050]:   File "/usr/local/lib/python3.9/site-packages/gns3server/web/route.py", line 200, in control_schema
Jan 05 20:12:08 gns3-vm2.pxlab.ngtech gns3server[1437050]:     await func(request, response)
Jan 05 20:12:08 gns3-vm2.pxlab.ngtech gns3server[1437050]:   File "/usr/local/lib/python3.9/site-packages/gns3server/handlers/api/compute/ethernet_switch_handler.py", line 55, in create
Jan 05 20:12:08 gns3-vm2.pxlab.ngtech gns3server[1437050]:     node = await dynamips_manager.create_node(request.json.pop("name"),
Jan 05 20:12:08 gns3-vm2.pxlab.ngtech gns3server[1437050]:   File "/usr/local/lib/python3.9/site-packages/gns3server/compute/base_manager.py", line 259, in create_node
Jan 05 20:12:08 gns3-vm2.pxlab.ngtech gns3server[1437050]:     await node.create()
Jan 05 20:12:08 gns3-vm2.pxlab.ngtech gns3server[1437050]:   File "/usr/local/lib/python3.9/site-packages/gns3server/compute/dynamips/nodes/ethernet_switch.py", line 184, in create
Jan 05 20:12:08 gns3-vm2.pxlab.ngtech gns3server[1437050]:     self._hypervisor = await self.manager.start_new_hypervisor(working_dir=module_workdir)
Jan 05 20:12:08 gns3-vm2.pxlab.ngtech gns3server[1437050]:   File "/usr/local/lib/python3.9/site-packages/gns3server/compute/dynamips/__init__.py", line 310, in start_new_hypervisor
Jan 05 20:12:08 gns3-vm2.pxlab.ngtech gns3server[1437050]:     await hypervisor.connect()
Jan 05 20:12:08 gns3-vm2.pxlab.ngtech gns3server[1437050]:   File "/usr/local/lib/python3.9/site-packages/gns3server/compute/dynamips/dynamips_hypervisor.py", line 90, in connect
Jan 05 20:12:08 gns3-vm2.pxlab.ngtech gns3server[1437050]:     raise DynamipsError("Couldn't connect to hypervisor on {}:{} :{}".format(host, self._port, last_exception))
Jan 05 20:12:08 gns3-vm2.pxlab.ngtech gns3server[1437050]: gns3server.compute.dynamips.dynamips_error.DynamipsError: Couldn't connect to hypervisor on 127.0.0.1:59321 :[Errno 111] Connect call failed ('127.0.0.1', 59321)
```
I am unable to start a basic ethernet switch.

**Comment by elico** [comment]
@b-ehlers Thanks, This was it.
I have put a full upgrade with the download of a busybox-static package from ubuntu lts ie:
```bash
#!/usr/bin/env bash

URL="http://cz.archive.ubuntu.com/ubuntu/pool/main/b/busybox/busybox-static_1.30.1-7ubuntu3_amd64.deb"

mkdir tmp

cd tmp && \
        wget "${URL}"
ar x busybox-static*.deb
```

and after that I am just copying the busybox binary and it works.

Thanks again.
