### ISSUE TITLE
Qemu linux are not seen down

### ISSUE THREAD

**Issue by thchich** [GNS3/gns3-server#2170]
If I shut a qemu linux host in gns3, (gns3vm 2.2.36), I lost the console, but I never see it down. I never see the Starp button again. In the log, I found: 
```
2023-01-18 13:16:59 ERROR base_events.py:1285 Task exception was never retrieved
future: <Task finished coro=<_check_process() done, defined at /usr/local/lib/python3.6/dist-packages/gns3server/utils/asyncio/__init__.py:115> exception=AttributeError("'StreamWriter' object has no attribute 'wait_closed'",)>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/gns3server/utils/asyncio/__init__.py", line 119, in _check_process
    await termination_callback(returncode)
  File "/usr/local/lib/python3.6/dist-packages/gns3server/compute/qemu/qemu_vm.py", line 1144, in _termination_callback
    await self.stop()
  File "/usr/local/lib/python3.6/dist-packages/gns3server/compute/qemu/qemu_vm.py", line 1195, in stop
    await super().stop()
  File "/usr/local/lib/python3.6/dist-packages/gns3server/compute/base_node.py", line 315, in stop
    await self.stop_wrap_console()
  File "/usr/local/lib/python3.6/dist-packages/gns3server/compute/base_node.py", line 411, in stop_wrap_console
    await self._wrap_console_writer.wait_closed()
AttributeError: 'StreamWriter' object has no attribute 'wait_closed'
```

**Comment by grossmj** [comment]
I have added quick (ugly) fix that should take care of the issue.
