### ISSUE TITLE
Broken Web console with python 3.11

### ISSUE THREAD

**Issue by nuqleo** [GNS3/gns3-server#2188]
Hi,

Web console is broken in gns3-server 2.2.37 running in Fedora 37 with python 3.11

2023-02-18 01:38:03 INFO base_node.py:443 Connected to Telnet server
2023-02-18 01:38:03 INFO base_node.py:449 New client has connected to console WebSocket
2023-02-18 01:38:03 INFO base_node.py:474 Client has disconnected from console WebSocket
2023-02-18 01:38:03 ERROR route.py:246 Uncaught exception detected: <class 'TypeError'>
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/gns3server/web/route.py", line 200, in control_schema
    await func(request, response)
  File "/usr/lib/python3.11/site-packages/gns3server/handlers/api/compute/qemu_handler.py", line 592, in console_ws
    return await vm.start_websocket_console(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/gns3server/compute/base_node.py", line 472, in start_websocket_console
    await asyncio.wait([ws_forward(telnet_writer), telnet_forward(telnet_reader)], return_when=asyncio.FIRST_COMPLETED)
  File "/usr/lib64/python3.11/asyncio/tasks.py", line 415, in wait
    raise TypeError("Passing coroutines is forbidden, use tasks explicitly.")
TypeError: Passing coroutines is forbidden, use tasks explicitly.

But it works in Fedora 36 with python 3.10.

**Comment by grossmj** [comment]
@nuqleo thanks for catching this, I have fixed the issue

**Comment by nuqleo** [comment]
Applied patch to 2.2.37. 
Web console works now both with python 311 and 3.10.
Thanks.

**Comment by grossmj** [comment]
Thanks for the confirmation! :)
