### ISSUE TITLE
Server sends error 500 if using Telnet to send garbage.

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-server#221]
```
$ telnet ::1 8000
Trying ::1...
Connected to ::1.
Escape character is '^]'.
HELp


HELO
HTTP/1.1 500 Internal Server Error
CONTENT-TYPE: text/html; charset=utf-8
CONTENT-LENGTH: 170
CONNECTION: close
DATE: Sat, 06 Jun 2015 21:39:02 GMT
SERVER: Python/3.4 aiohttp/0.16.3


<html>
  <head>
    <title>500 Internal Server Error</title>
  </head>
  <body>
    <h1>500 Internal Server Error</h1>
    Server got itself in trouble
  </body>
</html>Connection closed by foreign host.
```

```
2015-06-06 15:39:02 ERROR server.py:207 Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/aiohttp-0.16.3-py3.4-linux-x86_64.egg/aiohttp/server.py", line 241, in start
    yield from prefix.read()
  File "/usr/local/lib/python3.4/dist-packages/aiohttp-0.16.3-py3.4-linux-x86_64.egg/aiohttp/streams.py", line 505, in read
    result = yield from super().read()
  File "/usr/local/lib/python3.4/dist-packages/aiohttp-0.16.3-py3.4-linux-x86_64.egg/aiohttp/streams.py", line 365, in read
    yield from self._waiter
  File "/usr/lib/python3.4/asyncio/futures.py", line 348, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.4/asyncio/tasks.py", line 351, in _wakeup
    value = future.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 243, in result
    raise self._exception
  File "/usr/local/lib/python3.4/dist-packages/aiohttp-0.16.3-py3.4-linux-x86_64.egg/aiohttp/parsers.py", line 131, in feed_data
    self._parser.send(data)
  File "/usr/local/lib/python3.4/dist-packages/aiohttp-0.16.3-py3.4-linux-x86_64.egg/aiohttp/protocol.py", line 139, in __call__
    raw_data = yield from buf.waituntil(b' ', 12)
  File "/usr/local/lib/python3.4/dist-packages/aiohttp-0.16.3-py3.4-linux-x86_64.egg/aiohttp/parsers.py", line 374, in waituntil
    'Line is too long. %s' % bytes(self), limit)
aiohttp.errors.LineLimitExceededParserError: Line is too long. b'HELp\r\n\r\n\r\nHELO\r\n'
```

**Comment by noplay** [comment]
We can reply with a 400 it's good?

**Comment by grossmj** [comment]
Bad request is good :+1:

**Comment by noplay** [comment]
It's never in our code, we can't catch it. The debug is noisy but not send to the crash report server.

I just open an issue on aiohttp side:
https://github.com/KeepSafe/aiohttp/issues/404

**Comment by noplay** [comment]
Issue 404 :)

**Comment by noplay** [comment]
Pull request opened:
https://github.com/KeepSafe/aiohttp/pull/405

**Comment by noplay** [comment]
Fixed in aiohttp

**Comment by grossmj** [comment]
:+1: aiohttp contributor ;)
