### ISSUE TITLE
gns3server do not connect to websocket , only root user.

### ISSUE THREAD

**Issue by alexcama** [GNS3/gns3-server#2228]
I have an ubuntu 22.04 lts server and gns3server 2.2.39 installed, yesterday when updating packages in ubuntu, I noticed that the gns3server goes up but does not let the gui of another machine or even the web-ui connect to it, so I tried with the root user and everything is fine, however the projects and images are in another directory "/home/alexcama", Does anyone know if it is because of permission or something?
 log common user: 
2023-05-29 13:59:54 INFO run.py:219 GNS3 server version 2.2.39
2023-05-29 13:59:54 INFO run.py:221 Copyright (c) 2007-2023 GNS3 Technologies Inc.
2023-05-29 13:59:54 INFO run.py:224 Config file /home/alexcama/.config/GNS3/2.2/gns3_server.conf loaded
2023-05-29 13:59:54 INFO run.py:243 Running with Python 3.10.6 and has PID 1846
2023-05-29 13:59:54 INFO run.py:79 Current locale is en_US.UTF-8
2023-05-29 13:59:54 INFO web_server.py:318 Starting server on 0.0.0.0:3080
2023-05-29 13:59:54 INFO __init__.py:70 Load controller configuration file /home/alexcama/.config/GNS3/2.2/gns3_controller.conf
2023-05-29 13:59:54 INFO __init__.py:74 Controller is starting
2023-05-29 13:59:54 INFO __init__.py:309 Installing base configs in '/home/alexcama/GNS3/configs'
2023-05-29 13:59:54 INFO __init__.py:322 Installing built-in disks in '/home/alexcama/GNS3/images/QEMU'
2023-05-29 13:59:54 INFO compute.py:64 Create compute local
2023-05-29 13:59:54 INFO compute.py:364 Connecting to compute 'local'
2023-05-29 13:59:54 INFO web_log.py:206 127.0.0.1 [29/May/2023:13:59:54 +0000] "GET /v2/compute/capabilities HTTP/1.1" 200 553 "-" "Python/3.10 aiohttp/3.8.4"

Log root user:
2023-05-29 14:00:50 INFO run.py:219 GNS3 server version 2.2.39
2023-05-29 14:00:50 INFO run.py:221 Copyright (c) 2007-2023 GNS3 Technologies Inc.
2023-05-29 14:00:50 INFO run.py:243 Running with Python 3.10.6 and has PID 1865
2023-05-29 14:00:50 INFO run.py:79 Current locale is en_US.UTF-8
2023-05-29 14:00:50 INFO web_server.py:318 Starting server on 0.0.0.0:3080
2023-05-29 14:00:50 INFO __init__.py:70 Load controller configuration file /root/.config/GNS3/2.2/gns3_controller.conf
2023-05-29 14:00:50 INFO __init__.py:74 Controller is starting
2023-05-29 14:00:50 INFO __init__.py:309 Installing base configs in '/root/GNS3/configs'
2023-05-29 14:00:50 INFO __init__.py:322 Installing built-in disks in '/root/GNS3/images/QEMU'
2023-05-29 14:00:50 INFO compute.py:64 Create compute local
2023-05-29 14:00:50 INFO compute.py:364 Connecting to compute 'local'
2023-05-29 14:00:50 INFO web_log.py:206 127.0.0.1 [29/May/2023:14:00:50 +0000] "GET /v2/compute/capabilities HTTP/1.1" 200 553 "-" "Python/3.10 aiohttp/3.8.4"
2023-05-29 14:00:50 INFO notification_handler.py:50 New client has connected to compute WebSocket
2023-05-29 14:00:50 INFO compute.py:431 Connected to compute 'local' WebSocket 'http://127.0.0.1:3080/v2/compute/notifications/ws'
2023-05-29 14:00:54 INFO web_log.py:206 192.168.15.68 [29/May/2023:14:00:54 +0000] "GET / HTTP/1.1" 302 199 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36"
2023-05-29 14:00:54 INFO web_log.py:206 192.168.15.68 [29/May/2023:14:00:54 +0000] "GET /static/web-ui/bundled HTTP/1.1" 200 10059 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36"
2023-05-29 14:00:54 INFO web_log.py:206 192.168.15.68 [29/May/2023:14:00:54 +0000] "GET /v2/projects HTTP/1.1" 200 184 "http://192.168.15.69:3080/static/web-ui/server/1/projects" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36"

**Comment by grossmj** [comment]
Looks similar to https://github.com/GNS3/gns3-gui/issues/3464 

What do you see if you open `http://127.0.0.1:3080/v2/compute/notifications/ws'` in a browser after the server has been started?

Also, do you have the issue if you use our web-ui?

**Comment by alexcama** [comment]
I have no way to make this request, on this equipment I only run gns3server, I will post the debug for common user and root user. Then I upload the server on one side with the ip 192.168.15.69 and access via web-ui or gns3-gui on the ip 192.168.15.68 , there are no FW problems, when I did the update from ubuntu 22.04 it stopped working, it just works with user root (which doesn't have my topologies and projects and etc).
See that when using it in the browser of the client machine, it works only with the root user.
http://192.168.15.69:3080/v2/compute/notifications/ws
{
    "message": "No WebSocket UPGRADE hdr: None\n Can \"Upgrade\" only to \"WebSocket\".",
    "method": "GET",
    "path": "/v2/compute/notifications/ws",
    "request": {},
    "status": 400
}

With the common user, he tries to connect and nothing appears in the browser, but the connection is made on the server, as can be seen here.
alexcama@ubuntu22:~$ ss -atn | grep 3080
LISTEN     1      100          0.0.0.0:3080       0.0.0.0:*           
ESTAB      443    0      192.168.15.69:3080 192.168.15.68:45288       
[root_user_debug.txt](https://github.com/GNS3/gns3-server/files/11600079/root_user_debug.txt)

CLOSE-WAIT 1      0          127.0.0.1:3080     127.0.0.1:40292       
[root_user_debug.txt](https://github.com/GNS3/gns3-server/files/11600094/root_user_debug.txt)


[common_user_debug.txt](https://github.com/GNS3/gns3-server/files/11600092/common_user_debug.txt)

**Comment by alexcama** [comment]
> Looks similar to [GNS3/gns3-gui#3464](https://github.com/GNS3/gns3-gui/issues/3464)
> 
> What do you see if you open `http://127.0.0.1:3080/v2/compute/notifications/ws'` in a browser after the server has been started?
> 
> Also, do you have the issue if you use our web-ui?

It s not same issue.

**Comment by alexcama** [comment]
added a commit that referenced this issue [yesterday](https://github.com/GNS3/gns3-server/issues/2228#ref-commit-2361e13)
@grossmj
[Properly catch aiohttp client exception. Ref](https://github.com/GNS3/gns3-server/commit/2361e138ec540c74423176358fbf40b1b9d27a76) https://github.com/GNS3/gns3-server/issues/2228

I modified the lines of that commit but it still doesn't work, let me know if you need any log

**Comment by alexcama** [comment]
> This commit should catch any client error when the controller connects to the compute websocket. Do you see anything new or an error when starting the server?

Ok, I didn't notice anything strange, the behavior is the same, the difference is when the common user stops at that line and root continues,note that after the CRTL+C in the common user it gives some errors and in root this does not happen

user common:
2023-05-31 13:23:28 DEBUG compute.py:510 Attempting request to compute: GET http://127.0.0.1:3080/v2/compute/capabilities {'content-type': 'application/json'}
2023-05-31 13:23:28 INFO response.py:58 GET /v2/compute/capabilities
2023-05-31 13:23:28 DEBUG response.py:59 {'Host': '127.0.0.1:3080', 'Content-Type': 'application/json', 'Accept': '*/*', 'Accept-Encoding': 'gzip, deflate', 'User-Agent': 'Python/3.10 aiohttp/3.8.4', 'Authorization': 'Basic YWRtaW46ekRYODR0aGp0MlVHclVidDhtdkFxd3QwaFh0dDJiRVlpVFdOS0dBTUFlZEV0ZUE2SHRtMkNobHFycEduazlxVA=='}
2023-05-31 13:23:28 DEBUG response.py:61 {}
2023-05-31 13:23:28 INFO response.py:62 Response: 200 OK
2023-05-31 13:23:28 DEBUG response.py:63 {'Connection': 'close', 'X-Route': '/v2/compute/capabilities', 'Server': 'Python/3.10 GNS3/2.2.39', 'Content-Type': 'application/json'}
2023-05-31 13:23:28 DEBUG response.py:65 {'node_types': ['cloud', 'ethernet_hub', 'ethernet_switch', 'nat', 'vpcs', 'virtualbox', 'dynamips', 'frame_relay_switch', 'atm_switch', 'qemu', 'vmware', 'traceng', 'docker', 'iou'], 'platform': 'linux', 'version': '2.2.39'}
2023-05-31 13:23:28 INFO web_log.py:206 127.0.0.1 [31/May/2023:13:23:28 +0000] "GET /v2/compute/capabilities HTTP/1.1" 200 553 "-" "Python/3.10 aiohttp/3.8.4"

After CRTL+C
^CTraceback (most recent call last):
  File "/usr/bin/gns3server", line 8, in <module>
    sys.exit(main())
  File "/usr/share/gns3/gns3-server/lib/python3.10/site-packages/gns3server/main.py", line 83, in main
    run()
  File "/usr/share/gns3/gns3-server/lib/python3.10/site-packages/gns3server/run.py", line 261, in run
    server.run()
  File "/usr/share/gns3/gns3-server/lib/python3.10/site-packages/gns3server/web/web_server.py", line 321, in run
    if self._run_application(self._handler, self._ssl_context) is False:
  File "/usr/share/gns3/gns3-server/lib/python3.10/site-packages/gns3server/web/web_server.py", line 86, in _run_application
    self._server, startup_res = self._loop.run_until_complete(asyncio.gather(srv, self._app.startup()))
  File "/usr/lib/python3.10/asyncio/base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 600, in run_forever
    self._run_once()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1888, in _run_once
    handle._run()
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/share/gns3/gns3-server/lib/python3.10/site-packages/gns3server/compute/base_manager.py", line 591, in list_images
    return list_images(self._NODE_TYPE)
  File "/usr/share/gns3/gns3-server/lib/python3.10/site-packages/gns3server/utils/images.py", line 83, in list_images
    "md5sum": md5sum(os.path.join(root, filename)),
  File "/usr/share/gns3/gns3-server/lib/python3.10/site-packages/gns3server/utils/images.py", line 178, in md5sum
    m.update(buf)
KeyboardInterrupt
2023-05-31 13:23:30 ERROR base_events.py:1744 Task exception was never retrieved
future: <Task finished name='Task-10' coro=<BaseManager.list_images() done, defined at /usr/share/gns3/gns3-server/lib/python3.10/site-packages/gns3server/compute/base_manager.py:583> exception=KeyboardInterrupt() created at /usr/lib/python3.10/asyncio/tasks.py:636>
source_traceback: Object created at (most recent call last):
  File "/usr/bin/gns3server", line 8, in <module>
    sys.exit(main())
  File "/usr/share/gns3/gns3-server/lib/python3.10/site-packages/gns3server/main.py", line 83, in main
    run()
  File "/usr/share/gns3/gns3-server/lib/python3.10/site-packages/gns3server/run.py", line 261, in run
    server.run()
  File "/usr/share/gns3/gns3-server/lib/python3.10/site-packages/gns3server/web/web_server.py", line 321, in run
    if self._run_application(self._handler, self._ssl_context) is False:
  File "/usr/share/gns3/gns3-server/lib/python3.10/site-packages/gns3server/web/web_server.py", line 86, in _run_application
    self._server, startup_res = self._loop.run_until_complete(asyncio.gather(srv, self._app.startup()))
  File "/usr/lib/python3.10/asyncio/base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 600, in run_forever
    self._run_once()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1888, in _run_once
    handle._run()
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/share/gns3/gns3-server/lib/python3.10/site-packages/aiohttp/web_app.py", line 417, in startup
    await self.on_startup.send(self)
  File "/usr/share/gns3/gns3-server/lib/python3.10/site-packages/aiosignal/__init__.py", line 36, in send
    await receiver(*args, **kwargs)  # type: ignore
  File "/usr/share/gns3/gns3-server/lib/python3.10/site-packages/gns3server/web/web_server.py", line 242, in _on_startup
    asyncio.ensure_future(Qemu.instance().list_images())
  File "/usr/lib/python3.10/asyncio/tasks.py", line 615, in ensure_future
    return _ensure_future(coro_or_future, loop=loop)
  File "/usr/lib/python3.10/asyncio/tasks.py", line 636, in _ensure_future
    return loop.create_task(coro_or_future)
Traceback (most recent call last):
  File "/usr/bin/gns3server", line 8, in <module>
    sys.exit(main())
  File "/usr/share/gns3/gns3-server/lib/python3.10/site-packages/gns3server/main.py", line 83, in main
    run()
  File "/usr/share/gns3/gns3-server/lib/python3.10/site-packages/gns3server/run.py", line 261, in run
    server.run()
  File "/usr/share/gns3/gns3-server/lib/python3.10/site-packages/gns3server/web/web_server.py", line 321, in run
    if self._run_application(self._handler, self._ssl_context) is False:
  File "/usr/share/gns3/gns3-server/lib/python3.10/site-packages/gns3server/web/web_server.py", line 86, in _run_application
    self._server, startup_res = self._loop.run_until_complete(asyncio.gather(srv, self._app.startup()))
  File "/usr/lib/python3.10/asyncio/base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 600, in run_forever
    self._run_once()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1888, in _run_once
    handle._run()
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/share/gns3/gns3-server/lib/python3.10/site-packages/gns3server/compute/base_manager.py", line 591, in list_images
    return list_images(self._NODE_TYPE)
  File "/usr/share/gns3/gns3-server/lib/python3.10/site-packages/gns3server/utils/images.py", line 83, in list_images
    "md5sum": md5sum(os.path.join(root, filename)),
  File "/usr/share/gns3/gns3-server/lib/python3.10/site-packages/gns3server/utils/images.py", line 178, in md5sum
    m.update(buf)
KeyboardInterrupt

Root user:
2023-05-31 13:23:59 INFO compute.py:364 Connecting to compute 'local'
2023-05-31 13:23:59 DEBUG compute.py:510 Attempting request to compute: GET http://127.0.0.1:3080/v2/compute/capabilities {'content-type': 'application/json'}
2023-05-31 13:23:59 INFO response.py:58 GET /v2/compute/capabilities
2023-05-31 13:23:59 DEBUG response.py:59 {'Host': '127.0.0.1:3080', 'Content-Type': 'application/json', 'Accept': '*/*', 'Accept-Encoding': 'gzip, deflate', 'User-Agent': 'Python/3.10 aiohttp/3.8.4'}
2023-05-31 13:23:59 DEBUG response.py:61 {}
2023-05-31 13:23:59 INFO response.py:62 Response: 200 OK
2023-05-31 13:23:59 DEBUG response.py:63 {'Connection': 'close', 'X-Route': '/v2/compute/capabilities', 'Server': 'Python/3.10 GNS3/2.2.39', 'Content-Type': 'application/json'}
2023-05-31 13:23:59 DEBUG response.py:65 {'node_types': ['cloud', 'ethernet_hub', 'ethernet_switch', 'nat', 'vpcs', 'virtualbox', 'dynamips', 'frame_relay_switch', 'atm_switch', 'qemu', 'vmware', 'traceng', 'docker', 'iou'], 'platform': 'linux', 'version': '2.2.39'}
2023-05-31 13:23:59 INFO web_log.py:206 127.0.0.1 [31/May/2023:13:23:59 +0000] "GET /v2/compute/capabilities HTTP/1.1" 200 553 "-" "Python/3.10 aiohttp/3.8.4"
2023-05-31 13:23:59 INFO notification_handler.py:50 New client has connected to compute WebSocket
2023-05-31 13:23:59 INFO compute.py:431 Connected to compute 'local' WebSocket 'http://127.0.0.1:3080/v2/compute/notifications/ws'

After CRTL+C
^C2023-05-31 13:24:01 WARNING web_server.py:170 Server has got signal SIGINT, exiting...
2023-05-31 13:24:01 INFO web_server.py:113 Closing 1 websocket connections...
2023-05-31 13:24:01 INFO compute.py:457 Connection closed to compute 'local' WebSocket 'http://127.0.0.1:3080/v2/compute/notifications/ws'
2023-05-31 13:24:01 INFO notification_handler.py:59 Client has disconnected from compute WebSocket
2023-05-31 13:24:01 INFO response.py:58 GET /v2/compute/notifications/ws
2023-05-31 13:24:01 DEBUG response.py:59 {'Host': '127.0.0.1:3080', 'Upgrade': 'websocket', 'Connection': 'upgrade', 'Sec-WebSocket-Version': '13', 'Sec-WebSocket-Key': 'JUspKOJVQ1kgY2uK9fhUiA==', 'Accept': '*/*', 'Accept-Encoding': 'gzip, deflate', 'User-Agent': 'Python/3.10 aiohttp/3.8.4'}
2023-05-31 13:24:01 DEBUG response.py:61 {}
2023-05-31 13:24:01 INFO response.py:62 Response: 200 OK
2023-05-31 13:24:01 DEBUG response.py:63 {'Connection': 'close', 'X-Route': '/v2/compute/notifications/ws', 'Server': 'Python/3.10 GNS3/2.2.39'}
2023-05-31 13:24:01 INFO web_log.py:206 127.0.0.1 [31/May/2023:13:23:59 +0000] "GET /v2/compute/notifications/ws HTTP/1.1" 200 0 "-" "Python/3.10 aiohttp/3.8.4"
2023-05-31 13:24:01 INFO __init__.py:146 Controller is stopping
2023-05-31 13:24:01 DEBUG web_server.py:130 Unloading module Builtin


[log_user_commom-2.txt](https://github.com/GNS3/gns3-server/files/11614737/log_user_commom-2.txt)
[log_user_root-2.txt](https://github.com/GNS3/gns3-server/files/11614738/log_user_root-2.txt)

**Comment by alexcama** [comment]
I think I already know what was going on. I had a hda in the form of a 1Tb img, I need it because it is for RHHI tests. finally when removing only this hda the connection returned to work in common user. when I went to check I saw that the md5sum of this hda did not exist, maybe it is a process that takes time because of the size of the hd. Anyway now everything is ok! Thank you for your help.

**Comment by grossmj** [comment]
> I think I already know what was going on. I had a hda in the form of a 1Tb img, I need it because it is for RHHI tests. finally when removing only this hda the connection returned to work in common user. when I went to check I saw that the md5sum of this hda did not exist, maybe it is a process that takes time because of the size of the hd. Anyway now everything is ok! Thank you for your help.

Indeed, I was about to point to the `File "/usr/share/gns3/gns3-server/lib/python3.10/site-packages/gns3server/utils/images.py", line 178, in md5sum` logs. I think we solved this problem in v3.0 (not blocking the server when it is calculating MD5 checksums). I will keep this open to remind me to check for v2. Thanks.

**Comment by grossmj** [comment]
I confirm MD5 calculation is blocking the server in v2. We should use something like https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.loop.run_in_executor for CPU-bound operations.

**Comment by nuqleo** [comment]
Hi,

I don't know is this real issue but after commit ae825b0080dd7b61e720f3d656e56b1b865c1800 I have problem with starting gns3server in unshare namespace. I have Fedora tree in fedora, running by regular user "unshare -mpfur --mount-proc -R fedora" then trying to start gns3server.

gns3server 2.2.43 starts fine
```
2023-11-06 17:42:44 INFO run.py:217 GNS3 server version 2.2.43
2023-11-06 17:42:44 INFO run.py:219 Copyright (c) 2007-2023 GNS3 Technologies Inc.
2023-11-06 17:42:44 INFO run.py:241 Running with Python 3.11.6 and has PID 23
2023-11-06 17:42:44 INFO run.py:77 Current locale is en_US.UTF-8
2023-11-06 17:42:44 INFO web_server.py:318 Starting server on 0.0.0.0:3080
2023-11-06 17:42:44 INFO __init__.py:69 Load controller configuration file /root/.config/GNS3/2.2/gns3_controller.conf
2023-11-06 17:42:44 INFO __init__.py:73 Controller is starting
2023-11-06 17:42:44 INFO __init__.py:310 Installing base configs in '/root/GNS3/configs'
2023-11-06 17:42:44 INFO __init__.py:323 Installing built-in disks in '/root/GNS3/images/QEMU'
2023-11-06 17:42:44 INFO __init__.py:251 Comparing controller version 2.2.43 with config version 2.2.44
2023-11-06 17:42:44 INFO compute.py:63 Create compute local
2023-11-06 17:42:44 INFO compute.py:363 Connecting to compute 'local'
2023-11-06 17:42:44 INFO web_log.py:206 127.0.0.1 [06/Nov/2023:15:42:44 +0000] "GET /v2/compute/capabilities HTTP/1.1" 200 553 "-" "Python/3.11 aiohttp/3.8.5"
2023-11-06 17:42:44 INFO notification_handler.py:50 New client has connected to compute WebSocket
2023-11-06 17:42:44 INFO compute.py:430 Connected to compute 'local' WebSocket 'http://127.0.0.1:3080/v2/compute/notifications/ws'
```
2.2.44 fails to start
```
2023-11-06 17:41:23 INFO run.py:217 GNS3 server version 2.2.44
2023-11-06 17:41:23 INFO run.py:219 Copyright (c) 2007-2023 GNS3 Technologies Inc.
2023-11-06 17:41:23 INFO run.py:241 Running with Python 3.11.6 and has PID 22
2023-11-06 17:41:23 INFO run.py:77 Current locale is en_US.UTF-8
2023-11-06 17:41:23 INFO web_server.py:332 Starting server on 0.0.0.0:3080
2023-11-06 17:41:23 INFO __init__.py:69 Load controller configuration file /root/.config/GNS3/2.2/gns3_controller.conf
2023-11-06 17:41:23 INFO __init__.py:73 Controller is starting
2023-11-06 17:41:23 INFO __init__.py:310 Installing base configs in '/root/GNS3/configs'
2023-11-06 17:41:23 INFO __init__.py:323 Installing built-in disks in '/root/GNS3/images/QEMU'
2023-11-06 17:41:23 INFO __init__.py:251 Comparing controller version 2.2.44 with config version 2.2.44
2023-11-06 17:41:23 INFO compute.py:63 Create compute local
2023-11-06 17:41:23 INFO compute.py:363 Connecting to compute 'local'
2023-11-06 17:41:23 INFO web_log.py:206 127.0.0.1 [06/Nov/2023:15:41:23 +0000] "GET /v2/compute/capabilities HTTP/1.1" 200 553 "-" "Python/3.11 aiohttp/3.8.5"
2023-11-06 17:41:23 CRITICAL web_server.py:89 Could not start the server: [Errno 2] No such file or directory

```

**Comment by grossmj** [comment]
@nuqleo thanks, this should be fixed now. I will release v2.2.44.1

**Comment by nuqleo** [comment]
2.2.44.1 also fails in unshare
```
2023-11-07 15:13:17 INFO run.py:217 GNS3 server version 2.2.44.1
2023-11-07 15:13:17 INFO run.py:219 Copyright (c) 2007-2023 GNS3 Technologies Inc.
2023-11-07 15:13:17 INFO run.py:241 Running with Python 3.9.16 and has PID 20
2023-11-07 15:13:17 INFO run.py:77 Current locale is ru_RU.UTF-8
2023-11-07 15:13:17 INFO web_server.py:338 Starting server on 0.0.0.0:3080
2023-11-07 15:13:17 INFO __init__.py:69 Load controller configuration file /root/.config/GNS3/2.2/gns3_controller.conf
2023-11-07 15:13:17 INFO __init__.py:73 Controller is starting
2023-11-07 15:13:17 INFO __init__.py:310 Installing base configs in '/root/GNS3/configs'
2023-11-07 15:13:17 INFO __init__.py:323 Installing built-in disks in '/root/GNS3/images/QEMU'
2023-11-07 15:13:17 INFO __init__.py:251 Comparing controller version 2.2.44.1 with config version None
2023-11-07 15:13:17 INFO appliance_manager.py:102 Installing built-in appliances in '/root/.local/share/GNS3/appliances'
2023-11-07 15:13:17 INFO compute.py:63 Create compute local
2023-11-07 15:13:17 INFO compute.py:363 Connecting to compute 'local'
2023-11-07 15:13:17 INFO web_log.py:206 127.0.0.1 [07/Nov/2023:13:13:17 +0000] "GET /v2/compute/capabilities HTTP/1.1" 200 556 "-" "Python/3.9 aiohttp/3.8.5"
2023-11-07 15:13:17 CRITICAL web_server.py:88 Could not start the server: [Errno 2] No such file or directory
```

**Comment by nuqleo** [comment]
2.2.44.1 works in unshare if I create /dev/shm directory.
