### ISSUE TITLE
Project Save bug is back.

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-server#224]
https://community.gns3.com/thread/8770

**Comment by noplay** [comment]
Perhaps we need to send the 409 to the crash system

It's perhaps the private config issue
Le 8 juin 2015 18:55, "Jeremy Grossmann" <notifications@github.com> a
écrit :

**Comment by grossmj** [comment]
I think we will be drowning in 409 errors if we do this ;)

I've started the investigation around the private-config issue and asked to try with the latest nightly build.

**Comment by grossmj** [comment]
I had a remote control on Don's PC and I confirmed, this is a bug related to the private-config save.

**Comment by grossmj** [comment]
Debug log:

```
?[32m2015-06-08 14:23:55 INFO router.py:1507 saving startup-config to configs/i1
_startup-config.cfg?[0m
?[31m2015-06-08 14:23:55 ERROR route.py:150 VM error detected: <class 'gns3serve
r.modules.dynamips.dynamips_error.DynamipsError'>
Traceback (most recent call last):
  File "./gns3-server\gns3server\modules\dynamips\nodes\router.py", line 1517, i
n save_configs
FileNotFoundError: [Errno 2] No such file or directory: 'F:\\GNS3\\projects\\tes
t\\project-files\\dynamips\\'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./gns3-server\gns3server\web\route.py", line 140, in control_schema
  File "./gns3-server\gns3server\handlers\api\project_handler.py", line 111, in
commit
  File "./gns3-server\gns3server\modules\project.py", line 401, in commit
  File "./gns3-server\gns3server\modules\dynamips\__init__.py", line 213, in pro
ject_committed
  File "./gns3-server\gns3server\modules\dynamips\nodes\router.py", line 1521, i
n save_configs
gns3server.modules.dynamips.dynamips_error.DynamipsError: Could not save the pri
vate configuration F:\GNS3\projects\test\project-files\dynamips\: [Errno 2] No s
uch file or directory: 'F:\\GNS3\\projects\\test\\project-files\\dynamips\\'?[0m

?[32m2015-06-08 14:23:55 INFO response.py:44 POST /v1/projects/af4976f5-14e6-4d0
7-98fe-e655319b4a38/commit?[0m
?[35m2015-06-08 14:23:55 DEBUG response.py:45 {'HOST': '127.0.0.1:8000', 'CONTEN
T-TYPE': 'application/json', 'USER-AGENT': 'GNS3 QT Client v1.3.5dev1', 'ACCEPT-
LANGUAGE': 'en-US,*', 'CONTENT-LENGTH': '2', 'ACCEPT-ENCODING': 'gzip', 'CONNECT
ION': 'Keep-Alive'}?[0m
?[35m2015-06-08 14:23:55 DEBUG response.py:47 {}?[0m
?[32m2015-06-08 14:23:55 INFO response.py:48 Response: 409 Conflict?[0m
?[35m2015-06-08 14:23:55 DEBUG response.py:49 {'SERVER': 'Python/3.4 GNS3/1.3.5d
ev1', 'X-ROUTE': '/v1/projects/{project_id}/commit', 'CONTENT-TYPE': 'applicatio
n/json', 'CONTENT-LENGTH': '236'}?[0m
?[35m2015-06-08 14:23:55 DEBUG response.py:51 {'status': 409, 'message': "Could
not save the private configuration F:\\GNS3\\projects\\test\\project-files\\dyna
mips\\: [Errno 2] No such file or directory: 'F:\\\\GNS3\\\\projects\\\\test\\\\
project-files\\\\dynamips\\\\'"}?[0m
```

@noplay looks like the syntax colorization is not fully disabled on Windows... See the ?[32m ?[0m etc. or is this another issue?

**Comment by grossmj** [comment]
The issue was indeed solved in https://github.com/GNS3/gns3-server/commit/02650fa4909e1e46832650a795c143e8104e7e34 but for some reason it didn't make it to the latest nightly build... I had to manually compile a dev version of find this out @noplay can you investigate?
