### ISSUE TITLE
Frozen local server  doesn't start

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-server#309]
```
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.4.3_2/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/cx_Freeze/initscripts/Console.py", line 27, in <module>
  File "gns3-server/gns3server/main.py", line 76, in <module>
  File "gns3-server/gns3server/main.py", line 71, in main
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/importlib/_bootstrap.py", line 2237, in _find_and_load
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/importlib/_bootstrap.py", line 2226, in _find_and_load_unlocked
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/importlib/_bootstrap.py", line 1191, in _load_unlocked
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/importlib/_bootstrap.py", line 1161, in _load_backward_compatible
  File "./gns3-server/gns3server/run.py", line 31, in <module>
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/importlib/_bootstrap.py", line 2237, in _find_and_load
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/importlib/_bootstrap.py", line 2226, in _find_and_load_unlocked
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/importlib/_bootstrap.py", line 1191, in _load_unlocked
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/importlib/_bootstrap.py", line 1161, in _load_backward_compatible
  File "./gns3-server/gns3server/server.py", line 39, in <module>
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/importlib/_bootstrap.py", line 2237, in _find_and_load
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/importlib/_bootstrap.py", line 2226, in _find_and_load_unlocked
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/importlib/_bootstrap.py", line 1191, in _load_unlocked
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/importlib/_bootstrap.py", line 1161, in _load_backward_compatible
  File "./gns3-server/gns3server/handlers/__init__.py", line 27, in <module>
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/importlib/_bootstrap.py", line 2237, in _find_and_load
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/importlib/_bootstrap.py", line 2226, in _find_and_load_unlocked
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/importlib/_bootstrap.py", line 1191, in _load_unlocked
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/importlib/_bootstrap.py", line 1161, in _load_backward_compatible
  File "./gns3-server/gns3server/handlers/api/docker_handler.py", line 21, in <module>
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/importlib/_bootstrap.py", line 2237, in _find_and_load
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/importlib/_bootstrap.py", line 2226, in _find_and_load_unlocked
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/importlib/_bootstrap.py", line 1191, in _load_unlocked
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/importlib/_bootstrap.py", line 1161, in _load_backward_compatible
  File "./gns3-server/gns3server/modules/docker/__init__.py", line 25, in <module>
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/importlib/_bootstrap.py", line 2237, in _find_and_load
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/importlib/_bootstrap.py", line 2226, in _find_and_load_unlocked
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/importlib/_bootstrap.py", line 1191, in _load_unlocked
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/importlib/_bootstrap.py", line 1161, in _load_backward_compatible
  File "/Users/gns3/Jenkins/shiningpanda/jobs/fbe7b18b/virtualenvs/d41d8cd9/lib/python3.4/site-packages/docker/__init__.py", line 20, in <module>
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/importlib/_bootstrap.py", line 2237, in _find_and_load
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/importlib/_bootstrap.py", line 2226, in _find_and_load_unlocked
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/importlib/_bootstrap.py", line 1191, in _load_unlocked
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/importlib/_bootstrap.py", line 1161, in _load_backward_compatible
  File "/Users/gns3/Jenkins/shiningpanda/jobs/fbe7b18b/virtualenvs/d41d8cd9/lib/python3.4/site-packages/docker/client.py", line 29, in <module>
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/importlib/_bootstrap.py", line 2237, in _find_and_load
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/importlib/_bootstrap.py", line 2226, in _find_and_load_unlocked
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/importlib/_bootstrap.py", line 1191, in _load_unlocked
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/importlib/_bootstrap.py", line 1161, in _load_backward_compatible
  File "/Users/gns3/Jenkins/shiningpanda/jobs/fbe7b18b/virtualenvs/d41d8cd9/lib/python3.4/site-packages/docker/auth/__init__.py", line 1, in <module>
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/importlib/_bootstrap.py", line 2237, in _find_and_load
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/importlib/_bootstrap.py", line 2226, in _find_and_load_unlocked
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/importlib/_bootstrap.py", line 1191, in _load_unlocked
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/importlib/_bootstrap.py", line 1161, in _load_backward_compatible
  File "/Users/gns3/Jenkins/shiningpanda/jobs/fbe7b18b/virtualenvs/d41d8cd9/lib/python3.4/site-packages/docker/auth/auth.py", line 22, in <module>
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/importlib/_bootstrap.py", line 2237, in _find_and_load
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/importlib/_bootstrap.py", line 2226, in _find_and_load_unlocked
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/importlib/_bootstrap.py", line 1191, in _load_unlocked
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/importlib/_bootstrap.py", line 1161, in _load_backward_compatible
  File "/Users/gns3/Jenkins/shiningpanda/jobs/fbe7b18b/virtualenvs/d41d8cd9/lib/python3.4/site-packages/docker/utils/__init__.py", line 1, in <module>
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/importlib/_bootstrap.py", line 2237, in _find_and_load
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/importlib/_bootstrap.py", line 2226, in _find_and_load_unlocked
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/importlib/_bootstrap.py", line 1191, in _load_unlocked
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/importlib/_bootstrap.py", line 1161, in _load_backward_compatible
  File "/Users/gns3/Jenkins/shiningpanda/jobs/fbe7b18b/virtualenvs/d41d8cd9/lib/python3.4/site-packages/docker/utils/utils.py", line 22, in <module>
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/importlib/_bootstrap.py", line 2237, in _find_and_load
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/importlib/_bootstrap.py", line 2212, in _find_and_load_unlocked
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/importlib/_bootstrap.py", line 321, in _call_with_frames_removed
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/importlib/_bootstrap.py", line 2237, in _find_and_load
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/importlib/_bootstrap.py", line 2226, in _find_and_load_unlocked
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/importlib/_bootstrap.py", line 1191, in _load_unlocked
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/importlib/_bootstrap.py", line 1161, in _load_backward_compatible
  File "/Users/gns3/Jenkins/shiningpanda/jobs/fbe7b18b/virtualenvs/d41d8cd9/lib/python3.4/distutils/__init__.py", line 25, in <module>
ImportError: cannot import name 'dist'
```

**Comment by noplay** [comment]
http://stackoverflow.com/questions/14247130/cxfreeze-missing-distutils-module-inside-virtualenv

**Comment by noplay** [comment]
The issue is trigger by the need of distutils for this:
https://github.com/docker/docker-py/blob/master/docker/ssladapter/ssladapter.py#L5

**Comment by noplay** [comment]
We need the virtualenv on the build machine in order to have a clean envirronement

**Comment by noplay** [comment]
Wow the workaround!
https://gist.github.com/nicoddemus/ca0acd93a20acbc42d1d
