### ISSUE TITLE
Exception with Docker container

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-server#382]
Just drag & dropped a Docker container on the scene, tried to start it and exited the GUI.

```
2015-12-24 16:56:53 INFO servers.py:554 Stopping local server (PID=6661)
Stopping local server (PID=6661)
Exception ignored in: <bound method UnixConnector.__del__ of <aiohttp.connector.UnixConnector object at 0x7f46147d0a90>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/aiohttp/connector.py", line 160, in __del__
  File "/usr/lib/python3.4/asyncio/base_events.py", line 1037, in call_exception_handler
  File "/usr/lib/python3.4/logging/__init__.py", line 1303, in error
  File "/usr/lib/python3.4/logging/__init__.py", line 1409, in _log
  File "/usr/lib/python3.4/logging/__init__.py", line 1419, in handle
  File "/usr/lib/python3.4/logging/__init__.py", line 1481, in callHandlers
  File "/usr/lib/python3.4/logging/__init__.py", line 853, in handle
  File "/usr/lib/python3.4/logging/__init__.py", line 1040, in emit
  File "/usr/lib/python3.4/logging/__init__.py", line 1030, in _open
NameError: name 'open' is not defined
Exception ignored in: 
Process finished with exit code 0
```

**Comment by noplay** [comment]
Seem to be something internal to python :(

**Comment by noplay** [comment]
Another traceback:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/aiohttp/connector.py", line 152, in __del__
  File "/usr/local/lib/python3.4/dist-packages/aiohttp/connector.py", line 152, in <listcomp>
  File "/usr/lib/python3.4/asyncio/selector_events.py", line 540, in __repr__
  File "/usr/lib/python3.4/asyncio/selector_events.py", line 35, in _test_selector_event
AttributeError: 'NoneType' object has no attribute 'get_key'
```

**Comment by noplay** [comment]
Seem to be patch in more recent version of aiohttp
https://github.com/python/asyncio/commit/15a569d29b6ea60ebf9716117702e22d87ae638d

**Comment by noplay** [comment]
If I modify my Python source code with the patch the error is different:
```
2015-12-29 11:26:15 ERROR base_events.py:1008 Unclosed connector
connections: ['[(<_SelectorSocketTransport fd=12>, <aiohttp.parsers.StreamProtocol object at 0x7fb25c8c7438>, 1408.747017717)]']
connector: <aiohttp.connector.UnixConnector object at 0x7fb25d2ad438>
source_traceback: Object created at (most recent call last):
  File "gns3server/main.py", line 76, in <module>
    main()
  File "gns3server/main.py", line 72, in main
    run()
  File "/gns3-server/gns3server/run.py", line 232, in run
    server.run()
  File "/gns3-server/gns3server/server.py", line 235, in run
    m = module.instance()
  File "/gns3-server/gns3server/modules/base_manager.py", line 71, in instance
    cls._instance = cls()
  File "/gns3-server/gns3server/modules/docker/__init__.py", line 43, in __init__
    self._connector = aiohttp.connector.UnixConnector(self._server_url)
  File "/usr/local/lib/python3.4/dist-packages/aiohttp/connector.py", line 722, in __init__
    super().__init__(**kwargs)
Connection to 127.0.0.1 closed.
```
