### ISSUE TITLE
Traceback when starting Docker container

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-server#383]
Tried to start an Ubuntu Docker container.

```
Server error from http://127.0.0.1:8000: ubuntu-1: Traceback (most recent call last):
  File "/home/grossmj/PycharmProjects/gns3-server/gns3server/web/route.py", line 179, in control_schema
    yield from func(request, response)
  File "/home/grossmj/PycharmProjects/gns3-server/gns3server/handlers/api/docker_handler.py", line 101, in start
    yield from container.start()
  File "/home/grossmj/PycharmProjects/gns3-server/gns3server/modules/docker/docker_vm.py", line 175, in start
    yield from self._start_console()
  File "/home/grossmj/PycharmProjects/gns3-server/gns3server/modules/docker/docker_vm.py", line 205, in _start_console
    ws = yield from self.manager.websocket_query("containers/{}/attach/ws?stream=1&stdin=1&stdout=1&stderr=1".format(self._cid))
  File "/home/grossmj/PycharmProjects/gns3-server/gns3server/modules/docker/__init__.py", line 109, in websocket_query
    autoping=True)
TypeError: ws_connect() got an unexpected keyword argument 'origin'
```

**Comment by noplay** [comment]
You need last aiohttp. When you setup.py it should make the upgrade.

Le ven. 25 déc. 2015 01:05, Jeremy Grossmann <notifications@github.com> a
écrit :

**Comment by grossmj** [comment]
```
$ pip3 freeze | grep aiohttp
aiohttp==0.17.2
```

I have version 0.17.2, the issue remains.

**Comment by noplay** [comment]
It should be 0.19 previous doens't support docker websocket

Le lun. 28 déc. 2015 05:14, Jeremy Grossmann <notifications@github.com> a
écrit :

**Comment by noplay** [comment]
https://github.com/GNS3/gns3-server/blob/1.5/requirements.txt
