### ISSUE TITLE
Building GNS3 1.5 nightly build: Installation issue with psutil

### ISSUE THREAD

**Issue by AJNOURI** [GNS3/gns3-server#397]
GNS3 server complaining about psutil version, and suggest installtion via apt, though installed the latest psutils for python 3.4
Is there an apt package for 1.5?

ajn:~/Downloads/gns3-1.5/gns3-server-1.5$ **sudo gns3server**

    Traceback (most recent call last):
    File "/usr/local/bin/gns3server", line 9, in 
    load_entry_point('gns3-server==1.5.0dev1', 'console_scripts', 'gns3server')()
    File "/usr/local/lib/python3.4/dist-packages/gns3_server-1.5.0dev1-py3.4.egg/gns3server/main.py", line 71, in main
    from gns3server.run import run
    File "/usr/local/lib/python3.4/dist-packages/gns3_server-1.5.0dev1-py3.4.egg/gns3server/run.py", line 31, in
    from gns3server.server import Server
    File "/usr/local/lib/python3.4/dist-packages/gns3_server-1.5.0dev1-py3.4.egg/gns3server/server.py", line 32, in 
    from .web.route import Route
    File "/usr/local/lib/python3.4/dist-packages/gns3_server-1.5.0dev1-py3.4.egg/gns3server/web/route.py", line 28, in 
    from ..modules.vm_error import VMError
    File "/usr/local/lib/python3.4/dist-packages/gns3_server-1.5.0dev1-py3.4.egg/gns3server/modules/init.py", line 20, in 
    from .vpcs import VPCS
    File "/usr/local/lib/python3.4/dist-packages/gns3_server-1.5.0dev1-py3.4.egg/gns3server/modules/vpcs/init.py", line 25, in 
    from ..base_manager import BaseManager
    File "/usr/local/lib/python3.4/dist-packages/gns3_server-1.5.0dev1-py3.4.egg/gns3server/modules/base_manager.py", line 32, in 
    from gns3server.utils.interfaces import is_interface_up
    File "/usr/local/lib/python3.4/dist-packages/gns3_server-1.5.0dev1-py3.4.egg/gns3server/utils/interfaces.py", line 26, in 
    raise Exception("psutil version should >= 3.0.0. If you are under ubuntu/debian install gns3 via apt instead of pip")
    Exception: psutil version should >= 3.0.0. If you are under ubuntu/debian install gns3 via apt instead of pip

ajn:~/Downloads/psutil-3.4.1$ **sudo python3 setup.py install**

    running install
    ...
    Installed /usr/local/lib/python3.4/dist-packages/psutil-3.4.1-py3.4-linux-x86_64.egg
    Processing dependencies for psutil==3.4.1
    Finished processing dependencies for psutil==3.4.1
    ajn:~/Downloads/psutil-3.4.1$

**Comment by noplay** [comment]
If I correctly remember it's a conflict where python getting lost between
psutils from apt and psutils from pip. You can try to remove the apt-get
version with apt-get remove python3-psutil

**Comment by AJNOURI** [comment]
Thanks Julien. Removing the apt-get version with **apt-get remove python3-psutil** solved the issue.

**Comment by noplay** [comment]
The joy of packages :D
