### ISSUE TITLE
Version 1.5 Nightly build: Bug when reading docker images

### ISSUE THREAD

**Issue by AJNOURI** [GNS3/gns3-server#398]
This appear when creating new docker VM template:

    2016-01-18 20:32:04 INFO http_client.py:669 Response error: Error downloading http://Thswfu0Hstf0xInRfWeHvpVJ44xeNOeiDgswmQkaaHgOcF72lzmgtCeXktygxxdT@127.0.0.1:8000/v1/docker/images - server replied: Internal Server Error (error: 299)
    2016-01-18 20:32:04 CRITICAL qt.py:132 Traceback (most recent call last):
      File "/usr/local/lib/python3.4/dist-packages/gns3_server-1.5.0dev1-py3.4.egg/gns3server/web/route.py", line 179, in control_schema
        yield from func(request, response)
      File "/usr/local/lib/python3.4/dist-packages/gns3_server-1.5.0dev1-py3.4.egg/gns3server/handlers/api/docker_handler.py", line 45, in show
        images = yield from docker_manager.list_images()
      File "/usr/local/lib/python3.4/dist-packages/gns3_server-1.5.0dev1-py3.4.egg/gns3server/modules/docker/__init__.py", line 136, in list_images
        for image in (yield from self.query("GET", "images/json", params={"all": 0})):
      File "/usr/local/lib/python3.4/dist-packages/gns3_server-1.5.0dev1-py3.4.egg/gns3server/modules/docker/__init__.py", line 73, in query
        response = yield from self.http_query(method, path, data=data, params=params)
      File "/usr/local/lib/python3.4/dist-packages/gns3_server-1.5.0dev1-py3.4.egg/gns3server/modules/docker/__init__.py", line 96, in http_query
        connector=(yield from self.connector()),
    ...
      File "/usr/local/lib/python3.4/dist-packages/aiohttp-0.19.0-py3.4-linux-x86_64.egg/aiohttp/connector.py", line 717, in __init__
        super().__init__(**kwargs)
      File "/usr/local/lib/python3.4/dist-packages/aiohttp-0.19.0-py3.4-linux-x86_64.egg/aiohttp/connector.py", line 123, in __init__
        self._source_traceback = traceback.extract_stack(sys._getframe(1))
      File "/usr/lib/python3.4/traceback.py", line 301, in extract_stack
        stack = list(_extract_stack_iter(_get_stack(f), limit=limit))
      File "/usr/lib/python3.4/traceback.py", line 59, in _extract_tb_or_stack_iter
        f, lineno, next_item = extractor(curr)
    RuntimeError: maximum recursion depth exceeded

![image](https://cloud.githubusercontent.com/assets/1716020/12400952/79377444-be23-11e5-938c-5ea20c4c8470.png)

**Comment by noplay** [comment]
Thanks I will look at it.

**Comment by noplay** [comment]
Fixed
