### ISSUE TITLE
AttributeError: module 'aiohttp' has no attribute 'Timeout' in 2.0

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-server#463]
https://app.getsentry.com/gns3/gns3-server/issues/119471103/

```
AttributeError: module 'aiohttp' has no attribute 'Timeout'
(3 additional frame(s) were not displayed)
...
  File "./gns3-server/gns3server/controller/project.py", line 74, in addHypervisor
  File "./gns3-server/gns3server/controller/hypervisor.py", line 195, in post
  File "./gns3-server/gns3server/controller/hypervisor.py", line 119, in httpQuery
  File "./gns3-server/gns3server/controller/hypervisor.py", line 128, in _connect
  File "./gns3-server/gns3server/controller/hypervisor.py", line 159, in _runHttpQuery
```

**Comment by noplay** [comment]
It seem an issue with the mac build that don't reinstall the correct version of packages

**Comment by noplay** [comment]
Fixed in build process

**Comment by fcolista** [comment]
Seems that there's a regression with py-aiohttp version 3.0.1.
```
Traceback (most recent call last):
  File "/usr/bin/gns3server", line 11, in <module>
    load_entry_point('gns3-server==2.1.3', 'console_scripts', 'gns3server')()
  File "/usr/lib/python3.6/site-packages/gns3server/main.py", line 82, in main
    from gns3server.run import run
  File "/usr/lib/python3.6/site-packages/gns3server/run.py", line 32, in <module>
    from gns3server.web.web_server import WebServer
  File "/usr/lib/python3.6/site-packages/gns3server/web/web_server.py", line 32, in <module>
    from .route import Route
  File "/usr/lib/python3.6/site-packages/gns3server/web/route.py", line 31, in <module>
    from ..controller.controller_error import ControllerError
  File "/usr/lib/python3.6/site-packages/gns3server/controller/__init__.py", line 28, in <module>
    from .project import Project
  File "/usr/lib/python3.6/site-packages/gns3server/controller/project.py", line 30, in <module>
    from .node import Node
  File "/usr/lib/python3.6/site-packages/gns3server/controller/node.py", line 26, in <module>
    from .compute import ComputeConflict, ComputeError
  File "/usr/lib/python3.6/site-packages/gns3server/controller/compute.py", line 55, in <module>
    class Timeout(aiohttp.Timeout):
AttributeError: module 'aiohttp' has no attribute 'Timeout'
```

**Comment by fcolista** [comment]
In the new aiohttp version is stated:
"Drop aiohttp.Timeout and use async_timeout.timeout instead. (#2348)"

I think that i need to add a feature request to support newer aiohttp version.
