### ISSUE TITLE
GNS3->QEMU->Configure->Network->Base MAC

### ISSUE THREAD

**Issue by Rigamaroo** [GNS3/gns3-server#501]
When setting the MAC address for a QEMU host, using hex digits "A" through "F" as the last digit (least significant) appears to cause errors.  This is the result when I configure an address of 00:0c:29:11:b0:0a and start the emulation.

Server error from http://127.0.0.1:8000: QemuHost-1: Traceback (most recent call last):
  File "/usr/share/gns3/gns3-server/lib/python3.4/site-packages/gns3server/web/route.py", line 179, in control_schema
    yield from func(request, response)
  File "/usr/share/gns3/gns3-server/lib/python3.4/site-packages/gns3server/handlers/api/qemu_handler.py", line 164, in start
    yield from vm.start()
  File "/usr/share/gns3/gns3-server/lib/python3.4/site-packages/gns3server/modules/qemu/qemu_vm.py", line 869, in start
    command = yield from self._build_command()
  File "/usr/share/gns3/gns3-server/lib/python3.4/site-packages/gns3server/modules/qemu/qemu_vm.py", line 1482, in _build_command
    command.extend((yield from self._network_options()))
  File "/usr/share/gns3/gns3-server/lib/python3.4/site-packages/gns3server/modules/qemu/qemu_vm.py", line 1377, in _network_options
    mac = "%s%02x" % (self._mac_address[:-2], (int(self._mac_address[-2:]) + adapter_number) % 255)
ValueError: invalid literal for int() with base 10: '0a'

**Comment by noplay** [comment]
I confirm the problem.

**Comment by noplay** [comment]
Thanks for the report it's fixed now
