### ISSUE TITLE
Docker permission not reset, when command in docker exits

### ISSUE THREAD

**Issue by ehlers** [GNS3/gns3-server#576]
GNS3 V1.5 commit https://github.com/GNS3/gns3-server/commit/e82862c69f582beb2468dc6feaa7cfe280eb4c98

Normally when a docker container is halted, the permissions of the volume directories are saved and then reset to the und/gid of the gns3-server. When a docker container is not haltet by GNS3, but exits (normally or abnormally), then this save permission function can't run. The volume directories are still owned by root.

```
gns3@gns3vm:~/gns3-server$ ls -lt /opt/gns3/projects/e6de5e2e-58cd-4859-a8b1-cd915554d074/project-files/docker/5513293c-ca64-4c2a-886c-5ffae9f5b548/
total 8
drwx------ 2 root root 4096 Jun 15 08:39 root/
drwxrwx--- 3 gns3 gns3 4096 Jun 15 08:39 etc/
```

When this is a temporary directory, this root owned files can't be deleted on project close and they remain as leftovers.

```
gns3@gns3vm:~/gns3-server$ ls -l /opt/gns3/projects/e6de5e2e-58cd-4859-a8b1-cd915554d074/project-files/docker/5513293c-ca64-4c2a-886c-5ffae9f5b548/
total 4
drwx------ 2 root root 4096 Jun 15 08:39 root/
```

When you now stop, then start the GNS3 server it tries delete leftover temporary projects on start of the server. Because of the permission problem, this won't work. But this time this is fatal:

```
Traceback (most recent call last):
  File "/usr/local/bin/gns3server", line 9, in <module>
    load_entry_point('gns3-server==1.5.0dev5', 'console_scripts', 'gns3server')()
  File "/usr/local/lib/python3.4/dist-packages/gns3_server-1.5.0dev5-py3.4.egg/gns3server/main.py", line 72, in main
    run()
  File "/usr/local/lib/python3.4/dist-packages/gns3_server-1.5.0dev5-py3.4.egg/gns3server/run.py", line 230, in run
    Project.clean_project_directory()
  File "/usr/local/lib/python3.4/dist-packages/gns3_server-1.5.0dev5-py3.4.egg/gns3server/modules/project.py", line 437, in clean_project_directory
    shutil.rmtree(path)
  File "/usr/lib/python3.4/shutil.py", line 463, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/usr/lib/python3.4/shutil.py", line 401, in _rmtree_safe_fd
    _rmtree_safe_fd(dirfd, fullname, onerror)
  File "/usr/lib/python3.4/shutil.py", line 401, in _rmtree_safe_fd
    _rmtree_safe_fd(dirfd, fullname, onerror)
  File "/usr/lib/python3.4/shutil.py", line 401, in _rmtree_safe_fd
    _rmtree_safe_fd(dirfd, fullname, onerror)
  File "/usr/lib/python3.4/shutil.py", line 397, in _rmtree_safe_fd
    onerror(os.open, fullname, sys.exc_info())
  File "/usr/lib/python3.4/shutil.py", line 395, in _rmtree_safe_fd
    dirfd = os.open(name, os.O_RDONLY, dir_fd=topfd)
PermissionError: [Errno 13] Permission denied: 'root'
```

I think It will be difficult to avoid this leftovers, but this permission error on server startup should not be fatal.

**Comment by noplay** [comment]
Right exception catched (not tested yet)

**Comment by noplay** [comment]
Confirmed it's no longer crash
