### ISSUE TITLE
Packet capture file streaming is not correctly stopped when closing server

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-server#592]
```
2016-06-23 16:48:36 ERROR base_events.py:1008 Task exception was never retrieved
future: <Task finished coro=<_start_streaming_pcap() done, defined at /home/grossmj/PycharmProjects/gns3-server/gns3server/controller/link.py:89> exception=<HTTPNotFound Not Found not started> created at /home/grossmj/PycharmProjects/gns3-server/gns3server/controller/link.py:86>
source_traceback: Object created at (most recent call last):
  File "/usr/local/bin/gns3server", line 9, in <module>
    load_entry_point('gns3-server==2.0.0dev1', 'console_scripts', 'gns3server')()
  File "/home/grossmj/PycharmProjects/gns3-server/gns3server/main.py", line 79, in main
    run()
  File "/home/grossmj/PycharmProjects/gns3-server/gns3server/run.py", line 233, in run
    server.run()
  File "/home/grossmj/PycharmProjects/gns3-server/gns3server/web/web_server.py", line 308, in run
    self._loop.run_forever()
  File "/usr/lib/python3.4/asyncio/base_events.py", line 276, in run_forever
    self._run_once()
  File "/usr/lib/python3.4/asyncio/base_events.py", line 1164, in _run_once
    handle._run()
  File "/usr/lib/python3.4/asyncio/events.py", line 120, in _run
    self._callback(*self._args)
  File "/usr/lib/python3.4/asyncio/tasks.py", line 292, in _wakeup
    self._step(value, None)
  File "/usr/lib/python3.4/asyncio/tasks.py", line 236, in _step
    result = coro.send(value)
  File "/usr/local/lib/python3.4/dist-packages/aiohttp/server.py", line 266, in start
    yield from self.handle_request(message, payload)
  File "/usr/local/lib/python3.4/dist-packages/aiohttp/web.py", line 90, in handle_request
    resp = yield from handler(request)
  File "/home/grossmj/PycharmProjects/gns3-server/gns3server/web/route.py", line 267, in node_concurrency
    response = yield from control_schema(request)
  File "/home/grossmj/PycharmProjects/gns3-server/gns3server/web/route.py", line 186, in control_schema
    yield from func(request, response)
  File "/home/grossmj/PycharmProjects/gns3-server/gns3server/handlers/api/controller/link_handler.py", line 92, in start_capture
    yield from link.start_capture(data_link_type=request.json.get("data_link_type", "DLT_EN10MB"), capture_file_name=request.json.get("capture_file_name"))
  File "/home/grossmj/PycharmProjects/gns3-server/gns3server/controller/udp_link.py", line 102, in start_capture
    yield from super().start_capture(data_link_type=data_link_type, capture_file_name=capture_file_name)
  File "/usr/lib/python3.4/asyncio/coroutines.py", line 141, in coro
    res = func(*args, **kw)
  File "/home/grossmj/PycharmProjects/gns3-server/gns3server/controller/link.py", line 86, in start_capture
    self._streaming_pcap = asyncio.async(self._start_streaming_pcap())
Traceback (most recent call last):
  File "/usr/lib/python3.4/asyncio/tasks.py", line 236, in _step
    result = coro.send(value)
  File "/home/grossmj/PycharmProjects/gns3-server/gns3server/controller/link.py", line 95, in _start_streaming_pcap
    stream = yield from self.read_pcap_from_source()
  File "/usr/lib/python3.4/asyncio/coroutines.py", line 143, in coro
    res = yield from res
  File "/home/grossmj/PycharmProjects/gns3-server/gns3server/controller/compute.py", line 266, in steam_file
    raise aiohttp.web.HTTPNotFound(text="{} not found on compute".format(path))
aiohttp.web_exceptions.HTTPNotFound: Not Found
2016-06-23 16:48:36 ERROR base_events.py:1008 Unclosed response
```

**Comment by grossmj** [comment]
Tested with Qemu

**Comment by noplay** [comment]
I have no idea how to handle that :(

**Comment by noplay** [comment]
I think the most clean is to use a with context in order to have the query auto close.

But it's supported only in Python 3.5:
https://www.python.org/dev/peps/pep-0492/

We will need to find a tricks to use that with Python 3.4
