### ISSUE TITLE
[2.0] Traceback with fresh install of GNS3 2.0 branch of gns3-server

### ISSUE THREAD

**Issue by gcasella** [GNS3/gns3-server#598]
Hi,

I received the following traceback message on a fresh install of GNS3 2.0 on Fedora 24.

gns3server --version

Traceback (most recent call last):
  File "/usr/bin/gns3server", line 9, in <module>
    load_entry_point('gns3-server==2.0.0.dev1', 'console_scripts', 'gns3server')()
  File "/usr/lib/python3.5/site-packages/gns3_server-2.0.0.dev1-py3.5.egg/gns3server/main.py", line 78, in main
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/usr/lib/python3.5/site-packages/gns3_server-2.0.0.dev1-py3.5.egg/gns3server/run.py", line 33, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/usr/lib/python3.5/site-packages/gns3_server-2.0.0.dev1-py3.5.egg/gns3server/web/web_server.py", line 36, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/usr/lib/python3.5/site-packages/gns3_server-2.0.0.dev1-py3.5.egg/gns3server/web/route.py", line 31, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/usr/lib/python3.5/site-packages/gns3_server-2.0.0.dev1-py3.5.egg/gns3server/web/response.py", line 30, in <module>
  File "/usr/lib/python3.5/site-packages/Jinja2-2.8-py3.5.egg/jinja2/loaders.py", line 163, in __init__
    self.searchpath = list(searchpath)
TypeError: 'NoneType' object is not iterable

**Comment by noplay** [comment]
Seem to be a side effect of deb97f8ec005f6906031ccbdb3338beb8d750c54

**Comment by noplay** [comment]
Fixed
