### ISSUE TITLE
Error not forwarded from compute to client

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-server#615]
Using the following command: ``curl -X GET 'http://127.0.0.1:3080/v2/computes/local/network/interfaces'``

```
2016-07-10 11:13:26 ERROR route.py:226 Uncaught exception detected: <class 'AttributeError'>
Traceback (most recent call last):
  File "/home/grossmj/PycharmProjects/gns3-server/gns3server/web/route.py", line 186, in control_schema
    yield from func(request, response)
  File "/home/grossmj/PycharmProjects/gns3-server/gns3server/handlers/api/controller/compute_handler.py", line 109, in get_forward
    res = yield from compute.forward("GET", request.match_info["emulator"], request.match_info["action"])
  File "/home/grossmj/PycharmProjects/gns3-server/gns3server/controller/compute.py", line 422, in forward
    return res.json
AttributeError: 'NoneType' object has no attribute 'json'
```

**Comment by grossmj** [comment]
Well, it is because an emulator name is expected. I tricked it by renaming the entry point I was trying to use. Nonetheless, more checks should be done before forwarding a request to a compute server. Invalid requests should not raise these kind of exceptions.

**Comment by noplay** [comment]
The aiohttp with Timeout catched the exception.

**Comment by noplay** [comment]
It's fixed
