### ISSUE TITLE
Exception with WebSocket

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-server#635]
```
2016-08-20 10:14:21 INFO local_config.py:337 Section MainWindow has changed. Saving configuration
2016-08-20 10:14:21 INFO local_config.py:215 Configuration save to /home/grossmj/.config/GNS3/gns3_gui.conf
2016-08-20 10:14:21 INFO local_server.py:455 Stopping local server (PID=6912)
Exception ignored in: <bound method _GatheringFuture.__del__ of <_GatheringFuture finished exception=WSServerHandshakeError("401, message='Invalid response status'",) created at /usr/lib/python3.4/asyncio/tasks.py:528>>
Traceback (most recent call last):
  File "/usr/lib/python3.4/asyncio/futures.py", line 216, in __del__
  File "/usr/lib/python3.4/asyncio/base_events.py", line 1037, in call_exception_handler
  File "/usr/lib/python3.4/logging/__init__.py", line 1303, in error
  File "/usr/lib/python3.4/logging/__init__.py", line 1409, in _log
  File "/usr/lib/python3.4/logging/__init__.py", line 1419, in handle
  File "/usr/lib/python3.4/logging/__init__.py", line 1481, in callHandlers
  File "/usr/lib/python3.4/logging/__init__.py", line 853, in handle
  File "/usr/lib/python3.4/logging/__init__.py", line 1040, in emit
  File "/usr/lib/python3.4/logging/__init__.py", line 1030, in _open
NameError: name 'open' is not defined

Process finished with exit code 0
```

Something wrong with closing the Websocket. To reproduce: start GNS3, drop a node and then close the GUI.

**Comment by noplay** [comment]
I didn't replicate the issue on Mac or Linux (Xenial with Python 3.5)

Some people complaints about that in Python issues:
https://bugs.python.org/issue26789

But I guess I found the real problem.
