### ISSUE TITLE
[1.5] Deleting running telnet docker VM shows error in log

### ISSUE THREAD

**Issue by ehlers** [GNS3/gns3-server#662]
GNS3 version latest 1.5.3dev1 on Darwin (64-bit) with Python 3.5.2 Qt 5.6.0, docker in self made GNS3-VM with python 3.5.2

When deleting a running docker VM the log shows some errors, on the GUI everything look fine, no output in the console.  If I start, then stop, then delete the VM, all is fine. I have seen this error only on VMs with telnet console, VMs with GUI are looking fine. It happens also before https://github.com/GNS3/gns3-server/commit/07b982d4dbde6c7d59c85f3c3adb24938a8cbd5b.

Here the log output when starting, then deleting an pure alpine docker VM:
```
2016-09-01 09:54:26 INFO docker_vm.py:780 Docker container "alpine-1" [94effe26-1112-4b77-8b3e-29a8ea2e730e]: number of Ethernet adapters changed to 1
2016-09-01 09:54:26 INFO docker_vm.py:313 Docker container 'alpine-1' [94effe26-1112-4b77-8b3e-29a8ea2e730e] created
2016-09-01 09:54:26 INFO helpers.py:365 192.168.1.10 - - [01/Sep/2016:07:54:26 +0000] "POST /v1/projects/b4f3b796-7c3e-4927-a815-2b65f97dea25/docker/vms HTTP/1.1" 201 633 "-" "GNS3 QT Client v1.5.3dev1"
2016-09-01 09:54:29 INFO base_vm.py:425 Starting new uBridge hypervisor 0.0.0.0:35821
2016-09-01 09:54:29 INFO hypervisor.py:152 starting ubridge: ['/usr/local/bin/ubridge', '-H', '0.0.0.0:35821']
2016-09-01 09:54:29 INFO hypervisor.py:154 logging to /opt/gns3/projects/b4f3b796-7c3e-4927-a815-2b65f97dea25/project-files/docker/94effe26-1112-4b77-8b3e-29a8ea2e730e/ubridge.log
2016-09-01 09:54:29 INFO hypervisor.py:162 ubridge started PID=5570
2016-09-01 09:54:29 INFO base_vm.py:427 Hypervisor 0.0.0.0:35821 has successfully started
2016-09-01 09:54:29 INFO ubridge_hypervisor.py:84 Connected to uBridge hypervisor after 0.0146 seconds
2016-09-01 09:54:29 INFO docker_vm.py:372 Docker container 'alpine-1' [alpine:latest] started listen for telnet on 5000
2016-09-01 09:54:29 INFO helpers.py:365 192.168.1.10 - - [01/Sep/2016:07:54:29 +0000] "POST /v1/projects/b4f3b796-7c3e-4927-a815-2b65f97dea25/docker/vms/94effe26-1112-4b77-8b3e-29a8ea2e730e/start HTTP/1.1" 204 0 "-" "GNS3 QT Client v1.5.3dev1"
2016-09-01 09:54:35 INFO base_vm.py:264 Docker: 'alpine-1' [94effe26-1112-4b77-8b3e-29a8ea2e730e]: is closing
2016-09-01 09:54:35 INFO hypervisor.py:186 Stopping uBridge process PID=5570
2016-09-01 09:54:40 INFO docker_vm.py:543 Docker container 'alpine-1' [alpine:latest] stopped
2016-09-01 09:54:40 INFO docker_vm.py:599 Docker container 'alpine-1' [alpine:latest] removed
2016-09-01 09:54:40 ERROR base_events.py:1168 Task exception was never retrieved
future: <Task finished coro=<DockerVM._read_console_output() done, defined at /usr/local/lib/python3.5/dist-packages/gns3_server-1.5.3.dev1-py3.5.egg/gns3server/modules/docker/docker_vm.py:475> exception=Docker has returned an error: 404 No such container: 840fc32a0c2e59196532fa295217e0507777c7c57a37b81edbcdfdb162ba8470 created at /usr/lib/python3.5/asyncio/tasks.py:532>
source_traceback: Object created at (most recent call last):
  File "/usr/local/bin/gns3server", line 9, in <module>
    load_entry_point('gns3-server==1.5.3.dev1', 'console_scripts', 'gns3server')()
  File "/usr/local/lib/python3.5/dist-packages/gns3_server-1.5.3.dev1-py3.5.egg/gns3server/main.py", line 72, in main
    run()
  File "/usr/local/lib/python3.5/dist-packages/gns3_server-1.5.3.dev1-py3.5.egg/gns3server/run.py", line 255, in run
    server.run()
  File "/usr/local/lib/python3.5/dist-packages/gns3_server-1.5.3.dev1-py3.5.egg/gns3server/server.py", line 256, in run
    self._loop.run_forever()
  File "/usr/lib/python3.5/asyncio/base_events.py", line 345, in run_forever
    self._run_once()
  File "/usr/lib/python3.5/asyncio/base_events.py", line 1324, in _run_once
    handle._run()
  File "/usr/lib/python3.5/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "/usr/lib/python3.5/asyncio/tasks.py", line 307, in _wakeup
    self._step()
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/usr/local/lib/python3.5/dist-packages/aiohttp-0.21.5-py3.5-linux-x86_64.egg/aiohttp/server.py", line 266, in start
    yield from self.handle_request(message, payload)
  File "/usr/local/lib/python3.5/dist-packages/aiohttp-0.21.5-py3.5-linux-x86_64.egg/aiohttp/web.py", line 90, in handle_request
    resp = yield from handler(request)
  File "/usr/local/lib/python3.5/dist-packages/gns3_server-1.5.3.dev1-py3.5.egg/gns3server/web/route.py", line 258, in vm_concurrency
    response = yield from control_schema(request)
  File "/usr/local/lib/python3.5/dist-packages/gns3_server-1.5.3.dev1-py3.5.egg/gns3server/web/route.py", line 191, in control_schema
    yield from func(request, response)
  File "/usr/local/lib/python3.5/dist-packages/gns3_server-1.5.3.dev1-py3.5.egg/gns3server/handlers/api/docker_handler.py", line 109, in start
    yield from container.start()
  File "/usr/local/lib/python3.5/dist-packages/gns3_server-1.5.3.dev1-py3.5.egg/gns3server/modules/docker/docker_vm.py", line 364, in start
    yield from self._start_console()
  File "/usr/local/lib/python3.5/dist-packages/gns3_server-1.5.3.dev1-py3.5.egg/gns3server/modules/docker/docker_vm.py", line 473, in _start_console
    asyncio.async(self._read_console_output(self._console_websocket, output_stream))
  File "/usr/lib/python3.5/asyncio/tasks.py", line 532, in async
    return ensure_future(coro_or_future, loop=loop)
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/usr/local/lib/python3.5/dist-packages/gns3_server-1.5.3.dev1-py3.5.egg/gns3server/modules/docker/docker_vm.py", line 491, in _read_console_output
    yield from self.stop()
  File "/usr/local/lib/python3.5/dist-packages/gns3_server-1.5.3.dev1-py3.5.egg/gns3server/modules/docker/docker_vm.py", line 541, in stop
    yield from self.manager.query("POST", "containers/{}/stop".format(self._cid), params={"t": 5})
  File "/usr/local/lib/python3.5/dist-packages/gns3_server-1.5.3.dev1-py3.5.egg/gns3server/modules/docker/__init__.py", line 85, in query
    response = yield from self.http_query(method, path, data=data, params=params)
  File "/usr/local/lib/python3.5/dist-packages/gns3_server-1.5.3.dev1-py3.5.egg/gns3server/modules/docker/__init__.py", line 129, in http_query
    raise DockerHttp404Error("Docker has returned an error: {} {}".format(response.status, body))
gns3server.modules.docker.docker_error.DockerHttp404Error: Docker has returned an error: 404 No such container: 840fc32a0c2e59196532fa295217e0507777c7c57a37b81edbcdfdb162ba8470
2016-09-01 09:54:40 INFO helpers.py:365 192.168.1.10 - - [01/Sep/2016:07:54:40 +0000] "DELETE /v1/projects/b4f3b796-7c3e-4927-a815-2b65f97dea25/docker/vms/94effe26-1112-4b77-8b3e-29a8ea2e730e HTTP/1.1" 204 0 "-" "GNS3 QT Client v1.5.3dev1"
```

**Comment by noplay** [comment]
Thanks it's fixed
