### ISSUE TITLE
Exception when stopping server

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-server#669]
```
2016-09-07 10:33:02 INFO local_server.py:475 Stopping local server (PID=23924)
Exception ignored in: Exception ignored in: <generator object start at 0x7f8eb4083e10>
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/aiohttp/server.py", line 312, in start
  File "/usr/lib/python3.4/asyncio/selector_events.py", line 568, in close
  File "/usr/lib/python3.4/asyncio/base_events.py", line 427, in call_soon
  File "/usr/lib/python3.4/asyncio/base_events.py", line 436, in _call_soon
  File "/usr/lib/python3.4/asyncio/base_events.py", line 265, in _check_closed
RuntimeError: Event loop is closed
Exception ignored in: 2016-09-07 10:33:05 INFO http_client.py:497 Response error: Connection refused (error: 1)
2016-09-07 10:33:05 ERROR compute_manager.py:60 Error while getting compute list: Connection refused
```

**Comment by noplay** [comment]
I reimplemented the cleanup using this sample:
http://aiohttp.readthedocs.io/en/stable/_modules/aiohttp/web.html#run_app
