### ISSUE TITLE
Uncaught exception when dynamips not in path when connecting to gns3server remotely 

### ISSUE THREAD

**Issue by linickx** [GNS3/gns3-server#67]
Hello,

I setup gns3server on a remote OS X server but forgot to update `$PATH` to include `dynamips.` When I connected from my remote gns3 client and tried to configure a router the client raised the following error:

```
Server error [-3200] : uncaught exception <class 'TypeError'>: stat: can't specify None for path argument
Traceback (most recent call last):
  File "/Users/nick/GNS3/gns3-server/lib/python3.4/site-packages/gns3_server-1.2.3-py3.4.egg/gns3server/modules/base.py", line 276, in _decode_request
    self.modules[self.name][destination](self, params)
  File "/Users/nick/GNS3/gns3-server/lib/python3.4/site-packages/gns3_server-1.2.3-py3.4.egg/gns3server/modules/dynamips/backends/vm.py", line 167, in vm_create
    self.start_hypervisor_manager()
  File "/Users/nick/GNS3/gns3-server/lib/python3.4/site-packages/gns3_server-1.2.3-py3.4.egg/gns3server/modules/dynamips/__init__.py", line 281, in start_hypervisor_manager
    if not os.path.isfile(self._dynamips):
  File "/Users/nick/GNS3/gns3-server/bin/../lib/python3.4/genericpath.py", line 30, in isfile
    st = os.stat(path)
TypeError: stat: can't specify None for path argument
```

Both client & server are OS X 10.10.2. Server is running Python 3.4.2

__Steps to reproduce.__

1. On Server, install `gns3server` as per [README](https://github.com/GNS3/gns3-server/blob/master/README.rst) . Upload router IOS image.

2. On Client, install GNS3 as _normal_ using drag and drop methodology. Disable local gns3server from running at GUI startup, configure remote server IP address and IOS image.

3. Start new project, drag router into workspace and observe console.

__Steps to fix.__

Either symlink `dynamips` to the same `bin` directory that `gns3server` lives in or add `dynamips` to path.

It looks like this is supposed to be caught on lines 115 -> 126 of [dynamips/__init__.py](https://github.com/GNS3/gns3-server/blob/master/gns3server/modules/dynamips/__init__.py#L115)

**Comment by noplay** [comment]
It's work in 1.3
