### ISSUE TITLE
Crash when exporting very large project

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-server#670]
Report from andrew
```
Traceback (most recent call last):
  File "/usr/share/gns3/gns3-server/lib/python3.5/site-packages/aiohttp/server.py", line 285, in start
    yield from self.handle_request(message, payload)
  File "/usr/share/gns3/gns3-server/lib/python3.5/site-packages/aiohttp/web.py", line 90, in handle_request
    resp = yield from handler(request)
  File "/usr/share/gns3/gns3-server/lib/python3.5/site-packages/gns3server/web/route.py", line 258, in vm_concurrency
    response = yield from control_schema(request)
  File "/usr/share/gns3/gns3-server/lib/python3.5/site-packages/gns3server/web/route.py", line 176, in control_schema
    yield from func(request, response)
  File "/usr/share/gns3/gns3-server/lib/python3.5/site-packages/gns3server/handlers/api/project_handler.py", line 372, in export_project
    for data in project.export(include_images=include_images):
  File "/usr/share/gns3/gns3-server/lib/python3.5/site-packages/zipstream/__init__.py", line 182, in __iter__
    for data in self.__write(**kwargs):
  File "/usr/share/gns3/gns3-server/lib/python3.5/site-packages/zipstream/__init__.py", line 276, in __write
    self._writecheck(zinfo)
  File "/usr/lib/python3.5/zipfile.py", line 1424, in _writecheck
    " would require ZIP64 extensions")

**Comment by noplay** [comment]
Good news it seem to be only a flag to enable:
https://docs.python.org/2/library/zipfile.html#zipfile-objects
