### ISSUE TITLE
Stop on non running Qemu trigger an error

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-server#71]
```
[E 150225 15:21:18 qemu_vm:304] error while stopping BigRam-1: Traceback (most recent call last):
      File "/Users/noplay/code/gns3/gns3-server/gns3server/web/route.py", line 129, in control_schema
        yield from func(request, response)
      File "/Users/noplay/code/gns3/gns3-server/gns3server/handlers/api/qemu_handler.py", line 173, in stop
        yield from vm.stop()
      File "/usr/local/Cellar/python3/3.4.2_1/Frameworks/Python.framework/Versions/3.4/lib/python3.4/asyncio/coroutines.py", line 141, in coro
        res = func(*args, **kw)
      File "/Users/noplay/code/gns3/gns3-server/gns3server/modules/qemu/qemu_vm.py", line 596, in stop
        self._process.terminate()
      File "/usr/local/Cellar/python3/3.4.2_1/Frameworks/Python.framework/Versions/3.4/lib/python3.4/asyncio/subprocess.py", line 133, in terminate
        self._check_alive()
      File "/usr/local/Cellar/python3/3.4.2_1/Frameworks/Python.framework/Versions/3.4/lib/python3.4/asyncio/subprocess.py", line 126, in _check_alive
        raise ProcessLookupError()
    ProcessLookupError
```

**Comment by noplay** [comment]
Probably related to #71
