### ISSUE TITLE
IOU stop

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-server#73]
If I start an IOU process and then stop it using the GUI I get the following error:

```
2015-02-25 18:31:03 ERROR base_events.py:698 Exception in callback <bound method SubprocessStreamProtocol.process_exited of <asyncio.subprocess.SubprocessStreamProtocol object at 0x7f81cc383dd8>>()
handle: Handle(<bound method SubprocessStreamProtocol.process_exited of <asyncio.subprocess.SubprocessStreamProtocol object at 0x7f81cc383dd8>>, ())
Traceback (most recent call last):
  File "/usr/lib/python3.4/asyncio/events.py", line 39, in _run
    self._callback(*self._args)
  File "/usr/lib/python3.4/asyncio/subprocess.py", line 80, in process_exited
    waiter.set_result(returncode)
  File "/usr/lib/python3.4/asyncio/futures.py", line 298, in set_result
    raise InvalidStateError('{}: {!r}'.format(self._state, self))
asyncio.futures.InvalidStateError: CANCELLED: Future<CANCELLED>
```

**Comment by noplay** [comment]
It's seem related to http://bugs.python.org/issue23140

**Comment by noplay** [comment]
I have write a workaround you can see it in 5a58f6efc82ca15346ce0efd3cfc6150bfa0013c
