### ISSUE TITLE
"GNS3 VM is starting", VMWare doesn't start VM

### ISSUE THREAD

**Issue by DeathCamel57** [GNS3/gns3-server#754]
## Similar to #275
**OS: Ubuntu 16.04.1 LTS**
**Release: 2.0.0a3** 
(built from source)
GNS3 tries to start the VM, but the VM is always shown as "GNS3 VM is starting" in the server list. However, VMWare doesn't start, nor the the VM start if VMWare is already open.
This happens every time that I open it, even after reboot.

[`# gns3 --debug` gns3_gui.log](https://gist.github.com/DeathCamel57/260056793dcaf7991d1a6b7305c67f0a)
[`# gns3 --debug` gns3_server.log](https://gist.github.com/DeathCamel57/5921000f10c68c0c8ec6062a0091715a)

**To be noted...**
There is a long error that appears after trying to change the GNS3-gui close behavior for the GNS3 VM.

## Information requested in #275 by @grossmj 
**Step 1**: ubridge is not listed as any process command in `sudo htop`
**Step 2**: 
![`ubridge -H 4242`](https://cloud.githubusercontent.com/assets/1226646/19879978/1bae1b8c-9fcf-11e6-9a0c-2d2313d0b765.png)

**Comment by noplay** [comment]
Seem to timeout when trying to connect to the GNS3 VM
```
2016-11-01 00:53:41 ERROR route.py:236 Uncaught exception detected: <class 'concurrent.futures._base.TimeoutError'>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/gns3_server-2.0.0a3-py3.5.egg/gns3server/web/route.py", line 197, in control_schema
    yield from func(request, response)
  File "/usr/local/lib/python3.5/dist-packages/gns3_server-2.0.0a3-py3.5.egg/gns3server/handlers/api/controller/gns3_vm_handler.py", line 78, in update
    yield from gns3_vm.update_settings(request.json)
  File "/usr/local/lib/python3.5/dist-packages/gns3_server-2.0.0a3-py3.5.egg/gns3server/controller/gns3vm/__init__.py", line 191, in update_settings
    yield from self.start()
  File "/usr/local/lib/python3.5/dist-packages/gns3_server-2.0.0a3-py3.5.egg/gns3server/utils/asyncio/__init__.py", line 148, in new_function
    return (yield from f(*args, **kwargs))
  File "/usr/local/lib/python3.5/dist-packages/gns3_server-2.0.0a3-py3.5.egg/gns3server/controller/gns3vm/__init__.py", line 269, in start
    force=True)
  File "/usr/local/lib/python3.5/dist-packages/gns3_server-2.0.0a3-py3.5.egg/gns3server/controller/__init__.py", line 261, in add_compute
    yield from compute.connect()
  File "/usr/local/lib/python3.5/dist-packages/gns3_server-2.0.0a3-py3.5.egg/gns3server/controller/compute.py", line 364, in connect
    response = yield from self._run_http_query("GET", "/capabilities")
  File "/usr/local/lib/python3.5/dist-packages/gns3_server-2.0.0a3-py3.5.egg/gns3server/controller/compute.py", line 468, in _run_http_query
    response = yield from self._session().request(method, url, headers=headers, data=data, auth=self._auth, chunked=chunked, timeout=timeout)
  File "/usr/local/lib/python3.5/dist-packages/aiohttp-1.0.5-py3.5-linux-x86_64.egg/aiohttp/client.py", line 555, in __iter__
    resp = yield from self._coro
  File "/usr/local/lib/python3.5/dist-packages/aiohttp-1.0.5-py3.5-linux-x86_64.egg/aiohttp/client.py", line 198, in _request
    conn = yield from self._connector.connect(req)
  File "/usr/local/lib/python3.5/dist-packages/async_timeout-1.1.0-py3.5.egg/async_timeout/__init__.py", line 44, in __exit__
    raise asyncio.TimeoutError from None
concurrent.futures._base.TimeoutError
```

**Comment by DeathCamel57** [comment]
Any information that I can post that might help?

**Comment by DeathCamel57** [comment]
Also, 127.0.0.1:3080 does have the webserver running

**Comment by DeathCamel57** [comment]
Also, I've tried starting the GNS3 VM before starting GNS3, and that doesn't work either.
![VM already running](https://cloud.githubusercontent.com/assets/1226646/19899129/4725a21a-a035-11e6-97d3-3e8040fad6f3.png)


**Debug info requested**
[ Help -> Export debug](https://github.com/GNS3/gns3-server/files/564582/debug-info-gns3-2.0.0a3.zip)

**Comment by DeathCamel57** [comment]
Hrm... odd... It started once a few days ago properly, but it stopped for a while, this start though, it worked fine...
Seems like 10% of the time it works

**Comment by noplay** [comment]
If you change the stop mode from suspend to stop does it work better?

**Comment by DeathCamel57** [comment]
no difference.

**Comment by noplay** [comment]
Could you:
* reboot (to be sure no ghost process is running)
* open GNS3
* wait 5 minutes
* go to Help / Export debug informations
* send us the zip developers@gns3.net (I prefer that you email the zip because the zip contains the process list could be a sensitive info)

No need to rush for sending that we are already busy fixing other 2.0 bugs.

Thanks for the help

**Comment by DeathCamel57** [comment]
Sent a few zips... Next time it works, I'll send that zip too. Thanks for maintaining and making this software though. I love it.

**Comment by noplay** [comment]
I think we have solve bugs related to that. If after using last source code you still have the issue don't hesitate to comment.

**Comment by DeathCamel57** [comment]
Just pulled source code, built, and same issue. Emailing the debug info zips

**Comment by noplay** [comment]
It seem you have a permission issue in your ~/.config/GNS3 you have file owned by root. But it's not the issue.

I pushed a new version based on your feedbacks, I hope it's fixe your issues. Thanks for the help
