### ISSUE TITLE
Error while retrieving IOU images list from server

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-server#764]
```
2016-11-06 11:35:05 ERROR route.py:236 Uncaught exception detected: <class 'FileNotFoundError'>
Traceback (most recent call last):
  File "/home/grossmj/PycharmProjects/gns3-server/gns3server/web/route.py", line 197, in control_schema
    yield from func(request, response)
  File "/home/grossmj/PycharmProjects/gns3-server/gns3server/handlers/api/compute/iou_handler.py", line 316, in list_iou_images
    images = yield from iou_manager.list_images()
  File "/usr/lib/python3.4/asyncio/coroutines.py", line 141, in coro
    res = func(*args, **kw)
  File "/home/grossmj/PycharmProjects/gns3-server/gns3server/compute/base_manager.py", line 490, in list_images
    "filesize": os.stat(os.path.join(root, filename)).st_size})
FileNotFoundError: [Errno 2] No such file or directory: '/home/grossmj/GNS3/images/IOU/i86bi-linux-l2-adventerprisek9-15.1a.bin'
```

**Comment by noplay** [comment]
Weird it seem during the listing the image file as disapear
