### ISSUE TITLE
Traceback if no project name in the API project creating requests

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-server#783]
```
2016-11-14 10:58:27 ERROR route.py:236 Uncaught exception detected: <class 'AssertionError'>
Traceback (most recent call last):
  File "/Users/noplay/code/gns3/gns3-server/gns3server/web/route.py", line 197, in control_schema
    yield from func(request, response)
  File "/Users/noplay/code/gns3/gns3-server/gns3server/handlers/api/controller/project_handler.py", line 70, in create_project
    project_id=request.json.get("project_id"))
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/coroutines.py", line 206, in coro
    res = func(*args, **kw)
  File "/Users/noplay/code/gns3/gns3-server/gns3server/controller/__init__.py", line 334, in add_project
    project = Project(project_id=project_id, controller=self, name=name, **kwargs)
  File "/Users/noplay/code/gns3/gns3-server/gns3server/controller/project.py", line 73, in __init__
    assert name is not None
AssertionError
```

**Comment by noplay** [comment]
I think it's missing in the schema

**Comment by noplay** [comment]
Same for compute_id missing in node:
Traceback (most recent call last):
  File "/Users/noplay/code/gns3/gns3-server/gns3server/web/route.py", line 197, in control_schema
    yield from func(request, response)
  File "/Users/noplay/code/gns3/gns3-server/gns3server/handlers/api/controller/node_handler.py", line 50, in create
    compute = controller.get_compute(request.json.pop("compute_id"))
KeyError: 'compute_id'
```
