### ISSUE TITLE
Crash when you connect a GUI to project already opened

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-server#784]
```
Traceback (most recent call last):
  File "/Users/noplay/code/gns3/gns3-server/gns3server/web/route.py", line 197, in control_schema
    yield from func(request, response)
  File "/Users/noplay/code/gns3/gns3-server/gns3server/handlers/api/controller/project_handler.py", line 174, in load
    project = yield from controller.load_project(request.json.get("path"),)
  File "/Users/noplay/code/gns3/gns3-server/gns3server/controller/__init__.py", line 370, in load_project
    yield from project.open()
  File "/Users/noplay/code/gns3/gns3-server/gns3server/controller/project.py", line 655, in open
    os.remove(path + ".backup")
FileNotFoundError: [Errno 2] No such file or directory: '/Users/noplay/GNS3/projects/9e26e37d-4962-4921-8c0e-136d3b04ba9c/random.gns3.backup'
```

**Comment by noplay** [comment]
I think it's related to https://github.com/GNS3/gns3-server/issues/782
