### ISSUE TITLE
Controller crashes, if remote server has version 1.x

### ISSUE THREAD

**Issue by ehlers** [GNS3/gns3-server#810]
GNS3 version 2.0.0dev5 on Darwin (64-bit) with Python 3.5.2 Qt 5.7.0 and PyQt 5.7.

Initially only a local server is configured. Then a add a remote server, which is still running on v1.x.

The GUI rightfully complains with `The server f8cefa89-ecd2-43c8-ab66-08d21f298117 is not a GNS3 server or it's a 1.X server`.

Now I stop, then restart the GUI (and local server). On this new start the server crashes:
```
2016-12-06 14:51:13 INFO web_server.py:316 Starting server on 192.168.1.10:3080
2016-12-06 14:51:13 INFO __init__.py:52 Load controller configuration file /Users/behlers/.config/GNS3/gns3_controller.conf
2016-12-06 14:51:13 INFO __init__.py:56 Start controller
2016-12-06 14:51:13 INFO compute.py:80 Create compute f8cefa89-ecd2-43c8-ab66-08d21f298117
2016-12-06 14:51:13 CRITICAL run.py:271 Critical error while running the server: Conflict
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/gns3_server-2.0.0.dev5-py3.5.egg/gns3server/controller/compute.py", line 365, in connect
    response = yield from self._run_http_query("GET", "/capabilities")
  File "/usr/local/lib/python3.5/site-packages/gns3_server-2.0.0.dev5-py3.5.egg/gns3server/controller/compute.py", line 498, in _run_http_query
    raise aiohttp.web.HTTPNotFound(text="{} {} not found".format(method, path))
aiohttp.web_exceptions.HTTPNotFound: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/gns3_server-2.0.0.dev5-py3.5.egg/gns3server/run.py", line 265, in run
    server.run()
  File "/usr/local/lib/python3.5/site-packages/gns3_server-2.0.0.dev5-py3.5.egg/gns3server/web/web_server.py", line 318, in run
    if self._run_application(self._handler, ssl_context) is False:
  File "/usr/local/lib/python3.5/site-packages/gns3_server-2.0.0.dev5-py3.5.egg/gns3server/web/web_server.py", line 83, in _run_application
    self._server, startup_res = self._loop.run_until_complete(asyncio.gather(srv, self._app.startup(), loop=self._loop))
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/base_events.py", line 387, in run_until_complete
    return future.result()
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/usr/local/lib/python3.5/site-packages/aiohttp-1.1.6-py3.5-macosx-10.11-x86_64.egg/aiohttp/web.py", line 328, in startup
    yield from self.on_startup.send(self)
  File "/usr/local/lib/python3.5/site-packages/aiohttp-1.1.6-py3.5-macosx-10.11-x86_64.egg/aiohttp/signals.py", line 48, in send
    yield from self._send(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/aiohttp-1.1.6-py3.5-macosx-10.11-x86_64.egg/aiohttp/signals.py", line 16, in _send
    yield from res
  File "/usr/local/lib/python3.5/site-packages/gns3_server-2.0.0.dev5-py3.5.egg/gns3server/web/web_server.py", line 258, in _on_startup
    yield from Controller.instance().start()
  File "/usr/local/lib/python3.5/site-packages/gns3_server-2.0.0.dev5-py3.5.egg/gns3server/controller/__init__.py", line 57, in start
    yield from self.load()
  File "/usr/local/lib/python3.5/site-packages/gns3_server-2.0.0.dev5-py3.5.egg/gns3server/controller/__init__.py", line 140, in load
    yield from self.add_compute(**c)
  File "/usr/local/lib/python3.5/site-packages/gns3_server-2.0.0.dev5-py3.5.egg/gns3server/controller/__init__.py", line 261, in add_compute
    yield from compute.connect()
  File "/usr/local/lib/python3.5/site-packages/gns3_server-2.0.0.dev5-py3.5.egg/gns3server/utils/asyncio/__init__.py", line 151, in new_function
    return (yield from f(*args, **kwargs))
  File "/usr/local/lib/python3.5/site-packages/gns3_server-2.0.0.dev5-py3.5.egg/gns3server/controller/compute.py", line 372, in connect
    raise aiohttp.web.HTTPConflict(text="The server {} is not a GNS3 server or it's a 1.X server".format(self._id))
aiohttp.web_exceptions.HTTPConflict: Conflict
2016-12-06 14:51:15 INFO crash_report.py:109 Crash report sent with event ID: 369be899e3ec45f8b694289dfbe8b3ce
```

**Comment by noplay** [comment]
Thanks fixed
