### ISSUE TITLE
Can't add link to running docker instance

### ISSUE THREAD

**Issue by ehlers** [GNS3/gns3-server#817]
GNS3 version 2.0.0dev6 on Darwin (64-bit) with Python 3.5.2 Qt 5.7.0 and PyQt 5.7.

- start with empty project
- add 2 alpine docker VMs (don't interconnect them)
- start both VMs
- try to create connection between both VMs  
   -> Error while creating link: bridge 'bridge0' already exist: 

Server log from the start of the VMs:
```
2016-12-10 11:33:37 INFO base_node.py:536 Starting new uBridge hypervisor 0.0.0.0:53503
2016-12-10 11:33:37 INFO hypervisor.py:163 starting ubridge: ['/usr/local/bin/ubridge', '-H', '0.0.0.0:53503']
2016-12-10 11:33:37 INFO hypervisor.py:165 logging to /opt/gns3/projects/ba3cc636-ab5f-4f8e-8ad4-3bf235d84491/project-files/docker/db6a3e2c-f18d-49b5-94c8-17842fe8e76c/ubridge.log
2016-12-10 11:33:37 INFO base_node.py:536 Starting new uBridge hypervisor 0.0.0.0:48327
2016-12-10 11:33:37 INFO hypervisor.py:173 ubridge started PID=3465
2016-12-10 11:33:37 INFO base_node.py:538 Hypervisor 0.0.0.0:53503 has successfully started
2016-12-10 11:33:37 INFO hypervisor.py:163 starting ubridge: ['/usr/local/bin/ubridge', '-H', '0.0.0.0:48327']
2016-12-10 11:33:37 INFO hypervisor.py:165 logging to /opt/gns3/projects/ba3cc636-ab5f-4f8e-8ad4-3bf235d84491/project-files/docker/55079b1c-9dfb-4ca4-9318-b1a442b031aa/ubridge.log
2016-12-10 11:33:37 INFO hypervisor.py:173 ubridge started PID=3467
2016-12-10 11:33:37 INFO base_node.py:538 Hypervisor 0.0.0.0:48327 has successfully started
2016-12-10 11:33:37 INFO ubridge_hypervisor.py:84 Connected to uBridge hypervisor after 0.0142 seconds
2016-12-10 11:33:37 INFO ubridge_hypervisor.py:84 Connected to uBridge hypervisor after 0.0143 seconds
2016-12-10 11:33:37 INFO docker_vm.py:381 Docker container 'alpine-1' [be/alpine:latest] started listen for telnet on 5000
2016-12-10 11:33:37 INFO helpers.py:454 192.168.1.10 - - [10/Dec/2016:10:33:37 +0000] "POST /v2/compute/projects/ba3cc636-ab5f-4f8e-8ad4-3bf235d84491/docker/nodes/db6a3e2c-f18d-49b5-94c8-17842fe8e76c/start HTTP/1.1" 204 0 "-" "Python/3.5 aiohttp/1.1.6"
2016-12-10 11:33:37 INFO docker_vm.py:381 Docker container 'alpine-2' [be/alpine:latest] started listen for telnet on 5002
2016-12-10 11:33:37 INFO helpers.py:454 192.168.1.10 - - [10/Dec/2016:10:33:37 +0000] "POST /v2/compute/projects/ba3cc636-ab5f-4f8e-8ad4-3bf235d84491/docker/nodes/55079b1c-9dfb-4ca4-9318-b1a442b031aa/start HTTP/1.1" 204 0 "-" "Python/3.5 aiohttp/1.1.6"
2016-12-10 11:33:44 INFO helpers.py:454 192.168.1.10 - - [10/Dec/2016:10:33:44 +0000] "POST /v2/compute/projects/ba3cc636-ab5f-4f8e-8ad4-3bf235d84491/ports/udp HTTP/1.1" 201 25 "-" "Python/3.5 aiohttp/1.1.6"
2016-12-10 11:33:44 INFO helpers.py:454 192.168.1.10 - - [10/Dec/2016:10:33:44 +0000] "POST /v2/compute/projects/ba3cc636-ab5f-4f8e-8ad4-3bf235d84491/ports/udp HTTP/1.1" 201 25 "-" "Python/3.5 aiohttp/1.1.6"
2016-12-10 11:33:44 ERROR route.py:212 Node error detected: UbridgeError
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/gns3_server-2.0.0.dev6-py3.5.egg/gns3server/compute/base_node.py", line 516, in _ubridge_send
    yield from self._ubridge_hypervisor.send(command)
  File "/usr/local/lib/python3.5/dist-packages/gns3_server-2.0.0.dev6-py3.5.egg/gns3server/utils/asyncio/__init__.py", line 151, in new_function
    return (yield from f(*args, **kwargs))
  File "/usr/local/lib/python3.5/dist-packages/gns3_server-2.0.0.dev6-py3.5.egg/gns3server/ubridge/ubridge_hypervisor.py", line 248, in send
    raise UbridgeError(data[-1][4:])
gns3server.ubridge.ubridge_error.UbridgeError: bridge 'bridge0' already exist

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/gns3_server-2.0.0.dev6-py3.5.egg/gns3server/web/route.py", line 197, in control_schema
    yield from func(request, response)
  File "/usr/local/lib/python3.5/dist-packages/gns3_server-2.0.0.dev6-py3.5.egg/gns3server/handlers/api/compute/docker_handler.py", line 203, in create_nio
    yield from container.adapter_add_nio_binding(int(request.match_info["adapter_number"]), nio)
  File "/usr/local/lib/python3.5/dist-packages/gns3_server-2.0.0.dev6-py3.5.egg/gns3server/compute/docker/docker_vm.py", line 710, in adapter_add_nio_binding
    yield from self._ubridge_send('bridge create bridge{}'.format(adapter_number))
  File "/usr/local/lib/python3.5/dist-packages/gns3_server-2.0.0.dev6-py3.5.egg/gns3server/compute/base_node.py", line 518, in _ubridge_send
    raise UbridgeError("{}: {}".format(e, self._ubridge_hypervisor.read_stdout()))
gns3server.ubridge.ubridge_error.UbridgeError: bridge 'bridge0' already exist:
2016-12-10 11:33:44 INFO helpers.py:454 192.168.1.10 - - [10/Dec/2016:10:33:44 +0000] "POST /v2/compute/projects/ba3cc636-ab5f-4f8e-8ad4-3bf235d84491/docker/nodes/db6a3e2c-f18d-49b5-94c8-17842fe8e76c/adapters/0/ports/0/nio HTTP/1.1" 409 105 "-" "Python/3.5 aiohttp/1.1.6"
```

**Comment by noplay** [comment]
The problem was introduce when we replaced  the veth by the tap. In ubridge veth are independent of a bridge when  the tap are always link to a bridge, and modify a bridge is not supported.

**Comment by noplay** [comment]
Should be fix with last ubridge code and last server code. This will require more tests to be sure I didn't introduce side effects.

Now when we change a hotlink we do not delete the ubridge bridge but we update it. Because it's the first time ubridge support bridge update we will need to test this carefully.
