### ISSUE TITLE
Can't delete link between docker VM after they were in use

### ISSUE THREAD

**Issue by ehlers** [GNS3/gns3-server#818]
GNS3 version 2.0.0dev6 on Darwin (64-bit) with Python 3.5.2 Qt 5.7.0 and PyQt 5.7.

- start with empty project
- add 2 alpine docker VMs
- interconnect them
- start all/both VMs
- stop all/bothl VMs
- try to delete connection between both VMs  
   => Error while deleting link: Cannot send command 'bridge delete bridge0': uBridge is not running

Server log from the stop of the VMs:
```
2016-12-10 11:47:57 INFO base_node.py:548 Stopping uBridge hypervisor 0.0.0.0:45739
2016-12-10 11:47:57 INFO hypervisor.py:197 Stopping uBridge process PID=3848
2016-12-10 11:47:57 INFO base_node.py:548 Stopping uBridge hypervisor 0.0.0.0:58681
2016-12-10 11:47:57 INFO hypervisor.py:197 Stopping uBridge process PID=3845
2016-12-10 11:47:57 INFO docker_vm.py:559 Docker container 'alpine-2' [be/alpine:latest] stopped
2016-12-10 11:47:57 INFO helpers.py:454 192.168.1.10 - - [10/Dec/2016:10:47:57 +0000] "POST /v2/compute/projects/a7f5ee01-08f9-4d6f-b545-23911207bbe5/docker/nodes/b4f0b789-6396-4396-85bf-f22041b8b78b/stop HTTP/1.1" 204 0 "-" "Python/3.5 aiohttp/1.1.6"
2016-12-10 11:47:57 INFO docker_vm.py:559 Docker container 'alpine-1' [be/alpine:latest] stopped
2016-12-10 11:47:57 INFO helpers.py:454 192.168.1.10 - - [10/Dec/2016:10:47:57 +0000] "POST /v2/compute/projects/a7f5ee01-08f9-4d6f-b545-23911207bbe5/docker/nodes/2ff709f9-8781-4337-9f1f-ddd49dc09107/stop HTTP/1.1" 204 0 "-" "Python/3.5 aiohttp/1.1.6"
2016-12-10 11:48:04 ERROR route.py:212 Node error detected: NodeError
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/gns3_server-2.0.0.dev6-py3.5.egg/gns3server/web/route.py", line 197, in control_schema
    yield from func(request, response)
  File "/usr/local/lib/python3.5/dist-packages/gns3_server-2.0.0.dev6-py3.5.egg/gns3server/handlers/api/compute/docker_handler.py", line 224, in delete_nio
    yield from container.adapter_remove_nio_binding(int(request.match_info["adapter_number"]))
  File "/usr/local/lib/python3.5/dist-packages/gns3_server-2.0.0.dev6-py3.5.egg/gns3server/compute/docker/docker_vm.py", line 759, in adapter_remove_nio_binding
    yield from self._delete_ubridge_connection(adapter_number)
  File "/usr/local/lib/python3.5/dist-packages/gns3_server-2.0.0.dev6-py3.5.egg/gns3server/compute/docker/docker_vm.py", line 686, in _delete_ubridge_connection
    yield from self._ubridge_send("bridge delete bridge{name}".format(name=adapter_number))
  File "/usr/local/lib/python3.5/dist-packages/gns3_server-2.0.0.dev6-py3.5.egg/gns3server/compute/base_node.py", line 514, in _ubridge_send
    raise NodeError("Cannot send command '{}': uBridge is not running".format(command))
gns3server.compute.error.NodeError: Cannot send command 'bridge delete bridge0': uBridge is not running
2016-12-10 11:48:04 INFO helpers.py:454 192.168.1.10 - - [10/Dec/2016:10:48:04 +0000] "DELETE /v2/compute/projects/a7f5ee01-08f9-4d6f-b545-23911207bbe5/docker/nodes/2ff709f9-8781-4337-9f1f-ddd49dc09107/adapters/0/ports/0/nio HTTP/1.1" 409 137 "-" "Python/3.5 aiohttp/1.1.6"
```

**Comment by noplay** [comment]
Issue confirmed

**Comment by noplay** [comment]
Thanks it's fixed I found other bug on docker support that I will fix.
