### ISSUE TITLE
Issues with Raven on Windows

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-server#82]
Raven has an issue (apparently tries to use asyncio?). I have tested on Windows.

First test with a division by zero just before running the asynio loop (maybe this is why...).

```
2015-03-03 01:29:04 INFO main.py:160 Running with Python 3.4.2 and has PID 4304
2015-03-03 01:29:04 CRITICAL main.py:181 Critical error while running the server
: division by zero
Traceback (most recent call last):
  File "main.py", line 178, in main
    test = 1/0
ZeroDivisionError: division by zero
2015-03-03 01:29:04 ERROR base_events.py:912 Task was destroyed but it is pendin
g!
task: <Task pending coro=<f() running at C:\Python34-64bit\lib\site-packages\rav
en-5.2.0-py3.4.egg\raven\transport\aiohttp.py:52>>

C:\Users\GNS3\Documents\GNS3 build for Windows\gns3-server\gns3server>
```

Second test in the version handler:

```
2015-03-03 01:33:46 INFO server.py:169 127.0.0.1 - - Tue, 03 Mar 2015 01:33:46 G
MT "GET /v1/version HTTP/1.1" 500 761 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64; r
v:35.0) Gecko/20100101 Firefox/35.0"
Unable to reach Sentry log server:  (url: aiohttp+https://app.getsentry.com/api/
38482/store/)
Traceback (most recent call last):
  File "C:\Python34-64bit\lib\site-packages\raven-5.2.0-py3.4.egg\raven\transpor
t\aiohttp.py", line 62, in f
    loop=self._loop)
  File "C:\Python34-64bit\lib\asyncio\tasks.py", line 375, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError
2015-03-03 01:33:47 ERROR base.py:562 Unable to reach Sentry log server:  (url:
aiohttp+https://app.getsentry.com/api/38482/store/)
Traceback (most recent call last):
  File "C:\Python34-64bit\lib\site-packages\raven-5.2.0-py3.4.egg\raven\transpor
t\aiohttp.py", line 62, in f
    loop=self._loop)
  File "C:\Python34-64bit\lib\asyncio\tasks.py", line 375, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError
Failed to submit message: 'ZeroDivisionError: division by zero'
2015-03-03 01:33:47 ERROR base.py:565 Failed to submit message: 'ZeroDivisionErr
or: division by zero'
```

**Comment by noplay** [comment]
Fixed, now the error report is synchronous it's avoid losting events. I don't think performance issue to error report is a problem. And sentry no longer send his traceback to the console
