### ISSUE TITLE
"Start/Resume all devices" creates error on already running docker VMs

### ISSUE THREAD

**Issue by ehlers** [GNS3/gns3-server#839]
GNS3 version 2.0.0dev6 on Darwin (64-bit) with Python 3.5.2 Qt 5.7.0 and PyQt 5.7.

* create new project
* move alpine docker VM into the project
* start it
* hit the "Start/Resume all devices" button

The GUI shows `Docker has returned an error: 304 b''` error

Normally this situation happens, when some docker devices are already running, add some new devices and want to start them all. But this error happen also without adding anything, just hitting the "Start/Resume all devices" button when some docker VMs are already running.

Server log:
```
2016-12-16 11:10:09 ERROR route.py:212 Node error detected: DockerHttp304Error
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/gns3_server-2.0.0.dev6-py3.5.egg/gns3server/web/route.py", line 197, in control_schema
    yield from func(request, response)
  File "/usr/local/lib/python3.5/dist-packages/gns3_server-2.0.0.dev6-py3.5.egg/gns3server/handlers/api/compute/docker_handler.py", line 87, in start
    yield from container.start()
  File "/usr/local/lib/python3.5/dist-packages/gns3_server-2.0.0.dev6-py3.5.egg/gns3server/compute/docker/docker_vm.py", line 350, in start
    yield from self.manager.query("POST", "containers/{}/start".format(self._cid))
  File "/usr/local/lib/python3.5/dist-packages/gns3_server-2.0.0.dev6-py3.5.egg/gns3server/compute/docker/__init__.py", line 85, in query
    response = yield from self.http_query(method, path, data=data, params=params)
  File "/usr/local/lib/python3.5/dist-packages/gns3_server-2.0.0.dev6-py3.5.egg/gns3server/compute/docker/__init__.py", line 127, in http_query
    raise DockerHttp304Error("Docker has returned an error: {} {}".format(response.status, body))
gns3server.compute.docker.docker_error.DockerHttp304Error: Docker has returned an error: 304 b''
2016-12-16 11:10:09 INFO helpers.py:454 192.168.1.10 - - [16/Dec/2016:10:10:09 +0000] "POST /v2/compute/projects/79930f33-7e40-4ead-bc2e-1d4c1982d53e/docker/nodes/8a8a400e-bdd8-4e4c-9884-8a2fc8c50c24/start HTTP/1.1" 409 116 "-" "Python/3.5 aiohttp/1.1.6"
```

**Comment by noplay** [comment]
Thanks it's fixed
