### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-server#861]
https://sentry.io/gns3/gns3-server/issues/202535144/

```
TypeError: 'NoneType' object is not iterable
  File "gns3server/web/route.py", line 197, in control_schema
    yield from func(request, response)
  File "gns3server/handlers/api/compute/docker_handler.py", line 323, in show
    images = yield from docker_manager.list_images()
  File "gns3server/compute/docker/__init__.py", line 160, in list_images
    for tag in image['RepoTags']:

TypeError: 'NoneType' object is not iterable
```

**Comment by gmu-msk** [comment]
Is there any workaround in 1.5.3?

**Comment by noplay** [comment]
You get the exact  same error on 1.5.3?

**Comment by gmu-msk** [comment]
it looks almost the same:
`Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/gns3server/web/route.py", line 191, in control_schema
    yield from func(request, response)
  File "/usr/lib/python3.6/site-packages/gns3server/handlers/api/docker_handler.py", line 47, in show
    images = yield from docker_manager.list_images()
  File "/usr/lib/python3.6/site-packages/gns3server/modules/docker/__init__.py", line 160, in list_images
    for tag in image['RepoTags']:
TypeError: 'NoneType' object is not iterable`
GNS3 1.5.3
Archlinux
I created docker-container from Dockerfile. Then added it to GNS3. Then deleted it from GNS3 and from docker images. Modified Dockerfile and built it with the same image name. When I try to import any new docker container by pressing button "New" in "Preferences -> Docker -> Docker Containers" I get this error.

**Comment by gmu-msk** [comment]
Checked docker images on host again. Found two images with the same name. Removed it with --force flag and built again.
Now everything in GNS3 works fine!
