### ISSUE TITLE
Exception when loading project containing a VirtualBox VM

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-server#865]
```
2017-01-13 23:45:58 INFO virtualbox_vm.py:185 VirtualBox VM 'LinuxTinycore3.8.2-1' [b9e6b64e-50ab-4d4b-b3fa-e53a63bd4ecd] created
2017-01-13 23:45:58 ERROR route.py:236 Uncaught exception detected: <class 'AttributeError'>
Traceback (most recent call last):
  File "/home/grossmj/PycharmProjects/gns3-server/gns3server/web/route.py", line 197, in control_schema
    yield from func(request, response)
  File "/home/grossmj/PycharmProjects/gns3-server/gns3server/handlers/api/compute/virtualbox_handler.py", line 61, in create
    adapters=request.json.get("adapters", 0))
  File "/home/grossmj/PycharmProjects/gns3-server/gns3server/compute/base_manager.py", line 252, in create_node
    yield from node.create()
  File "/home/grossmj/PycharmProjects/gns3-server/gns3server/compute/virtualbox/virtualbox_vm.py", line 189, in create
    self._patch_vm_uuid()
  File "/home/grossmj/PycharmProjects/gns3-server/gns3server/compute/virtualbox/virtualbox_vm.py", line 212, in _patch_vm_uuid
    machine.set("uuid", "{" + self.id + "}")
AttributeError: 'NoneType' object has no attribute 'set'
```

**Comment by grossmj** [comment]
I still have the issue :(

**Comment by noplay** [comment]
It with Github down the push has failed
