### ISSUE TITLE
netifaces dependency creates install issues.

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-server#97]
Ubuntu 14.04, upgrading from GNS3-1.2.3 to 1.3.0rc1.dev1

```
Processing dependencies for gns3-server==1.3.0rc1.dev1
Searching for netifaces==0.10.4
Reading https://pypi.python.org/simple/netifaces/
Best match: netifaces 0.10.4
Downloading https://pypi.python.org/packages/source/n/netifaces/netifaces-0.10.4.tar.gz#md5=36da76e2cfadd24cc7510c2c0012eb1e
Processing netifaces-0.10.4.tar.gz
Writing /tmp/easy_install-r04gfbhx/netifaces-0.10.4/setup.cfg
Running netifaces-0.10.4/setup.py -q bdist_egg --dist-dir /tmp/easy_install-r04gfbhx/netifaces-0.10.4/egg-dist-tmp-xq3is6d3
Traceback (most recent call last):
  File "setup.py", line 80, in <module>
    "Programming Language :: Python :: Implementation :: CPython",
  File "/usr/lib/python3.4/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.4/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.4/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 73, in run
    self.do_egg_install()
  File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 96, in do_egg_install
    cmd.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 381, in run
    self.easy_install(spec, not self.no_deps)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 597, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 648, in install_item
    self.process_distribution(spec, dist, deps)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 694, in process_distribution
    [requirement], self.local_index, self.easy_install
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 620, in resolve
    dist = best[req.key] = env.best_match(req, ws, installer)
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 858, in best_match
    return self.obtain(req, installer) # try and download/install
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 870, in obtain
    return installer(requirement)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 616, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 646, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 834, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 1040, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 1025, in run_setup
    run_setup(setup_script, args)
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 50, in run_setup
    lambda: execfile(
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 100, in run
    return func()
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 52, in <lambda>
    {'__file__':setup_script, '__name__':'__main__'}
  File "/usr/lib/python3/dist-packages/setuptools/compat.py", line 78, in execfile
    exec(compile(source, fn, 'exec'), globs, locs)
  File "setup.py", line 17, in <module>
   
AttributeError: 'dict' object has no attribute 'print'
```

I've disabled the installation of netifaces in the setup.py for now.

**Comment by noplay** [comment]
It's a netifaces bug:
https://bitbucket.org/al45tair/netifaces/issue/13/0104-install-is-broken-on-python-3x

**Comment by noplay** [comment]
No news from netficase

**Comment by noplay** [comment]
No news from the developers. Should we release a GNS3 netifaces on pypi ?

On Wed, Jun 3, 2015 at 8:14 PM, Jeremy Grossmann <notifications@github.com>
wrote:

> Assigned #97 <https://github.com/GNS3/gns3-server/issues/97> to @noplay
> <https://github.com/noplay>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GNS3/gns3-server/issues/97#event-321635967>.
>



-- 

*JULIEN DUPONCHELLE*
Software Engineer

E: julien@gns3.com
LinkedIn <http://linkedin.com/in/julienduponchelle/>

<http://www.linkedin.com/in/stephenguppy>288, 200 – Rivercrest Drive SE
Calgary, AB, T2T 2X5
Twitter <http://www.twitter.com/gns3_official> | Facebook
<https://www.facebook.com/gns3official> | LinkedIn
<http://www.linkedin.com/company/gns3-net> | Google+
<https://plus.google.com/+Gns3Net/posts> | CrunchBase
<http://www.crunchbase.com/organization/gns3>

**Comment by grossmj** [comment]
We may have to.

**Comment by noplay** [comment]
@dlintott what did you think about this issue? 

The project netifaces seem to be dead. Debian provide a patch for Python 3 so the user can install netifaces without issues from debian but not from pypi.

We have two solutions:
* release a gns3-netifaces on Pypi a keeping the name netifaces in our imports
* release netifaces under a totally new name like awesomeifaces and change our Python import to awesomeifaces

Solution 1 seem to be the way to go, does it create an issue with your packaging?

Solution 2 require you to create a totally new package I don't think it's a good idea.

**Comment by dlintott** [comment]
Solution #1 is definitely the easiest way for me and already added as a dependency in the deb packaging 

Solution #2 might not even make it into Debian as it would be duplicated code.

**Comment by noplay** [comment]
Ok solution 1 is done :)

**Comment by noplay** [comment]
Already 256 download :) 
https://pypi.python.org/pypi/gns3-netifaces/0.10.4.1
