### ISSUE TITLE
File "C:\Users\noplay\AppData\Local\Programs\Python\Python35\lib\ntpath.py", line 139, in splitdrive TypeError: object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by liamtoh06** [GNS3/gns3-server#978]
Traceback (most recent call last):
  File "./gns3-server\gns3server\web\route.py", line 191, in control_schema
  File "./gns3-server\gns3server\handlers\api\vmware_handler.py", line 47, in index
  File "./gns3-server\gns3server\modules\vmware\__init__.py", line 672, in list_vms
  File "./gns3-server\gns3server\modules\vmware\__init__.py", line 200, in check_vmware_version
  File "./gns3-server\gns3server\modules\vmware\__init__.py", line 163, in _check_vmware_player_requirements
  File "./gns3-server\gns3server\modules\vmware\__init__.py", line 414, in check_vmrun_version
  File "./gns3-server\gns3server\modules\vmware\__init__.py", line 110, in find_vmrun
  File "C:\Users\noplay\AppData\Local\Programs\Python\Python35\lib\ntpath.py", line 69, in isabs
  File "C:\Users\noplay\AppData\Local\Programs\Python\Python35\lib\ntpath.py", line 139, in splitdrive
TypeError: object of type 'NoneType' has no len()

**Comment by noplay** [comment]
VMware is installed on your system?
